### ISSUE TITLE
Requesting to allow for autodetecting the line separators based on a file to be parsed

### ISSUE THREAD

**Issue by compellon** [uniVocity/univocity-parsers#10]
Hi,

We are switching from opencsv parser to univocity cvs + tsv parsers. 
As of 1.3.2 version, there is no way to detect the line end character for files and thus automatically choose a line separator that would commonly work for all our cvs and tsv files independent of the OS. We would like to put a feature request to enable univocity parsers, given a file,  to auto detect line terminator format and enable parsing.

Thanks!

**Comment by jbax** [comment]
Thank you. This will be introduced in version 1.4.0 - just give us a couple of days.

**Comment by jbax** [comment]
Done. We added the [lineSeparatorDetection](http://docs.univocity.com/parsers/1.4.0/com/univocity/parsers/common/CommonParserSettings.html#setLineSeparatorDetectionEnabled(boolean)) flag to the [CommonParserSettings](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/CommonParserSettings.java) class in version 1.4.0

Direct download link (if you can't get the artifact via maven yet - it's been just released)
http://oss.sonatype.org/content/repositories/releases/com/univocity/univocity-parsers/1.4.0/univocity-parsers-1.4.0.jar
