### ISSUE TITLE
Examples don't work out of the box

### ISSUE THREAD

**Issue by analytically** [uniVocity/univocity-parsers#102]
`parser.beginParsing(getReader("/examples/example.csv"));` -> getReader?

**Comment by jbax** [comment]
From the tutorial (and code)


All parsers work with an instance of java.io.Reader, so you will see calls such as getReader("/examples/example.csv") everywhere. This is just a helper method we use to build the examples (source code here):

```

    public Reader getReader(String relativePath) {
        ...
        return new InputStreamReader(this.getClass().getResourceAsStream(relativePath), "UTF-8");
        ...
    }

```
So let's get started!
