### ISSUE TITLE
Parser is skipping the empty lines

### ISSUE THREAD

**Issue by mohammadshahidkhan** [uniVocity/univocity-parsers#104]
eid,ename,sal,presal,comm,deptno,Desc
17

18,,,,,,NullValue_check

while reading the line betweem 2nd and 4th row is skipped

**Comment by mohammadshahidkhan** [comment]
I think its univocity parser behaviour, are is there is any way to avoid skipping the same.
Use case:
Like hive considers the empty row between two rows as valid row and loads the same in the table.
Can we add a flag to avoid skipping the same.

**Comment by jbax** [comment]
This should solve your problem:

```parserSettings.setSkipEmptyLines(false);```

Thank you for using our parsers!

**Comment by mohammadshahidkhan** [comment]
Thank you for your support :)
