### ISSUE TITLE
Skipping CSV footer

### ISSUE THREAD

**Issue by exigow** [uniVocity/univocity-parsers#107]
Hello,

I have a CSV file with some footer consisting of several lines. To deal with headers (not footers) I can skip a constant number of lines using the setNumberOfRowsToSkip method.

Currently, I have to cut this footer manually before parsing.

Is it possible to add a similar solution like setNumberOfRows**FromBottom**ToSkip when setting up the parser configuration?

**Comment by jbax** [comment]
The parser reads all content from start to finish, and as it works internally with an instance of `java.io.Reader` there's not much we can do to ignore rows at the end. 

However, you can probably build your own `RowProcessor` to validate the content of each parsed row and discard the ones you are not interested in. For example, if you are parsing rows into beans, but need to ignore some rows, do this:

```
new RowProcessor() {

       private BeanListProcessor<SomeType> myActualProcessor = new BeanListProcessor<>(SomeType.class);

        @Override
        public void processStarted(ParsingContext context) {
            myActualProcessor.processStarted(context);
        }

        @Override
        public void rowProcessed(String[] row, ParsingContext context) {
            if (isValid(row)) {
                 myActualProcessor.rowProcessed(row, context);
            }
            //else skip row
           //and stop the parsing process  
           context.stop();
        }

        @Override
        public void processEnded(ParsingContext context) {
                myActualProcessor.processEnded(context);
        }
    };
```
