### ISSUE TITLE
Trailing comman in headers causes NPE

### ISSUE THREAD

**Issue by oliverhenlich** [uniVocity/univocity-parsers#109]
Hi,

We've just stumbled on an issue where a trailing comma at the end of the headers causes a NPE when doing an operation like `metaData.containsColumn("col1")`.

Please see the attached junit test illustrating the problem.

Cheers
Oliver

**Comment by oliverhenlich** [comment]
Here is the test.
[univocitytest.zip](https://github.com/uniVocity/univocity-parsers/files/394973/univocitytest.zip)

**Comment by anthony-bruno** [comment]
Fixed the problem, SNAPSHOT 2.2.1 has been updated with the fix. Thank you for your contribution.

**Comment by oliverhenlich** [comment]
Great! Thanks.
