### ISSUE TITLE
Possibility to avoid conversion of the "\u0000" string to null char

### ISSUE THREAD

**Issue by PawelPacholek** [uniVocity/univocity-parsers#110]
I have recently tried to use univocity parser to parse a csv, in which the String "\u0000" appears several times as a sub-string in some fields. The parser converts every occurrence of this string to the null char and I would like to switch it off to have field values unchanged. I have not found such an option in CsvFormat class. Could You add such an option? I mean an option that would allow to appropriately modify the behaviour of the "\" char in this case - to be treated as an ordinary char.

**Comment by jbax** [comment]
The parser is handling the `\u0000` correctly. This is not a string and it represents a single character instead of 6, and it IS the null character, meaning `'\0'` == `'\u0000'`.


Try running this test case:

	assertEquals('\0', '\u0000');
	assertEquals("a\0b", "a\u0000b");

        CsvParser csvParser = new CsvParser(new CsvParserSettings());

        String[] values = csvParser.parseLine("ab\u0000cd,e\u0000f");
        assertEquals(values[0], "ab\u0000cd");
        assertEquals(values[1], "e\u0000f");
        
        //if you want to "see" 6 characters then the forward slash must be escaped on the string literal
        values = csvParser.parseLine("ab\\u0000cd,e\\u0000f");
        assertEquals(values[0], "ab\\u0000cd");
        assertEquals(values[1], "e\\u0000f");

Hope this helps.
