### ISSUE TITLE
Add default converter for a class?

### ISSUE THREAD

**Issue by mlvn23** [uniVocity/univocity-parsers#114]
Is it possible to register a default conversion for a given Class[T]? I'm looking to reduce / eliminate the @Convert(conversionClass = classOf[Converter]) annotations every time I use the same type. Thanks.

**Comment by jbax** [comment]
You can use meta-annotations. For example, create your own annotation that uses the configuration used everywhere for a given field:

```
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Target(value = { ElementType.FIELD, ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@BooleanString(trueStrings = {"Y", "yes", "true"}, falseStrings = {"N", "no", "false"})
public @interface MyFantasticBoolean {
}
```

Now you can annotated your classes' fields with `@MyFantasticBoolean`.

Hope it helps!

**Comment by mlvn23** [comment]
Thanks for the tip!
