### ISSUE TITLE
Try to read headers and row use Read all rows of a CSV (the powerful version) method i got empty header and rows

### ISSUE THREAD

**Issue by winkumar** [uniVocity/univocity-parsers#117]
I try to to read csv file header and rows use Read all rows of a CSV (the powerful version) method.    
String[] headers = rowProcessor.getHeaders();
List<String[]> rows = rowProcessor.getRows();

The program generate csv template file can able to read header and rows , if i remove any rows i not get headers and rows.

**Comment by jbax** [comment]
Can you please provide a test case? I'm not sure I understand what the problem is.
Thank you!

**Comment by winkumar** [comment]
thanks @jbax 
i have two two different type of test case,
case 1:
i can export data from server user can change their needed to upload server this test execute successfully.
case 2:
user can create csv template fill data to upload server this case i can't able to read user entered data. but in csv file data is their. getHeaders() and getRows() method return {} and [] .  both are empty what is problem this case.

**Comment by jbax** [comment]
Sorry if I wasn't clear, be test case I meant an actual code snippet that reproduces the issue you are having.

Have you tried `settings.setHeaderExtractionEnabled(true);`? If that doesn't work can you please provide a code snippet + sample input I can use to reproduce the problem you're having?

Cheers!

**Comment by winkumar** [comment]
i have attached my input csv file. file read use following  method " **new InputStreamReader(new FileInputStream(relativePath), "UTF-16");**"
[test-csv.txt](https://github.com/uniVocity/univocity-parsers/files/477301/test-csv.txt)

**Comment by winkumar** [comment]
@jbax thanks, my problem is not with csv parser tool . it is based on streaming input.
