### ISSUE TITLE
Different behaviour between OSX Numbers csv file and MS Excel csv file

### ISSUE THREAD

**Issue by thegamblerrises** [uniVocity/univocity-parsers#118]
We are using jersey for the file uploading feature. Client uploads csv file, which we parse and save in DB. Problem is (so far observed), if they upload csv file , saved in OSX Numbers, I can parse it as it is. But when they try with Excel, it cannot decide the end of line and merges all into one, and saves all data in one row.

```
    CsvParserSettings settings = new CsvParserSettings();
	settings.getFormat().setLineSeparator(NEW_LINE);
	settings.setMaxCharsPerColumn(Configurations.MAX_ALLOWED_CHARACTERS_IN_A_CSV_COLUMN);
	settings.detectFormatAutomatically();
    CsvParser parser = new CsvParser(settings);

	List<String[]> allRows = parser.parseAll(new InputStreamReader(uploadedInputStream, CHARSET_UTF_8));

```

**Comment by jbax** [comment]
This is not a problem with the parser. Excel accepts only `/r/n` as the line separator so make sure you always write with `/r/n` as the line ending. If you don't have control over how users write their files, then you'd need to parse their files and write the values using the `/r/n` delimiter.

**Comment by thegamblerrises** [comment]
How would I change that? I mean how would I know that it's end of input as I don't know which file is coming (mac or excel)?

**Comment by jbax** [comment]
Parse the input files with this:

    CsvParserSettings parserSettings = new CsvParserSettings();
    parserSettings.setMaxCharsPerColumn(Configurations.MAX_ALLOWED_CHARACTERS_IN_A_CSV_COLUMN);
    // detect which line ending is being used.
    parserSettings.setLineSeparatorDetectionEnabled(true);
     // or to detect delimiters, etc
     parserSettings.detectFormatAutomatically();

And write them using:

     CsvWriterSettings writerSettings = Csv.writeExcel();

There's a pre-built routine to parse then write, which you could try:
    
    CsvRoutines csvRoutines = new CsvRoutines(parserSettings, writerSettings);
    csvRoutines.parseAndWrite(new InputStreamReader(uploadedInputStream, CHARSET_UTF_8), new FileWriter(new File("/path/to/final.csv")));

Hope this helps
