### ISSUE TITLE
Is there a simple way to get row count?

### ISSUE THREAD

**Issue by jearton** [uniVocity/univocity-parsers#119]
Using this way, I got the row count

```
String csv = "str of csv format"
CsvParser csvParser = new CsvParser(Csv.parseExcel());
int total = csvParser.parseAll(new StringReader(csv)).size();
System.out.println(total);
```

I think it's better to expose one simple api to get row count.

**Comment by jbax** [comment]
That's probably the slowest approach to get the row count as it generates rows and adds them to a list. Check [this example](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/examples/samples/CsvDimensionExample.java) to get the dimensions of a file for a faster approach.

I'll have this added as a routine available from [CsvRoutines](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/csv/CsvRoutines.java) for version 2.3.0

Thank you for using our parsers!

**Comment by jearton** [comment]
Thank you for detail explanation!

**Comment by jbax** [comment]
Done, just call `new CsvRoutines().getInputDimension(<File>)` and you'll get the row count and column count.

**Comment by jbax** [comment]
version 2.3.0-SNAPSHOT released to include this feature.
