### ISSUE TITLE
Can "@Replace" be used on the Class?

### ISSUE THREAD

**Issue by jearton** [uniVocity/univocity-parsers#120]
I want to replace all for input, like this:

```
public class Bill {

    @Replace(expression = "`", replacement = "")
    private String tradeTime;

    @Replace(expression = "`", replacement = "")
    private String appid;

    @Replace(expression = "`", replacement = "")
    private String muchId;

    @Replace(expression = "`", replacement = "")
    private String subMuchId;

   ...and so many fields...
}
```

I think it would be better to write like this:

```
@Replace(expression = "`", replacement = "")
public class Bill {
    private String tradeTime;
    private String appid;
    private String muchId;
    private String subMuchId;

   ...and so many fields...
}
```

**Comment by jbax** [comment]
Not yet, will be supported on version 2.3.0

**Comment by jbax** [comment]
Implemented a bit differently, with the improved support for meta-annotations introduced in [this commit](https://github.com/uniVocity/univocity-parsers/commit/74d7dbb0323bc91ad40eafb121280b590dc2abc3).

You can now define meta-annotations that allow modifying the properties of the annotations that compose it, using the [@Copy](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/Copy.java) annotation, check the javadoc shows a good example.
