### ISSUE TITLE
Regression from v2.2.1 to v2.2.2

### ISSUE THREAD

**Issue by manish-in-java** [uniVocity/univocity-parsers#121]
[121.zip](https://github.com/uniVocity/univocity-parsers/files/487123/121.zip)
Consider the following class hierarchy:

    abstract class Parent {
      @Parsed(field = "Code")
      private String code;
    }

    class Child extends Parent {
      @Parsed(field = "Name")
      private String name;
      @Parsed(field = "Description")
      private String description;
    }

and the following file (shown formatted for easier understanding):

    +------+-------------+
    | Name | Description |
    +------+-------------+
    | A123 | Category 1  |
    | B456 | Category 2  |
    +------+-------------+

This file gets parsed correctly with v2.2.1 (even though it does not contain a `Code` column. However, it fails with v2.2.2. A sample project is attached. Run test with v2.2.1 as `mvn clean test -P"v2.2.1"` and with v2.2.2 as `mvn clean test -P"v2.2.2"`.
[121.zip](https://github.com/uniVocity/univocity-parsers/files/487123/121.zip)

**Comment by jbax** [comment]
Thank you so much for reporting this error and providing a test case. This has been fixed now and a 2.2.3-SNAPSHOT build has been released with the correction.
