### ISSUE TITLE
Question on how to get origin CSV List<row> data.

### ISSUE THREAD

**Issue by duxy2002** [uniVocity/univocity-parsers#127]
I am using BeanListProcessor and RowProcessorErrorHandler.
1. by using BeanListProcessor I can get valid bean which's data is coverted.
2. by using RowProcessorErrorHandler I can get invalid datas which can't be coverted base on @annotation.
My question is how can I get the origin datas whatever they are valid or invalid?

**Comment by duxy2002** [comment]
I want to show the whole data of CSV file in the HTML table and want to color the invalid rows. so open the question would you please help me?

**Comment by jbax** [comment]
You can override the `public T createBean(String[] row, Context context) {` method to get the original input row. Just don't forget to call `super.createBean(row, context);` from within your implementation.

In regards to displaying rows in HTML, sorry but I can't help you here as this is a general programming question and not related to the library.
