### ISSUE TITLE
null at the end of the record

### ISSUE THREAD

**Issue by suyogparlikar** [uniVocity/univocity-parsers#128]
for fixedwidth paser if i make setSkipTrailingCharsUntilNewline=true 
i am getting the null value at the end of the line.

please find the below example for more details

sample file - 

YearMake_Model___________________________________Description_____________________________Price___   123456_78
1997Ford_E350____________________________________ac, abs, moon___________________________3000.00_   123456789
1997Ford_E350____________________________________ac, abs, moon___________________________3000.00_    23455889

output - 
Year|Make|Model|Description|Price|null
1997|Ford|E350|ac, abs, moon|3000.00|null
1997|Ford|E350|ac, abs, moon|3000.00|null

**Comment by jbax** [comment]
Can you provide the code you are using to parse this input? Thanks!

**Comment by suyogparlikar** [comment]
FixedWidthFieldLengths lengths = new FixedWidthFieldLengths(4, 5, 40,40,8);
		FixedWidthParserSettings settings = new FixedWidthParserSettings(
				lengths);
		settings.getFormat().setPadding('_');
		settings.getFormat().setLineSeparator("\n");
		settings.setHeaderExtractionEnabled(false);
		settings.setMaxColumns(6);
		settings.setSkipTrailingCharsUntilNewline(true);
		FixedWidthParser parser = new FixedWidthParser(settings);

		List<String[]> rows = parser
				.parseAll(new File("test"));

**Comment by jbax** [comment]
Fixed, I've released a 2.3.0-SNAPSHOT build to include this correction. Thanks for using our parsers!

**Comment by suyogparlikar** [comment]
thanks for the support

@jbax code is working as expected on windows , but on linux i am getting the above issue.

**Comment by jbax** [comment]
Is the line separator correctly configured in both platforms? Does it work if you run with `settings.setLineSeparatorDetectionEnabled(true)`? If nothing works, can you please attach the file (or a sample) so I can have a look? Thanks!

**Comment by suyogparlikar** [comment]
i have tried with settings.setLineSeparatorDetectionEnabled(true) but no luck.

here is the sample file - 

YearMake_Model___________________________________Description_____________________________Price___   123456_78
1997Ford_E350____________________________________ac, abs, moon___________________________3000.00_   123456789
1997Ford_E350____________________________________ac, abs, moon___________________________3000.00_    23455889

Actually i am using this library inside my spark code.

output is - 

Year^AMake^AModel^ADescription^APrice^Anull
1997^AFord^AE350^Aac, abs, moon^A3000.00^Anull
1997^AFord^AE350^Aac, abs, moon^A3000.00^Anull

**Comment by jbax** [comment]
I'm unable to reproduce. Can you verify the dependency has been updated? If you could attach the zipped file I'd be able to ensure everything is exactly the same as you have in your environment. Copying the text from the message messes up with line endings and whatnot. Thanks!

**Comment by suyogparlikar** [comment]
i am running this with older code i.e 2.2.3 , do want me to test this with updated code?

**Comment by jbax** [comment]
Yes please, otherwise you won't be able to know if the problem was resolved by the fix I applied earlier.

**Comment by suyogparlikar** [comment]
[test.zip](https://github.com/uniVocity/univocity-parsers/files/630748/test.zip)

attached the sample file for your reference.

**Comment by suyogparlikar** [comment]
how can i get the fix , can you provide the repo path

**Comment by jbax** [comment]
Here's the link:

https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/2.3.0-SNAPSHOT/univocity-parsers-2.3.0-20161205.073520-6.jar

Thanks for attaching the file. Testing now

**Comment by jbax** [comment]
I tested with your file and everything works as expected.

**Comment by suyogparlikar** [comment]
yup with new code its working just fine.
thanks for all your help and support.

can i have maven repo link for the same.

**Comment by jbax** [comment]
Just add this to your pom.xml to enable SNAPHOST builds:

    <repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

Then net the update the version of univocity-parsers to `2.3.0-SNAPSHOT`.

Cheers!
