### ISSUE TITLE
FixedWidthFields is there a way to establish the length via annotation

### ISSUE THREAD

**Issue by mallim** [uniVocity/univocity-parsers#129]
Hi

Currently we could establish the column ordering via:

@Parsed(index=1)

Is there a way to establish the max length at the same time via annotation?

e.g. @Parsed(index=1,length=8)

**Comment by jbax** [comment]
Thanks for the suggestion. We will create an annotation to configure fixed-width field properties: length, alignment & padding.

**Comment by jbax** [comment]
Done, you can now use `@FixedWidth` on your fields to configure everything. I've released a 2.3.0-SNAPSHOT build to include this feature.

Thanks again for the suggestion!
