### ISSUE TITLE
setColumnReorderingEnabled(false) not working when parsing single line

### ISSUE THREAD

**Issue by Nath5** [uniVocity/univocity-parsers#131]
I am trying to parse an individual line while preserving the line structure without actually returning all the values.

> String test2 = "1,2,3,4,5";
CsvParserSettings settings = new CsvParserSettings();
settings.getFormat().setDelimiter(',');
settings.selectIndexes(0,3);
settings.setColumnReorderingEnabled(false);
CsvParser parse = new CsvParser(settings);
String[] strings = parse.parseLine(test2);
System.out.println(Arrays.toString(strings));

Outputs:
[1, 2, 3, 4, 5]

I would expect it to output:
[1, null, null, 4, null]

Am I doing something wrong?

Thanks,
Nathan

**Comment by jbax** [comment]
Thanks for reporting this bug, we'll get it fixed soon.

As a workaround (not ideal, you shouldn't have to do this) you can define headers and then it will produce the expected output:

    settings.setHeaders(test2.split(","));

Thanks again!

**Comment by jbax** [comment]
Fixed. Also released a 2.3.1-SNAPSHOT build to include this adjustment if you want to test it.
