### ISSUE TITLE
index of Annotation@parsed

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#132]
Hi,

I've just upgraded from version 2.1.1 to 2.3.0.
This causes an usecase to fail which formerly succeeded well.

`BeanListProcessor<SomeBean> rowProcessor = new BeanListProcessor<SomeBean>(SomeBean.class);
CsvParserSettings parserSettings = new CsvParserSettings();
parserSettings.setProcessor(rowProcessor);
parserSettings.setHeaderExtractionEnabled(false);
parserSettings.setLineSeparatorDetectionEnabled(true);
parserSettings.getFormat().setComment('#');
parserSettings.getFormat().setDelimiter(';');
CsvParser parser = new CsvParser(parserSettings);
parser.parse(file)
`
where SomeBean
```public class SomeBean{
      
   public SomeBean() {
      super();
   }

   @Parsed(index = 1)
   private int orderNr;
   
   @Parsed(index = 3)
   private String pkNr;
   
   @Parsed(index = 6)
   private int status;
}
```
and parsing a file with this line:
`0948;960567;0621;06215005852549;20160115;;1;0.000000;;;18;072;03212248/8486748;0;;`

I get 
`java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 6` resulting in 
`com.univocity.parsers.common.DataProcessingException: Unexpected error processing input row [960567, 06215005852549, 1] using RowProcessor com.univocity.parsers.common.processor.BeanListProcessor.
Internal state when error was thrown: charIndex=0, row=[960567, 06215005852549, 1]`

It seems as parsing reads only the desired 3 columns and in the BeanListProcessor the index from the annotation is used which fails because there are some columns from the original file already filtered out => Index out of Bounds...!?
I think this is a bug, or have I missed something?

Cheers

**Comment by jbax** [comment]
Thanks for reporting this! Not only it is a bug, having users get such exceptions is also a shame. I've just fixed it and released a new 2.3.1-SNAPSHOT build to include the adjustment.

**Comment by blackfoxoh** [comment]
Thanks for the fix - I've tested it on my local machine, works well!
Is there a timeline planned for a 2.3.1 Release? (Just for my planning when we might proceed updating the lib - snapshot isn't an option outside developer-system)

**Comment by jbax** [comment]
Will be released Monday (maybe earlier). Thanks!
