### ISSUE TITLE
Specifying date format for resultset output

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#133]
Is there a way to specify the date format for date and/or datetime fields when doing resultset to csv output. The code I'm using to for csv generation is as follows

	CsvRoutines routines=new CsvRoutines();
	routines.write(rs, outputWriter);

**Comment by jbax** [comment]
You just need to use a `ObjectRowWriterProcessor`:

	ObjectRowWriterProcessor processor = new ObjectRowWriterProcessor();
	//assigns a "global" date format conversion for any timestamp that gets written.
	//you can also define field-specific conversions, which will override the default set here.
	processor.convertType(java.sql.Timestamp.class, Conversions.toDate("dd/MM/yyyy HH:mm"));
	
	CsvWriterSettings writerSettings = new CsvWriterSettings();
	writerSettings.setRowWriterProcessor(processor);
	
	CsvRoutines routines = new CsvRoutines(writerSettings);
	routines.write(rs, outputWriter);

Thanks for using our parsers!
