### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by chesterchen-gpsw** [uniVocity/univocity-parsers#134]
Just clone the project and try to build it. 

The build failed with following on master branch
 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.580 s
[INFO] Finished at: 2017-02-08T15:20:51-08:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project univocity-parsers: Could not resolve dependencies for project com.univocity:univocity-parsers:jar:2.3.2-SNAPSHOT: Failure to find com.univocity:univocity-output-tester:jar:1.1-SNAPSHOT in http://dse-artifactsrepo.prod.gopro-platform.com:8088/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]
[ERROR]

Then tried on release branch hotfix-2.0.1
...
1 error
3 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:46 min
[INFO] Finished at: 2017-02-08T15:23:59-08:00
[INFO] Final Memory: 24M/250M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project univocity-parsers: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /Users/chesterchen/projects/univocity-parsers/src/main/java/com/univocity/parsers/common/processor/OutputValueSwitch.java:215: warning: no @param for <T>
[ERROR] public <T> void addSwitchForType(Class<T> beanType, String... headersToUse) {
[ERROR] ^
[ERROR] /Users/chesterchen/projects/univocity-parsers/src/main/java/com/univocity/parsers/conversions/Conversions.java:77: warning: no @param for length
[ERROR] public static TrimConversion trim(int length) {
[ERROR] ^
[ERROR] /Users/chesterchen/projects/univocity-parsers/src/main/java/com/univocity/parsers/csv/CsvParserSettings.java:115: error: invalid use of @return
[ERROR] * @return a flag indicating that the parser should stop accumulating values when a field delimiter character is
[ERROR] ^
[ERROR] /Users/chesterchen/projects/univocity-parsers/src/main/java/com/univocity/parsers/csv/CsvParserSettings.java:118: warning: no @param for parseUnescapedQuotesUntilDelimiter
[ERROR] public void setParseUnescapedQuotesUntilDelimiter(boolean parseUnescapedQuotesUntilDelimiter) {
[ERROR] ^
[ERROR]
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/Users/chesterchen/projects/univocity-parsers/target/apidocs' dir.
[ERROR] -> [Help 1]

Not sure which stable build I should use to build

**Comment by chesterchen-gpsw** [comment]
Branch 1.5.6 build seems to be ok

**Comment by jbax** [comment]
Clone the univocity-output-tester project and build that one too. Version
2.3.2 will depend on version 1.1 of this testing library. Both are being
worked on right now.
