### ISSUE TITLE
FixedWidthRoutines write to ResultSet not respecting field lengths

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#135]
I have code similar to the one below. No matter what I put as the field lengths, the output is coming out the same. Is there something I'm missing.

		FixedWidthFields fields = new FixedWidthFields(8,10,15);

		FixedWidthWriterSettings writerSettings = new FixedWidthWriterSettings(fields);
		writerSettings.setHeaderWritingEnabled(true);
		
		FixedWidthRoutines routines = new FixedWidthRoutines(writerSettings);
		routines.write(rs, outputWriter);

**Comment by jbax** [comment]
Fixed and released a 2.3.2-SNAPSHOT version to include the fix.

As a workaround on your current version you can override the `adjustColumnLengths` method of the `FixedWidthRoutines` class:

	FixedWidthRoutines routines = new FixedWidthRoutines(writerSettings){
		@Override
		protected void adjustColumnLengths(String[] headers, int[] lengths) {
		}
	}

Sucks, but will work if you provide the field lengths.
