### ISSUE TITLE
ParsingContext with CsvRoutines

### ISSUE THREAD

**Issue by alvarorrol** [uniVocity/univocity-parsers#136]
Hi,
at the moment, there are [2 strategies](http://stackoverflow.com/questions/38051534/univocity-how-to-return-one-bean-per-row-using-iterator-style) to read iteratively the file instead of loading all beans in memory:

The first option (using setRowProcessor), allows to get and use ParsingContext. However the second one does not offer access to context. Is there any plan to add this option? 
From what I see in [AbstractRoutines.java](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/routine/AbstractRoutines.java) (method iterate, line ~660), a possible solution is to use a contextHolder similar to beanHolder and return it. The unique problem is the interface. I think there are 2 possible solutions
 - A wrapper (similar for Map.Entry<K, V>) for <V, ParsingContext>, create a iterateWithContext method to return <V, ParsingContext> when next() is used.
- Define a new interface with a method getParsingContext() to be implemented by the inner class (the iterator with the hasNext, next and remove). I think it is the best, just a minor change.

I have created a gist for this second: https://gist.github.com/alvarorrol/2f0a8ddf24f5721b02f881e089b59aa4

**Comment by jbax** [comment]
Done and I released a 2.3.2-SNAPSHOT build that includes this feature

**Comment by alvarorrol** [comment]
Thanks!
