### ISSUE TITLE
TSV multi-line fields without escapes

### ISSUE THREAD

**Issue by ctmay4** [uniVocity/univocity-parsers#137]
I have to deal with TSV files I don't produce and are not escape properly.  For example, let's say that there are supposed to be 3 fields per row.  I have:

```
value1	value2	value3
value1	value2a
value2b
value2c	value3
```

Since I know that there should be 3 values per row, I want to get two rows and the second value of the second row should be a single value with the newlines.

```
value2a
value2b
value2c
```

I'd tried but I can't seem to get the library to parse this correctly.    All the examples I saw assumed escaping but I don't have that option.  Are there settings to support this?  Thanks.

**Comment by jbax** [comment]
You won't have a setting that identifies this for you as the line ending is generally the end of the record, but it's very easy parse this row by row. If you get anything with less than 3 columns you just need to concatenate the last value of the previous row with the first value of the next.

**Comment by ctmay4** [comment]
Ok thanks.  I was hoping I could tell the parser there are a certain number of fields (or have it figure out from the header) and that logic would be built in.
