### ISSUE TITLE
is the solution support composite pojo classes..

### ISSUE THREAD

**Issue by newCoder5685** [uniVocity/univocity-parsers#138]
class Person{
@Parsed(index=1)
String name;
@Parsed(index=2)
String age;
Address address;
}

class Address{
@Parsed(index=3)
String street;
String city;
}
 BeanListProcessor<Person> rowProcessor = new BeanListProcessor<Person>(Person.class);
List<Person> beans = rowProcessor.getBeans();

Exception while mapping the csv columns to POJO class :
com.univocity.parsers.common.DataProcessingException: Unable to set value

**Comment by jbax** [comment]
Can you please provide a sample of the input you are trying to parse?

There's no support for nested objects, but you can use a `MultiBeanListProcessor` to get multiple objects parsed from a single row.

**Comment by jbax** [comment]
Fixed an `ArrayIndexOutOfBoundsException` raised when testing this.  Released a 2.3.2-SNAPSHOT build to include this adjustment.

**Comment by newCoder5685** [comment]
Thanks for the update. will test from MultiBeanListProcessor.
 Input is simple string data fetched from the csv columns but unable to map to the address class. 
name and age csv to java pojo mapping is working fine
Currently i am using below :
 BeanListProcessor (Person) rowProcessor = new BeanListProcessor(Person)(Person.class);
 List(Person) beans = rowProcessor.getBeans();

**Comment by jbax** [comment]
FIY, version 2.4.0 released just now supports a `@Nested` annotation that does the job for you.
