### ISSUE TITLE
Add support for nested object and collection values in annotations.

### ISSUE THREAD

**Issue by jbax** [uniVocity/univocity-parsers#139]
Allow users to collect multiple values of a row into a collection, e.g.:

```
person,phone1,phone2
Mary Jane, 041233122, 081133352
John Citizen, 1234333122, 12248750
```

Should be parsed into a `Person` class such as:

```
class Person {
    @Parsed
    String name;
    @Collection(fields={"phone1","phone2"}) //or something similar
    List<String> phones;
}
```

Or into some flat object structure such as:

```
class Person {
    @Parsed
    String name;
    @Nested //or something similar
    PhoneList;
}

class PhoneList{
    @Parsed
    String phone1
    @Parsed
    String phone2
}
```

Given that all values come from the same row, it should not be too tricky to make this work.

**Comment by jbax** [comment]
Implemented initial support for parsing and writing in this commit https://github.com/uniVocity/univocity-parsers/commit/4797de7ff20b9d8b9e38a83c93542958e7d75992.

Version 2.4.0-SNAPSHOT released to include this feature.

**Comment by jbax** [comment]
Not implementing support for collections of plain values for now as the code gets easily cluttered with annotations and a bit confusing. Any future suggestions on how to approach this cleanly will be considered and possibly implemented in a next version. Closing for now as support for nested objects is working fine.

**Comment by yonialaluf** [comment]
@jbax is there any new update on this issue.
I'm trying to do something similar, when i want to parse List/Map
I have a CSV **without** headers where i have the following schema:
"name, phone,....., key1, value1, key2, value2, ...., key25, value25"
meaning from position x i have a map of 25 key-value pairs (which some can be empty)
i wonder if i can have something like this 


```
class MyPair {
    @Parsed(index = 0)
    String key;
    @Parsed(index = 1)
    String value;
}

class MyRow {
    @Parsed(index = 0)
    String name;
    @Parsed(index = 1)
    String phone;    

    @Nested(index = x)
    List<MyPair> attributes;
}
```

**Comment by jbax** [comment]
Have a look at the @Nested annotation

**Comment by yonialaluf** [comment]
@jbax  unless i'm missing something @Nested will not help in this case as i dont want to create new Pojo with 25 pairs (meaning 50 fields) and put on each one its index.
For the example i put @nested on the attributes property but i want something like nested List``

```
@NestedList(fromIndex = <x>, toIndex=<x+50>)
 List<MyPair> attributes;
```
Or just specifying the number of elements
```
@NestedList(fromIndex = <x>, size=25)
 List<MyPair> attributes;
```

I understand this is not implemented, but is there any other way i can achieve this, even with configure a specific Processor, couldn't find any hook for this.

**Comment by jbax** [comment]
Yeah I realized that using a `HeaderTransformer` won't be of much help either. I'll have a look at the case you describe in a few days. Thank you for your input!
