### ISSUE TITLE
New line character in quoted string fails parsing

### ISSUE THREAD

**Issue by mj-jadhav** [uniVocity/univocity-parsers#141]
I have following line in csv file:
`a,b,c,"d`
`e"`
`f,g,h,i`
As you can see the first line, one value contains \n "d\ne", and currently this library is separating it out. I want that to be a single line. Do you have any suggestions?

**Comment by jbax** [comment]
Are you parsing this on Windows? If yes then it's because the default line separator is "\r\n". You can set it manually or configure the parser to detect this automatically.

**Comment by mj-jadhav** [comment]
@jbax No. I'm parsing it in linux. and current I've set line-separator to "\n". Should I change it to something else? or any other settings that I need to change to make this work?

**Comment by jbax** [comment]
that should just work. Is the character encoding correct? Can you attach the file so I can test this? 

This should work just fine. Try this:

```
    public static void main( String ... args){
		String input = "a,b,c,\"d\n" +
				"e\"\n" +
				"f,g,h,i";

		StringReader inputReader = new StringReader(input);

		CsvParser parser = new CsvParser(new CsvParserSettings());
		for(String[] row : parser.parseAll(inputReader)){
			System.out.println("Row = " + Arrays.toString(row));
		}
	}
```

This will print:

```
Row = [a, b, c, d
e]
Row = [f, g, h, i]
```

**Comment by jbax** [comment]
Re-reading your question I think I got what you expect. You want to get this:

```
Row = [a, b, c, d e]
Row = [f, g, h, i]
```

For that, use the following:

```
settings.getFormat().setNormalizedNewline(' ');
```

You can also use `\0` instead of whitespace, i.e. `' '` to get 

```
Row = [a, b, c, de]
Row = [f, g, h, i]
```

**Comment by mj-jadhav** [comment]
@jbax I've attached the file. 
[nlcsv.txt](https://github.com/uniVocity/univocity-parsers/files/813268/nlcsv.txt)

I want output to be as follows:
```
Row = [21AB25FB4CB0 1483114914885 1483114917563 football 20131105232448936 ios F 4.8] 
Row = [73f95e0f64f7 1464402309982 1464402310313 ad 0eef1e0ae283c7b support 600 "Virgin Mobile" AU] 
```
I've set following settings:
```
       CsvParserSettings settings = new CsvParserSettings();
        settings.getFormat().setLineSeparator("\n");
        settings.getFormat().setDelimiter(",");
        settings.getFormat().setNormalizedNewline(' ');
```
But it is still not working.

**Comment by jbax** [comment]
On my mac, this code:

    public static void main( String ... args){

		File input = new File("/Users/jbax/Downloads/nlcsv.txt");

		CsvParserSettings settings = new CsvParserSettings();
		settings.getFormat().setNormalizedNewline(' ');
		settings.getFormat().setLineSeparator("\n");
		settings.getFormat().setDelimiter(',');

		CsvParser parser = new CsvParser(settings);
		for(String[] row : parser.parseAll(input, "UTF-8")){
			System.out.println("Row = " + Arrays.toString(row));
		}

	}


Produced:

```
Row = [21AB25FB4CB0, 1483114914885, 1483114917563, football, 20131105232448936, ios, F, 4.8, null]
Row = [73f95e0f64f7, 1464402309982, 1464402310313, ad, 0eef1e0ae283c7b, support, 600, Virgin Mobile, AU]
```

Which is what you expect. Do you mind trying this?

**Comment by mj-jadhav** [comment]
@jbax Found the issue. Actually I was using this library https://github.com/brianmhess/cassandra-loader to load data into cassandra using csv. And in that library they are using `(line = reader.readLine())` instead of `(row = parser.parseNext()) != null)` to iterate over a line, which is causing the issue. As readLine will read one line at a time even if you do `seNormalizedNewline(' ')`
 https://github.com/al3xandru/cassandra-loader/blob/parser/src/main/java/com/datastax/loader/CqlDelimLoadTask.java#L191

Will have to fix that code to use your settings correctly :(
Sorry for the misunderstanding!

**Comment by jbax** [comment]
Ouch, splitting lines outside of the parser itself not only breaks anything within quotes, it's also WAY slower (like 3-4 times slower) and generates twice the garbage.

I'm glad you found a solution. Cheers!
