### ISSUE TITLE
why univocity CsvParser reads "" as null not as empty string

### ISSUE THREAD

**Issue by mohammadshahidkhan** [uniVocity/univocity-parsers#144]

**Comment by jbax** [comment]
That's the default behaviour. You can use `setEmptyValue` (for quoted fields) and `setNullValue` (in unquoted fields) in the parser settings to configure what to return.

**Comment by mohammadshahidkhan** [comment]
Thanks @jbax for your help, its really helped to deal with the issue our system was facing.
