### ISSUE TITLE
Retrieve the tokens using routines.iterate

### ISSUE THREAD

**Issue by alvarorrol** [uniVocity/univocity-parsers#148]
I am trying to get the tokens of a parsed row using `routines.iterate`:

```   IterableResult<T, ParsingContext> iterator = routines.iterate(csvBeanClass(), csvContext.getReader());```

Using this iterator I can get the parsingContext and have access to some details of the parsing process, including the line parsed and the tokens (as described in ParserOutput.initializeColumnsToExtract(..)). However, only the tokens required are included when a header is included. For example, for a csv with 2 elements in the header and 3 elements in the rest of the rows, the array parsedValues excludes this third element. I know this is not formally a standard csv (wrong header, rows with extra items, ...), but it would be useful to include all the tokens. It seems it is considering only the columns found on the first non empty row.

I have thought about processing the returned line by myself, but it would an important add extra overhead (process twice each line) for long csv and probably it is a good option to offer all the tokens in the array parsedValues.

**Comment by jbax** [comment]
This can't be implemented in the parser as this is a very specific use case that would degrade the performance (values parsed would have to be stored for you to access them later).

My suggestion is to use a `RowProcessor` to capture all values parsed instead. Try overriding the `BeanProcessor` class:

```

    BeanProcessor<YourBean> processor = new BeanProcessor<YourBean>(YourBean.class) {
			@Override
			public YourBean createBean(String[] row, Context context) {
				//your tokens here
				System.out.println(Arrays.toString(row));
                                //your bean will come out of this:
				return super.createBean(row, context);
			}

			@Override
			public void beanProcessed(YourBean bean, ParsingContext context) {
				//your bean here
				System.out.println(bean);
			}
		};
```

This will also run faster than your current `routines.iterate` as it involves less copying.

Hope this helps.

**Comment by alvarorrol** [comment]
This BeanProcessor strategy is already implemented in AbstractRoutines (iterate(..), line ~660). But it does not include the rowProcessed or createBean. I have implemented my own version as you have mentioned.
I was asking because perhaps it is useful for more people to add a flag in `CsvParserSettings` to return the parsed tokens in every possible scenary. The flag should be false by default to avoid the overheading for those users who do not want the tokens.
