### ISSUE TITLE
Support auto detect of column seperator

### ISSUE THREAD

**Issue by Odelya** [uniVocity/univocity-parsers#15]
Please support auto detect of columns separator.

The result will also return the detected separator type

Thanks!

**Comment by jbax** [comment]
Feature introduced [in this commit](https://github.com/uniVocity/univocity-parsers/commit/79e23a71801ca1e83942888b6164a2a066f87db9). In addition to the column separator, the parser can also detect the quote and quote escape.

This is available for testing from the latest 1.6.0-SNAPSHOT version.

Thank you for using our parsers!
