### ISSUE TITLE
Ability to assign a prefix to the Nested annotation

### ISSUE THREAD

**Issue by NateAtBV** [uniVocity/univocity-parsers#159]
I have a situation where multiple nested objects of the exact same type are coming in a csv.  It would be nice if there was a way for me to annotate those fields to indicate which columns (plural!) are used for which nested objects.

A contrived example:

Car has 4 separate Wheel fields, one for frontLeft, frontRight, rearLeft, and rearRight.
Those fields are annotated as "@Nested"

Each Wheel has: 
brandName (String annotated @Parsed(field="brand") 
milesRemaining (integer annotated @Parsed(field="miles").

The incoming CSV has information on all 4 Wheels, but with different headings:
"frontLeftWheelBrand", "frontLeftWheelMiles", "frontRightWheelBrand", "frontRightWheelMiles","rearLeftWheelBrand","rearLeftWheelMiles","rearRightWheelBrand","rearRightWheelMiles".

So, right now, I don't see a way (without extra processing) for univocity to parse the columns and assign them each to the correct Wheel field in Car.

I think if I could give the @Nested Wheel fields in the Car class a prefix, like "frontLeftWheel", and the uniVocity-parser would append that to the front of the fields in the Wheel class when it parses the CSV columns, that would solve my problem.

**Comment by jbax** [comment]
Thanks for the suggestion, I'll look into it

**Comment by jbax** [comment]
I've added support for this through the newly introduced [HeaderTransformer](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/HeaderTransformer.java). This is meant to be provided in the `@Nested` annotation and allows you to modify your headers at will.

Here is a test case demonstrating how it works: https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_159.java

Thank you for the suggestion! I've released a 2.5.0-SNAPSHOT build to include this new API. I hope it works well for you.

Best regards
