### ISSUE TITLE
How we can use @Format for String and Integer

### ISSUE THREAD

**Issue by sjupally** [uniVocity/univocity-parsers#162]
Hi Team,
I want parse String or Integer for fixedwidth value, if value is not up to the specified width, i want append 0 for integer and space for string at left or right.
Is @format annotation is helpful, if yes how can we use. provide me some examples.

**Comment by jbax** [comment]
The [@FixedWidth](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/FixedWidth.java) annotation has everything you need.

**Comment by sjupally** [comment]
Thanks @jbax
