### ISSUE TITLE
ParsingContext.currentParsedContent returns null when input is single length string

### ISSUE THREAD

**Issue by HyukjinKwon** [uniVocity/univocity-parsers#165]
It looks `ParsingContext.currentParsedContent` returns `null` when input is single length string.

Minimal reproduction:

```java
import java.io.StringReader;

import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;

class Main {
  public static void main(String[] args) throws Exception {
    CsvParserSettings settings = new CsvParserSettings();
    CsvParser parser = new CsvParser(settings);

    parser.parse(new StringReader("a"));
    System.out.println(parser.getContext().currentParsedContent());

    parser.parse(new StringReader("aa"));
    System.out.println(parser.getContext().currentParsedContent());
  }
}
```

prints

```
null
aa
```

Parsed tokens look correct. I first thought this produced `null` as it already parsed the input correctly but it looks not and inconsistent.

**Comment by jbax** [comment]
Thank you for reporting this one! It's been fixed and I released a 2.5.0-SNAPSHOT build that includes the adjustment. 

Cheers!

**Comment by HyukjinKwon** [comment]
Thank you @jbax!!

**Comment by jbax** [comment]
@HyukjinKwon I've tested this more and fixed a few problems in the original solution. Released another 2.5.0-SNAPSHOT with a bullet-proof algorithm (test case here: https://github.com/uniVocity/univocity-parsers/blob/08b67c3017c765b75f4b72dfeae743427f0f0ca6/src/test/java/com/univocity/parsers/issues/github/Github_165.java)

**Comment by HyukjinKwon** [comment]
@jbax, I just tested it with the snapshot. It looks working fine. Thank you for your quick fix again.

**Comment by HyukjinKwon** [comment]
@jbax, I just tested it with the snapshot. It looks working fine. I will look forward the next release. Thank you for your quick fix again.

**Comment by HyukjinKwon** [comment]
@jbax, BTW, do you mind if I ask a question please? (probably, because I am not used to the version policy in this repository ... ). I was thinking of bumping up the version from `2.2.1` to `2.5.0` when it is released.

Does this library generally make sure the backward compatibility between minor version changes? Just wondering if it is okay to bump this up without other additional changes generally (of course except deprecation changes).

I will try to help answer some questions if there are related issues about this in the future once I get to know this ...

**Comment by jbax** [comment]
Yes all changes are meant to be backward compatible.

**Comment by HyukjinKwon** [comment]
Thank you.
