### ISSUE TITLE
declaring start position and end position for fixed width

### ISSUE THREAD

**Issue by dcbhz** [uniVocity/univocity-parsers#166]
Hi this would be helpful and is not sure if implemented.

I have a input file:

Field1Field2Field3Field4

In my xml mappings, i have 
field name="field1" column-length="5"  (value:field1)
field name="field2" column-length="5"  (value:field2)
field name="field3" column-length="5"  (value:field3)

However 
lets say i want field 2 to be of text "Field1Field2"
am i able to declare something like this
<field name="field2" startPosition="0' endPosition="9" />

**Comment by jbax** [comment]
No sure where your XML mappings are coming from (there's nothing like it in this library), but it seems reasonably easy to implement support for position ranges in the `FixedWidthFields` class. Will be introduced in the upcoming 2.5.0 version. Thank you for the suggestion!

**Comment by jbax** [comment]
Done, you can now use "from" and "to" attributes in the `@FixedWidth` annotation and also use `FixedWidthFields.addField(int startPosition, int endPosition)` and overrides.

I released a 2.5.0-SNAPSHOT build that includes this feature. If you could try and let me know how it goes that would be great, thank you!
