### ISSUE TITLE
CsvParser does not throw exception for invalid CSV

### ISSUE THREAD

**Issue by bensullivan** [uniVocity/univocity-parsers#168]
Hi

The following code does not seem to throw an exception and I am not sure why:
`BeanListProcessor<CsvAdviceRecord> rowProcessor = new BeanListProcessor<>(CsvAdviceRecord.class);
        rowProcessor.setStrictHeaderValidationEnabled(true);
        CsvParserSettings parserSettings = new CsvParserSettings();
        parserSettings.setProcessor(rowProcessor);
        parserSettings.setHeaderExtractionEnabled(true);
        CsvParser parser = new CsvParser(parserSettings);
        try (StringReader reader = new StringReader("asdflkjnadklsjn")) {
            parser.parse(reader);
        }`
I was expecting parser.parse to error....

Am I doing something wrong?

Thanks

Ben

**Comment by jbax** [comment]
Can you please share your `CsvAdviceRecord` class?

**Comment by bensullivan** [comment]
Hi

Thanks for such a speedy reply.  Here it is:

```import com.univocity.parsers.annotations.Parsed;
import com.univocity.parsers.annotations.Trim;
import lombok.Getter;
import lombok.ToString;

import static spark.utils.StringUtils.isNotBlank;

@ToString
public final class CsvAdviceRecord {
    @Parsed @Trim @Getter private String questionText;
    @Parsed @Trim @Getter private String possibleAnswer;
    @Parsed @Trim @Getter private Double likelihood;
    @Parsed @Trim @Getter private String measure;
    @Parsed @Trim @Getter private Double measurementValue;
    @Parsed @Trim @Getter private Double measurementRangeStart;
    @Parsed @Trim @Getter private Double measurementRangeEnd;

    boolean isValid() {
        return isNotBlank(questionText) && (isValidOpinionatedResponse() ^ isValidMeasuredResponse());
    }

    boolean isValidOpinionatedResponse() {
        return isNotBlank(possibleAnswer) && likelihood != null;
    }

    boolean isValidMeasuredResponse() {
        return isNotBlank(measure) && (measurementValue != null ^ (measurementRangeStart != null
                && measurementRangeEnd != null));
    }
}```

Thanks

**Comment by jbax** [comment]
You don't see an error simply because your input doesn't have a line break.

The parser is reading the first row to collect headers. It gets to the end of the input without ever finding a new line, so it doesn't even have to try to populate values for an instance of the `CsvAdviceRecord` class. Put a `\n` in the middle of your gibberish String and you will get the exception you are looking for.
