### ISSUE TITLE
Option for AbstractRoutines.write(ResultSet rs, Writer output) that doesn't close the resultset or writer

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#172]
Is it possible to provide an overload for the **AbstractRoutines.write(ResultSet rs, Writer output)** method that doesn't close the resultset and writer when finished. Sometimes you may need to continue working with these objects after output is finished. I'm currently using **CsvRoutines** and **FixedWidthRoutines** and need to continue working with the rs and writer after the routines.write(rs, output).

**Comment by jbax** [comment]
Thank you for the suggestion. I've added a `keepResourcesOpen` property to the routines class. If you call `setkeepResourcesOpen(true)` it will not close the writer or the resultset after the routine executes.

This is available in the latest 2.5.0-SNAPSHOT build I just released.
Thank you for using our parsers!
