### ISSUE TITLE
Build process guide

### ISSUE THREAD

**Issue by PopescuStefanRadu** [uniVocity/univocity-parsers#173]
I don't use eclipse and figuring out how to run maven goals on that is quite tricky, everything seems to fail and working an unknown amount of hours to make it work is a pain.

Using intellij or plain maven has the tests failing, maybe due to some of the plugins you use?

Could you please make it so that the mvn processes run out of the box without using a specific IDE and setup?

**Comment by jbax** [comment]
I don't use eclipse either. The maven build just works for me in IntelliJ or the command line. 

Not that we build with JDK 6.
