### ISSUE TITLE
NullStringConversion converts only when reading

### ISSUE THREAD

**Issue by PopescuStefanRadu** [uniVocity/univocity-parsers#174]
When my string in my Java annotated bean has the value "" or whatever value I choose to be considered as equivalent to null I expect that when writing the CSV of that bean to get that string transformed into a null.

Of course the final result in the .csv should be the nullValue I choose for the CsvWriterSettings.

So for

```
public class SomeBean{
    @NullString(nulls = {""})
    @Parsed
    public String name = "";

    @Parsed
    public String street = "asd";
}
```
and
`csvWriterOptions.setNullValue("?");`

the result in .csv should look like:
```
name,street
?,asd
```
instead of 
```
name,street
,asd
```

Normally I'd just fork and do the change, but I can't get your build running using maven.

**Comment by jbax** [comment]
A `""` is an empty value. In CSV there's a distinction between what is null or empty. It should work if you use:

`csvWriterOptions.setEmptyValue("?");`
