### ISSUE TITLE
Set certain characters in input to return null on parse

### ISSUE THREAD

**Issue by a12jun** [uniVocity/univocity-parsers#175]
I'm refactoring an application that uses Apache Commons CSV Parser, to now use UniVocity's.  I'm very impressed with the performance increase!

A feature that Apache Commons had, which I can't seem to find easily in UniVocity, is [`.withNullString(String)`](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html#withNullString-java.lang.String-) - I could tell the parser to convert certain input strings to `null` when parsing.  In our application, we need to convert columns that just contain a hyphen to `null`.

Apologies if it's already there but I have looked around and can't find it anywhere obvious.

Thanks

**Comment by jbax** [comment]
You are looking a conversion that is available from an `ObjectRowProcessor`

Try this:
```
    // ObjectRowProcessor converts the parsed values and gives you the resulting row.
    ObjectRowProcessor rowProcessor = new ObjectRowProcessor() {
        @Override
        public void rowProcessed(Object[] row, ParsingContext context) {
            //here is the row. Let's just print it.
            println(out, Arrays.toString(row));
        }
    };
   
   //to convert some fields
    rowProcessor.convertFields(Conversions.toLowerCase(), Conversions.toNull("chevy", "-", "somethingelseidontwant")).set("Make", "Model", "Description");

   //or, for all fields
   rowProcessor.convertAll(/*same as above */);
```

Then configure the parser to use it:

```
	CsvParserSettings parserSettings = new CsvParserSettings();
	parserSettings.getFormat().setLineSeparator("\n");
	parserSettings.setProcessor(rowProcessor);
	parserSettings.setHeaderExtractionEnabled(true);

	CsvParser parser = new CsvParser(parserSettings);

	//the rowProcessor will be executed here.
	parser.parse(getReader("/examples/example.csv"));
```

Hope this helps. Thank you for using our parsers!
