### ISSUE TITLE
CSV File Parsing Issue

### ISSUE THREAD

**Issue by brsanthu** [uniVocity/univocity-parsers#177]
Been having issue with parsing this [file](https://drive.google.com/open?id=0B6Vdn5Wc0LIccXd5WUJOT1VRUDA)

File content is

```
"Action","ConnectionReceivedId","ConnectionSentId","CreatedById","CreatedDate","Field1","Field2","Field3","Field4","Field5","Field6","Field7","Id","IsDeleted","LastModifiedById","LastModifiedDate","LastReferencedDate","LastViewedDate","Field8","Field9","Name","OwnerId","Field10","Field11","Field12","Field13","SystemModstamp","Field14","Field15","Field16","Field17","Field18"
"Api1","","","00532000004sefcAAA","2016-11-16T18:47:46.000Z","","","","","Request:


Response:
{ }","","","a8E32000004yGChEAM","false","00532000004sefcAAA","2016-11-16T18:47:46.000Z","","","Request processing successful","Api","API-021382027","00532000004sefcAAA","","","","","2016-11-16T18:47:46.000Z","","Debug","Pass","",""
"Api2","","","00532000004sefcAAA","2016-11-16T18:48:13.000Z","","","","","Request:


Response:
{
  ""createdDate"" : ""2016-09-01T02:54:01.000Z""
}","","","a8E32000004yGCiEAM","false","00532000004sefcAAA","2016-11-16T18:48:13.000Z","","","Request processing successful","Api","API-021382123","00532000004sefcAAA","","","","","2016-11-16T18:48:13.000Z","","Debug","Pass","",""
```

It doesn't parse the second record completely. Instead of returning 32 fields, it returns 10 fields. I think the issue is in this part `}",` in line 13. It is treating that line as next record.

The settings I'm using are,

```
		CsvParserSettings settings = new CsvParserSettings();

		settings.getFormat().setComment('\0');
		settings.setMaxCharsPerColumn(1000000);
		settings.setMaxColumns(10000);

		settings.setQuoteDetectionEnabled(true);
		settings.setLineSeparatorDetectionEnabled(true);

		settings.setSkipEmptyLines(false);
		settings.setReadInputOnSeparateThread(true);

		return new CsvParser(settings);
```

**Comment by jbax** [comment]
Hi I just tested this and the parser returns the correct result: 10 fields. 

Pretty sure you are parsing the wrong file, there is no row with 32 columns in the one you attached.

Thank you for using our parsers!

**Comment by brsanthu** [comment]
Hi @jbax, thank you for taking time to respond.

The file contains 32 fields. They are `Action	ConnectionReceivedId	ConnectionSentId	CreatedById	CreatedDate	Field1	Field2	Field3	Field4	Field5	Field6	Field7	Id	IsDeleted	LastModifiedById	LastModifiedDate	LastReferencedDate	LastViewedDate	Field8	Field9	Name	OwnerId	Field10	Field11	Field12	Field13	SystemModstamp	Field14	Field15	Field16	Field17	Field18`.

**Comment by brsanthu** [comment]
Hi @jbax, can you please reopen the issue? I think there is an issue or may be misconfiguration, which is resulting in wrong results.

Your help is appreciated.

**Comment by jbax** [comment]
If you use a CSV parser to read JSON, you are going to have a really bad time. 

In CSV each line represents an individual record. The parser won't be able to join the values spanning over multiple lines to form a single record. If you insist in using a CSV parser for doing this, all you can do is to extract the rows one by one and join them when appropriate. It's not the job of the parser to reason about your input, that's up to you.

**Comment by brsanthu** [comment]
I understand. But here the json value is properly quoted. This is the second record value that is failing, however similar value in first is read fine.

```
"Request:


Response:
{
  ""createdDate"" : ""2016-09-01T02:54:01.000Z""
}"
```

**Comment by jbax** [comment]
Ah now I got it. It looks like a bug. Will investigate it further. Thank you for your patience!

**Comment by jbax** [comment]
Fixed. I released a new 2.5.2-SNAPSHOT build with the adjustment so you can test it.
Thank you for reporting the issue.

**Comment by brsanthu** [comment]
It fixed the issue. Thank you for your awesome quick turnaround.

**Comment by jbax** [comment]
Version 2.5.2 released. Thank you again!
