### ISSUE TITLE
Reset error states and keep parsing data from InputStream

### ISSUE THREAD

**Issue by maropu** [uniVocity/univocity-parsers#179]
Hi, I have some questions; previously, [I tried to catch exceptions and skip some corrupt records in Apache Spark](https://github.com/apache/spark/pull/18250#issuecomment-307977289) when parsing data from `InputStream`, but I failed to do so because the parser stopped whole parsing process when hitting exception. For example;
```
val input = s"""
   |"c0", "c1"           // Record 1
   |"c0", "c1","c2"      // Record 2
   |"c0", "c1"           // Record 3
 """.stripMargin

val csvOptions = new CsvParserSettings()

// Makes records having more than 3 columns corrupt
csvOptions.setMaxColumns(2)
val csvParser = new CsvParser(csvOptions)

// Parse data from `InputStream`
csvParser.beginParsing(new ByteArrayInputStream(input.getBytes("utf-8")))

// This works well and returns "c0, c1"
csvParser.parseNext()

try {
  // This throws an exception because `Record 2` has 3 columns and it is a corrupt record
  csvParser.parseNext()
} catch {
  case NonFatal(_) =>
}

// It returns `null` because parser have been already stopped.
csvParser.parseNext()
```
Then, Spark fails a whole job in this case. But, some Spark users wants to skip these corrupt records. IIUC, in `univocity-parser`, there is currently no way to reset error state and restart parsing data from next records (Record 3 in this example). Do we have any chance to implement this parsing recovery as a new feature, or any workaround? I appreciate any suggestion. Thanks in advance!

**Comment by jbax** [comment]
Sorry but there is zero chance of this being implemented internally. That limit is used only to "defend" you from running out of memory in case the parser is misconfigured and never find the end of the record - which will make the parser keep adding values to the same row until either the input or your memory is exhausted.

If you just want to ignore invalid records - in your case those with more than 2 columns - you can simply do this:

```
String[] row = csvParser.parseNext()
if(row.length > 2){
    //discard the row.
}

```

No need to hande that in a `try/catch` block.

Thank you for using our parsers!

**Comment by maropu** [comment]
ok, many thanks!
