### ISSUE TITLE
ConversionClass without String args

### ISSUE THREAD

**Issue by Fadelis** [uniVocity/univocity-parsers#181]
If field annotated with `Convert` annotation does not assign any args to it, I think it would be wise to use converter constructor without args argument.
It becomes quite redundant, if you want to have a simple converter, to write these constructors.
Ex:
```
public static class ToLocalTime extends ObjectConversion<LocalTime> {
    @Override
    public LocalTime fromString(final String input) {
      return processValue(input)
          .map(LocalTime::parse)
          .orElse(null);
    }
}
```

**Comment by jbax** [comment]
Thanks for the suggestion, I was thinking about doing it some time ago but never did it.

Keep in mind you can declare the constructor using `String ... args` and you are not required to pass any argument if you want to create an instance of your conversion class.

Thanks for the suggestion.

**Comment by jbax** [comment]
Done, I released another 2.5.3-SNAPSHOT build that allows you to create a conversion class without declaring `String[] args` constructor.

**Comment by Fadelis** [comment]
When do you plan to release `2.5.3` ?

**Comment by jbax** [comment]
5 minutes ago, good timing!
