### ISSUE TITLE
ParsingContext with CsvRoutines bug

### ISSUE THREAD

**Issue by alvarorrol** [uniVocity/univocity-parsers#184]
Hi, 
when using:
~~~~~
CsvRoutines routines = new CsvRoutines(parserSettings);
IterableResult<T, ParsingContext> iterator = routines.iterate(csvBeanClass(), csvContext.getReader());
for (T t : iterator)
   ...
~~~~~
the iterator.getContext() returns a context which contains information about the following line (not the current one parsed). So, for example, if we have a csv file with 3 rows, when we get the first row, the context contains the information about the second row. With the current implementation, it can be used calling manually the iter.hasNext(), iter.next() if you are able to look for the bug in the code.

The problem seems to have a quick fix. File AbstractRoutines.java, line 726. Before returning the bean, parser.parseNext() is called.  So when we return the bean, the context refers to the following row in the csv. Moving the parser.parseNext() to the hasNext() is a solution (with a flag to avoid side effect with repeated hasNext(), it should be idempotent).

Thanks for the parser, btw.

**Comment by jbax** [comment]
Fixed and release a 2.5.4-SNAPSHOT build that includes the adjustment.

Thank you for reporting the bug!
