### ISSUE TITLE
Investigate crash building with JDK 9

### ISSUE THREAD

**Issue by jbax** [uniVocity/univocity-parsers#189]
Running a simple `mvn clean install` with the JDK 9 results in the JVM crashing:

```
[jbax@linux-pc univocity-parsers]$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building univocity-parsers 2.5.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ univocity-parsers ---
[INFO] Deleting /home/jbax/dev/repository/univocity-parsers/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ univocity-parsers ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jbax/dev/repository/univocity-parsers/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ univocity-parsers ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 201 source files to /home/jbax/dev/repository/univocity-parsers/target/classes
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f46cf0802f0, pid=15241, tid=15282
#
# JRE version: Java(TM) SE Runtime Environment (9.0+181) (build 9+181)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9+181, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x9292f0]  JVMCIGlobals::check_jvmci_flags_are_consistent()+0x120
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e" (or dumping to /home/jbax/dev/repository/univocity-parsers/core.15241)
#
# An error report file with more information is saved as:
# /home/jbax/dev/repository/univocity-parsers/hs_err_pid15241.log
[thread 15281 also had an error]
#
# Compiler replay data is saved as:
# /home/jbax/dev/repository/univocity-parsers/replay_pid15241.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)

```

Attached the `hs_err` files:
[jdk_9_crash.zip](https://github.com/uniVocity/univocity-parsers/files/1324326/jdk_9_crash.zip)

It doesn't always fail with a crash. In this case the enforcer plugin errors out. Removing out the `maven-enforcer-plugin` in the `pom.xml` makes the crash happen 100% of the time.

**Comment by jbax** [comment]
Also, this happens using the 3.0 version of the  `maven-javadoc-plugin`

```
       <groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>3.0.0-M1</version>
```

**Comment by edvbld** [comment]
Hi @jbax,

this is openjdk_ehelin from java.reddit.com. Looking at the hs_err file, the stack trace is "wrong", a C2 Compiler Thread can't call JVMCIGlobals::check_jvmci_flags_are_consistent (and the value of the register RIP does not correspond to any instruction in the compiled version of that function). This makes me suspect that something could be wrong with your CPU, the CPU should not have jumped to this memory location.

Could you please send an email to hotspot-dev@openjdk.java.net and also CC rohitarulraj@gmail.com and Prakash.Raghavendra@amd.com (they both work at AMD). In the email, please describe your issue and include the link https://github.com/uniVocity/univocity-parsers/files/1324326/jdk_9_crash.zip (attachments will be stripped). Please also specify that you are running this on an AMD Ryzen 7 1700 CPU (you might want to include the exact description from /proc/cpuinfo).

I tried to reproduce this on Debian 8 on an Intel Intel Xeon CPU E5-2630 v2 with no luck, running `mvn clean install` with or without the `maven-enforcer-plugin` (and with version 3.0.0-M1 of the `maven-javadoc-plugin`) always works (both with a fastdebug and product build of JDK 9).

**Comment by jbax** [comment]
Thanks @edvbld, maybe try the same version of maven I'm using to make sure everything java-related is the same: 

```
[jbax@linux-pc ~]$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T03:59:23+10:30)
Maven home: /home/jbax/dev/apache-maven
Java version: 9, vendor: Oracle Corporation
Java home: /home/jbax/dev/jdk9
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "4.12.13-1-manjaro", arch: "amd64", family: "unix"
```

I use that version because that's the last one that is compatible with java 6 as univocity-parsers still supports it.

I'm sending an e-mail as you suggested with all the details.
Best regards,
Jeronimo

**Comment by jbax** [comment]
Hi @edvbld I tried again and the build succeeded after 4 tries. The 5th caused the JVM to crash. 

Attaching this other crash report, along with my `pom.xml` file.
[jdk_9_crash2.zip](https://github.com/uniVocity/univocity-parsers/files/1326484/jdk_9_crash2.zip)

**Comment by jbax** [comment]
```
[jbax@linux-pc univocity-parsers]$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD Ryzen 7 1700 Eight-Core Processor
Stepping:            1
CPU MHz:             1550.000
CPU max MHz:         3000.0000
CPU min MHz:         1550.0000
BogoMIPS:            6001.43
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx hw_pstate vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca

```

**Comment by MartyIX** [comment]
I don't really understand the problem so please consider the following as either helpful or useless but in both cases with good intentions in mind:

1) https://issues.apache.org/jira/projects/MCOMPILER?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page&status=all - Apache Maven Compiler 3.7.0 is first JDK 9 ready version

Another project of my interest uses Maven profiles to achive Java 9 compatibility: https://github.com/OpenHFT/Chronicle-Core/blob/master/pom.xml#L198 Maybe it may be of some use for you.

2) My experience with `maven-javadoc-plugin` 3.0.0-M1 is that it is still not working correctly with JDK 9, I would just disable javadoc plugin at the moment and I would wait for 3.0.0 release of (https://issues.apache.org/jira/projects/MJAVADOC/versions/12330875).

Regards,
Martin

**Comment by edvbld** [comment]
Hi @jbax, I saw your email on hotspot-dev@openjdk.java.net, lets continue the discussion there.

**Comment by rototor** [comment]
Hi @edvbld,

would you be so kind and add any info regarding this issue also here? I'm not subscribed to hotspot-dev, but also affected by this issue. 

I can't build my Java project on my Ryzen machine with Java 9 because I always get this crashes, but always at different place in the build process. Everything is fine with the Intel machines I have. Also building with Java 8 works fine. As my project is also deployed on some Ryzen machines this is a show stopper for me at the moment, i.e. I can not use Java 9 until it is either fixed in Java 9 or you/Oracle declares it a Ryzen CPU bug and I get a replacement for my CPU. As some early Ryzen CPUs where faulty I would not be surprised if this is a CPU bug. See also https://hothardware.com/news/amd-confirms-rare-ryzen-smt-bug-and-fix or https://www.phoronix.com/scan.php?page=news_item&px=Ryzen-Segv-Response

Thank you

FYI: 
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD Ryzen 7 1700X Eight-Core Processor
Stepping:              1
CPU MHz:               2200.000
CPU max MHz:           3400,0000
CPU min MHz:           2200,0000
BogoMIPS:              6786.87
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx hw_pstate vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca
```
The system is also not overclocked.

**Comment by rototor** [comment]
I just run the [https://github.com/suaefar/ryzen-test](kill-ryzen) test to verify that my processor is not faulty... But it is :( 

@jbax you could try that script on your machine. If it also crashes it we might just found another way to trigger that bug - namely using JDK9 to compile your projects...

```
Extract GCC sources
Download prerequisites
2017-10-06 10:27:39 URL: ftp://gcc.gnu.org/pub/gcc/infrastructure/gmp-6.1.0.tar.bz2 [2383840] -> "./gmp-6.1.0.tar.bz2" [1]
2017-10-06 10:27:45 URL: ftp://gcc.gnu.org/pub/gcc/infrastructure/mpfr-3.1.4.tar.bz2 [1279284] -> "./mpfr-3.1.4.tar.bz2" [1]
2017-10-06 10:27:49 URL: ftp://gcc.gnu.org/pub/gcc/infrastructure/mpc-1.0.3.tar.gz [669925] -> "./mpc-1.0.3.tar.gz" [1]
2017-10-06 10:27:56 URL: ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.16.1.tar.bz2 [1626446] -> "./isl-0.16.1.tar.bz2" [1]
gmp-6.1.0.tar.bz2: OK
mpfr-3.1.4.tar.bz2: OK
mpc-1.0.3.tar.gz: OK
isl-0.16.1.tar.bz2: OK
All prerequisites downloaded successfully.
cat /proc/cpuinfo | grep -i -E "(model name|microcode)"
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
model name	: AMD Ryzen 7 1700X Eight-Core Processor
microcode	: 0x8001129
sudo dmidecode -t memory | grep -i -E "(rank|speed|part)" | grep -v -i unknown
	Speed: 2133 MHz
	Part Number: CMK32GX4M2A2400C16
	Rank: 2
	Configured Clock Speed: 1067 MHz
	Speed: 2133 MHz
	Part Number: CMK32GX4M2A2400C16
	Rank: 2
	Configured Clock Speed: 1067 MHz
	Speed: 2133 MHz
	Part Number: CMK32GX4M2A2400C16
	Rank: 2
	Configured Clock Speed: 1067 MHz
	Speed: 2133 MHz
	Part Number: CMK32GX4M2A2400C16
	Rank: 2
	Configured Clock Speed: 1067 MHz
uname -a
Linux EPServer 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
cat /proc/sys/kernel/randomize_va_space
2
/ /tmp/ryzen-test
/tmp/ryzen-test
Using 16 parallel processes
Failed to search journal ACL: Operation not supported
No journal files were opened due to insufficient permissions.
[loop-0] Fri Oct 6 10:27:57 CEST 2017 start 0
[loop-1] Fri Oct 6 10:27:58 CEST 2017 start 0
[loop-2] Fri Oct 6 10:27:59 CEST 2017 start 0
[loop-3] Fri Oct 6 10:28:00 CEST 2017 start 0
[loop-4] Fri Oct 6 10:28:01 CEST 2017 start 0
[loop-5] Fri Oct 6 10:28:02 CEST 2017 start 0
[loop-6] Fri Oct 6 10:28:03 CEST 2017 start 0
[loop-7] Fri Oct 6 10:28:04 CEST 2017 start 0
[loop-8] Fri Oct 6 10:28:05 CEST 2017 start 0
[loop-9] Fri Oct 6 10:28:06 CEST 2017 start 0
[loop-10] Fri Oct 6 10:28:07 CEST 2017 start 0
[loop-11] Fri Oct 6 10:28:08 CEST 2017 start 0
[loop-12] Fri Oct 6 10:28:09 CEST 2017 start 0
[loop-13] Fri Oct 6 10:28:10 CEST 2017 start 0
[loop-14] Fri Oct 6 10:28:11 CEST 2017 start 0
[loop-15] Fri Oct 6 10:28:12 CEST 2017 start 0
[loop-14] Fri Oct 6 10:30:27 CEST 2017 build failed
[loop-14] TIME TO FAIL: 150 s
``` 

I'm trying to get a replacement now...

**Comment by jbax** [comment]
@rototor ryzen-test didn't cause me any trouble, yet the build issues still remain. Sounds like something wrong with the JDK itself

**Comment by edvbld** [comment]
All, this has _most likely_ nothing do to with the JDK (one can never be totally sure until the problem is solved). Again, the crash occurs in a C2 compiler thread. The C2 compiler thread is implemented using C++ and for Linux x86-64 compiled using gcc. This is _not_ code generated by `javac` or one of the JIT compilers. Think of it as a complicated C++ program.

Since the problem occurs when running C++ code, the problem is either with the C++ code, with the compiler (gcc in this case) or with the CPU (Intel or AMD for x86-64). Since an Intel CPU and the Ryzen CPU will run the exact same instructions, compiled with the exact same compiler from the same source, the program should crash on _both_ an Intel CPU and an AMD CPU if the problem was in the source code or with gcc. Since the program runs reliably on Intel CPUs but sometimes crashes on AMD Ryzen CPUs (with a very weird stack trace), the problem is _most likely_ in the AMD Ryzen CPU.

You don't have to be subscribed to hotspot-dev@openjdk.java.net to follow the thread, you can use the archive link here: http://mail.openjdk.java.net/pipermail/hotspot-dev/2017-September/028404.html

As you can see in the email thread, Rohit who works at AMD was able to reproduce issue. If you want an update, please reply to the thread on hotspot-dev@openjdk.java.net, you need the guys from the AMD to comment on this issue (I can't reproduce it on Intel and I don't have access to a Ryzen CPU).

**Comment by jbax** [comment]
Thanks for the clarification @edvbld , I'll close this thread.

**Comment by rototor** [comment]
@jbax FYI: I got my replacement CPU from AMD and Java 9 works without any flaws now... so I think it's strange that you can not reproduce crashes with kill-ryzen. In my case it really was a faulty CPU.

**Comment by jbax** [comment]
@rototor For the record I also got a new CPU from AMD and the crashes don't happen any longer.
