### ISSUE TITLE
[Bug] Incorrect length considered

### ISSUE THREAD

**Issue by anshooarora** [uniVocity/univocity-parsers#192]
Please see [here](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/fixed/FixedWidthFields.java#L311).

The length considered is invalid because consider the following example:

```
starting = 51, ending = 51
```

The above will result in `length = 0` because the length is being calculated as:

```
int length = endPosition - startPosition;
```

However, this is not correct.  a field that starts at 51 and is 1 character, will also end at 51, not 52.  So the correct calculation is:

```
int length = 1 + endPosition - startPosition;
```

**Comment by jbax** [comment]
Sorry, but I don't agree with you on this one. 

If a field starts at position 51 and has a length of 1, it will end at position 52, meaning that one character will be read when advancing from the starting position to the ending position. If a field starts and ends at the same position it means it's basically an empty field as nothing will be read from the transitioning from the start to end.

**Comment by anshooarora** [comment]
Sorry, but a field with 1 character will start and end on the same position. See the illustration below:

```
00138ADHJ
123456789
```

The 1st line above is the character string and the 2nd is the position.

The letter D for example, starts at position 7 and also ends there. In a fixed format, a length of 1 means the field ends where it starts.

In your explanation above, a field that starts at 51 and ends at 52 has a length of 2..  Above, look at position 4,5 -> it has 2 characters so length is also 2. 

I don't want to argue with you on this but this is how all our fixed files are created. We use the AS400 standard. 

Thanks for your library. I have added this fix and rebuild the jar for our use.

**Comment by jbax** [comment]
Thanks for your input and for using our parsers. Our fixed width parser doesn't follow any specific standard - that's where the confusion comes from. Changing how this works at this point is a problem because it's not a backward compatible change.
