### ISSUE TITLE
Trailing spaces in csv line leads to null instead of empty String

### ISSUE THREAD

**Issue by sormuras** [uniVocity/univocity-parsers#196]
See https://github.com/junit-team/junit5/issues/1100 for details.

We configure a `CsvParser` like:

```java
CsvParserSettings settings = new CsvParserSettings();
settings.getFormat().setDelimiter(delimiter);
settings.getFormat().setQuote('\'');
settings.getFormat().setQuoteEscape('\'');
settings.setEmptyValue("");
settings.setAutoConfigurationEnabled(false);
CsvParser csvParser = new CsvParser(settings);
...
```

and feeding line with multiple values and trailing spaces leads to `null` for the last column, instead of the expected empty value. From our test-suite, the following assertions fails:

```
Stream<Object[]> arguments = provideArguments(',', "1,''", "2, ''", "3,'' ", "4, '' ");

assertThat(arguments).containsExactly(new String[][] { { "1", "" }, { "2", "" }, { "3", null }, { "4", null } });
assertThat(arguments).containsExactly(new String[][] { { "1", "" }, { "2", "" }, { "3", "" }, { "4", "" } }); // failes
```

Using `settings.trimValues(true);` does not solve the issue.

Are we using the settings or the parser in a wrong way?

**Comment by sormuras** [comment]
Here is the class that feeds lines of Strings to the CsvParser:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java#L39

**Comment by jbax** [comment]
Thanks for reporting the bug! I've fixed and released a 2.5.8-SNAPSHOT build with the adjustment. Can you please confirm if it works?

Best regards

**Comment by sormuras** [comment]
Confirmed and thanks for the quick fix!

https://github.com/junit-team/junit5/commit/62055132ae226f7e99031d779926ed553a8ed543

**Comment by jbax** [comment]
Version 2.5.8 released. Thank you for using our parsers!
