### ISSUE TITLE
CsvParser does not properly detect delimiter (with setDelimiterDetectionEnabled)

### ISSUE THREAD

**Issue by axelborja** [uniVocity/univocity-parsers#198]
The delimiter detection does not work properly.

Here is a simple example of data that highlight the problem:
```
entity-id;code;color-code;display-name
12345;789;123-456;Display Name 1
12346;789;123-456;Display Name 2
12347;789;123-456;Display Name 3
```

Try to `parseAll` this file with `setDelimiterDetectionEnabled`, the detected delimiter is `-` instead of `;`.

Thanks in advance for your answer.

**Comment by jbax** [comment]
Thank you for reporting the bug! It's fixed and I released a 2.5.8-SNAPSHOT build that has the adjustment ready for you to test. Please let me know if it works for you.

Thank you for using our parsers!

**Comment by axelborja** [comment]
@jbax, first of all, thx for your reactivity.

Wonderful work, I tested it, it works.

Is it possible to release a non-SNAPSHOT version ?

**Comment by jbax** [comment]
Thanks! It will be available on Monday.

**Comment by axelborja** [comment]
Ok, then, is it possible to get a snapshot version from a maven or .sbt file ?

When I try, I get the following.
```
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.univocity#univocity-parsers;2.5.8-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by jbax** [comment]
If you use maven, you can get it by enabling the snapshot repository in your `pom.xml`:

```
<repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by axelborja** [comment]
Ok thanks a lot :+1:

**Comment by jbax** [comment]
Version 2.5.8 released. Thank you for using our parsers!

**Comment by axelborja** [comment]
@jbax Super, Thanks a lot. :+1:
