### ISSUE TITLE
Read a plaintext file

### ISSUE THREAD

**Issue by srijiths** [uniVocity/univocity-parsers#200]
Hi Team,

Is it possible to read a text file which contains non-csv format ( JSON/XML , line by line ) using univocity ? 
Does extending RowProcessor helps ?

Thank You,
Srijith

**Comment by jbax** [comment]
If the JSON/XML bit is inside a CSV field it should work just fine. If you are trying to parse JSON/XML then you should use a parser for this sort of format.
