### ISSUE TITLE
Delimiter Autodetect Broken in CSV files with Tabs

### ISSUE THREAD

**Issue by wnreynoldsWork** [uniVocity/univocity-parsers#202]
import java.io.StringReader;
import java.util.List;

import com.univocity.parsers.common.ParsingContext;
import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;

/**
 * Small class to demonstrate bug in univocity parser. In CSV file with embedded tabs, 
* delimiter autodetection always detects \t as delimiter.
* To run: 
* save this file as 'UnivocityTabBug.java'
* $ javac UnivocityTabBug.java
* $ java UnivocityTabBug

  */
public class UnivocityTabBug {

// taken from bean_test.csv in univocity repository.
    static final String input = "date,			amount,		quantity,	pending	,comments\n"
        + "10-oct-2001,	555.999,	1,			yEs		,?\n"
        + "2001-10-10,		,			?,			N		,\"  \"\" something \"\"  \"";

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        StringReader reader = new StringReader(input);
        CsvParserSettings settings = new CsvParserSettings();
        settings.setDelimiterDetectionEnabled(true);
        settings.setLineSeparatorDetectionEnabled(true);
        settings.setIgnoreLeadingWhitespaces(true);
        settings.setIgnoreTrailingWhitespaces(true);
        settings.setHeaderExtractionEnabled(true);
        settings.setCommentCollectionEnabled(true);
        CsvParser parser = new CsvParser(settings);

        List<String[]> rows = parser.parseAll(reader);

        ParsingContext context = parser.getContext();
        String headers[] = context.parsedHeaders();
        System.out.println("Delimiter Autodetect on:");
        System.out.println("detected delimiter = '" + parser.getDetectedFormat().getDelimiter() + "'");
        printParse(headers, rows);

        settings.setDelimiterDetectionEnabled(false);
        reader = new StringReader(input);
        parser = new CsvParser(settings);
        rows = parser.parseAll(reader);
        context = parser.getContext();
        headers = context.parsedHeaders();
        System.out.println("\n\nDelimiter Autodetect off:");
        System.out.println("delimiter = '" + parser.getDetectedFormat().getDelimiter() + "'");
        printParse(headers, rows);

    }

    static void printParse(String headers[], List<String[]> rows) {
        System.out.println("header:");
        for (String header : headers) {
            System.out.print("'" + header + "' ");
        }
        System.out.println();

        System.out.println("rows:");
        for (String row[] : rows) {
            for (String elem : row) {
                System.out.print("'" + elem + "' ");
            }
            System.out.println();
        }

    }

}

**Comment by wnreynoldsWork** [comment]
<dependency>
            <groupId>com.univocity</groupId>
            <artifactId>univocity-parsers</artifactId>
            <version>2.5.8</version>
            <type>jar</type>
        </dependency>

**Comment by jbax** [comment]
Thanks for your contribution, but this example is extremely unrealistic. The sample input is just too small to enable a reliable detection.

The heuristic discards the last line of the input. If your input does not contain a line ending in the last line then in this example just the first row will be considered. The tab will be chosen as the delimiter as it appears more frequently in the first row. There is no way to reliably detect the delimiter.

If the input contains a line ending in the last line, the first two rows will be considered. By sheer luck, the number of tabs in these first two rows is the same. Given that the number of commas and tabs is the same in all rows, the algorithm chooses the one that appears more frequently, and the tab will be selected again. If you add an extra tab in either row then the comma will be chosen.

I made an adjustment to not discard the last row when the input is small. It won't make this example work anyway, but improves the chances of getting the correct delimiter on very small inputs.

Thanks for using our parsers!
