### ISSUE TITLE
Are inner spaces supported in headers?

### ISSUE THREAD

**Issue by vmaldosan** [uniVocity/univocity-parsers#204]
Using v2.5.8, if any header has words separated by spaces, the CsvWriter won't be able to match it with the field. Normalization of header only trims it and set it to lower-case, shouldn't also remove any inner space?

**Comment by jbax** [comment]
I'm unable to reproduce this. Can you provide a unit test or code sample that highlights the particular issue you are having?

Thank you!

**Comment by vmaldosan** [comment]
Most likely I'm missing some settings, this is how I write the Java beans into CSV strings:
```
public static String writeToCsv(List<String> headers, List<String> fields, List<ExampleJavaBean> exampleJavaBeanList) {
        CsvWriterSettings settings = new CsvWriterSettings();
        settings.selectFields(fields.toArray(new String[0]));
        settings.setRowWriterProcessor(
                new BeanWriterProcessor<>(ExampleJavaBean.class));

        ByteArrayOutputStream csvResult = new ByteArrayOutputStream();
        Writer outputWriter = new OutputStreamWriter(csvResult);

        CsvRoutines csvRoutines = new CsvRoutines(settings);
       
        csvRoutines.writeAll(exampleJavaBeanList, ExampleJavaBean.class,
                outputWriter, headers.toArray(new String[headers.size()]));
```
_ExampleJavaBean_ has _@Parsed_ annotation in all its fields, without the _index_ option. My understanding was headers would be assigned to a field by order of appearance, but with my current settings it's trying to match each header with a field after being normalised.

**Comment by vmaldosan** [comment]
Ok, I figured out how to do it: using CsvWriter for the custom headers and not passing any header to csvRoutines.writeAll(...).
Thanks!

**Comment by vmaldosan** [comment]
Worth mentioning I also had to use settings.selectIndexes() and Java Reflection in order to make the list of fields to write configurable in run-time.
