### ISSUE TITLE
OOM on skip lines. AbstractCharInputReader.skipLines

### ISSUE THREAD

**Issue by leafgray** [uniVocity/univocity-parsers#205]
thanks for this greate library.

meet  OOM error on skip many lines.
reproduce steps:
1. generate a large  csv file (my test case: 2G, 5 million lines)
2. skip large numer rows
3. run with small -Xmx.  

workaroud:  use Parser.parseNext to skip....

test code:

`import com.univocity.parsers.common.Context;
import com.univocity.parsers.common.processor.core.Processor;
import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;
import java.io.File;
import java.util.Arrays;

public class Test {
    public static void main(String[] args) throws Exception {
        String fn = args[0];
        int rowsToSkip = 100000;
        if (args.length > 1) {
            rowsToSkip = Integer.parseInt(args[1]);
        }
        CsvParserSettings settings = new CsvParserSettings();
        final int batchSize = 10000;
        settings.setNumberOfRecordsToRead(batchSize);
        settings.setLineSeparatorDetectionEnabled(true);
        settings.setNumberOfRowsToSkip(rowsToSkip);
        settings.setNullValue("\\N");
        settings.setEmptyValue("");
        settings.getFormat().setQuoteEscape('\\');
        settings.getFormat().setDelimiter(',');
        settings.setHeaderExtractionEnabled(true);
        settings.setMaxCharsPerColumn(-1);

        CsvParser parser = new CsvParser(settings);
        parser.beginParsing(new File(fn));
        String[] record = parser.parseNext();
        while (record != null) {
            System.out.println(Arrays.asList(record) + ":" + parser.getContext().currentLine());
            System.out.println();
            record = parser.parseNext();
        }
    }
}`

**Comment by jbax** [comment]
Thank you for reporting the bug. It's been fixed and I released a 2.6.0-SNAPSHOT that includes the adjustment.

Thanks for using our parsers!

**Comment by jbax** [comment]
Released version 2.5.9 with this bugfix (and others)
