### ISSUE TITLE
Csv format detection enhancement

### ISSUE THREAD

**Issue by ludoo0d0a** [uniVocity/univocity-parsers#214]
I use the auto detection format. It works well, but with this dataset it fails.

```csv
1_car_name|2_truck_name|3_wheels
audi,q5,4
audi,q3,4
````

There are more _ than real delimiter |. So detector guesses _ is the delimiter. Logical, but wrong !

Is it possible to introduce a check on header and/or first date line (based on a setting )?
May be a result comparison between header line and first data line could help (delimiter count?) ?

**Comment by ludoo0d0a** [comment]
or a set of allowed delimiters ?
or a priority in characters used for delimiter ?

**Comment by jbax** [comment]
Thanks for the suggestion. I'll have a look on this for the next version. Keep in mind that the detection process is a heuristic that depends a lot on the input length. It is not suited for small test inputs like this - if you give it unrealistic data it's very likely you'll find a case where if fails.

Thank you for using our parsers!

**Comment by ludoo0d0a** [comment]
> detection process is a heuristic that depends a lot on the input length

you're right ! My real case is a big file. I give you only a test case.

**Comment by jbax** [comment]
Adding to the enhancements: also allow users to modify the delimiter/quote/line ending if needed before parsing.

**Comment by jbax** [comment]
Done and I released a 2.6.0-SHAPSHOT build to include the adjustment.

You can now provide a sequence of allowed characters for detection, e.g. `settings.detectFormatAutomatically( '-', '.');` 

Also, after calling  `beginParsing`, you can get the detected format  with `parser.getDetectedFormat()` and make adjustments to the format that was detected if you wish.

Then, call `parser.updateFormat(format);` to use your adjusted format to continue parsing.

Finally, you can proceed with the parser to get rows one by one or just call the new `List<String[]> rows = parser.parseAll();` (without args) to get all rows.

Thank you for using our parsers!
