### ISSUE TITLE
CSVWriter turn off quoting

### ISSUE THREAD

**Issue by gaborgsomogyi** [uniVocity/univocity-parsers#215]
As I see now it's possible to set '\u0000' as quote character both on read and write side. On read side it's ending up in skipping the quotes (feature turned off because it never finds such character). On the write side it just writes it out. Can we consider this special (end of string) character as no quoting on the write side as well?

**Comment by jbax** [comment]
The writer will only put quotes when absolutely required (i.e. the value has a delimiter, line ending, or another quote in it). If you don't want to output quotes in these cases the parser won't be able to read the data back properly. It makes no sense to `force` the CSV writer to not use quotes.

If you really want to do this you'd be better off just writing your data directly to an instance of `java.io.Writer` (FileWriter, OutputStreamWriter, StringWriter, etc)

**Comment by HyukjinKwon** [comment]
Hi @jbax, just a small followup question though, if there is a quick answer. In Apache Spark, I think we described a behaviour mistakenly - when setting `\u0000` [null character](https://en.wikipedia.org/wiki/Null_character) via `CsvFormat.setQuoteEscape`, the parser ignores quotes when loading. Given my tests and code reading, it does not seems so.

Do you mind if I ask a quick confirmation if possible please? I would like to disallow setting empty string in Spark actually (which internally sets `\u0000` to the property in Univocity internally).

**Comment by jbax** [comment]
@HyukjinKwon Actually the code will try to handle `\0` as the quote character. Basically the idea is to use a character that won't occur in the input - especially not around commas and line endings. Now that you asked it maybe `\uFFFF` is a better candidate (if it's part of the BOM marker it will have been used before parsing starts).

**Comment by HyukjinKwon** [comment]
@jbax, thanks so much. That helped me a lot to understand. Probably, documenting it properly within Spark could be a safe option for now.
