### ISSUE TITLE
setEmptyValue for missing cells.

### ISSUE THREAD

**Issue by gowravshekar** [uniVocity/univocity-parsers#217]
Value set in `setEmptyValue` isn't used for missing cells. Getting null. [Sample Code](https://gist.github.com/gowravshekar/f19170e52148e17f4b20e4ec4f829f3d)

**Comment by jbax** [comment]
You must use `setNullValue("")` for these. In CSV there are two "empty" representations:

- the empty or blank value (no data within quotes): `a,"",b`
- the null value (no data at all): `a,,b`

Just  add `setNullValue("")`  to your code and you will get the result you want.
Thank you for using our parsers!
