### ISSUE TITLE
Attach the raw string to the Record for debugging purposes

### ISSUE THREAD

**Issue by ben-manes** [uniVocity/univocity-parsers#218]
I have an integration with an AS/400 system, where CSV rows are pushed to our APIs for a real-time sync. This is their changed database rows for the table named by the request. We then digest this into our staging tables and periodically sync it with our models.

Sometimes we are seeing missing data, so we direct the request to dedicated log files (e.g. `logs/innovative/billing.log`). That way we can easily grep to see if the data was sent in the requests to determine who is responsible for resolving the issue. Currently I do this by using the `Record.toString()` in the named logger.

This seems to work fine, but I know the format isn't identical to the request. For example they send a pipe delimited request with empty columns whereas the log record might look like,
```
4202374, null, null, null, null, 0, 0.00, 0.00, null, null, null, null, null, null, null, null, null, null, null, null, 0.00, 0.00, 0.00, 0.00, 0.00, null, 0.00, 0.00, 0.00, 0.00, 0, null, 98021, null, null, null
```

The raw input is read as a stream into the processing logic. This is nice since we can use the same process for a historical import to bootstrap the integration. I could move the logging earlier and only on the incremental API, but it would be nicer to have a `Record.toRawString()` method instead.

**Comment by ben-manes** [comment]
I was able to get around this by using `BufferedReader.readLine()` and `parser.parseRecord(line)`. That works well enough, though I do like the idea of deferring to your library for all the parsing.

**Comment by jbax** [comment]
It's already implemented in class `ParsingContext` method `currentParsedContent`. It returns the content that was parsed to produce a row.

Simple example of how to use it:
```
CsvParser parser = new CsvParser(Csv.parseRfc4180());
for(Record record : parser.iterateRecords(new File("/lala"))){
    String originalContent = parser.getContext().currentParsedContent();
}
```

Essentially, if you concatenate the output of this method using a `StringBuilder` every time a row is parsed, your `StringBuilder` should contain the exact same content as your entire input. There's a test case [here](https://github.com/uniVocity/univocity-parsers/blob/ce8a5b565bd4e970543f5fc2f6cdabd0dfd09fbc/src/test/java/com/univocity/parsers/issues/github/Github_136.java) if it helps.

Thank you for using our parsers!

**Comment by ben-manes** [comment]
Thanks!
