### ISSUE TITLE
Stop parsing causes null pointer exception

### ISSUE THREAD

**Issue by VCubarP** [uniVocity/univocity-parsers#219]
Recently I have upgraded to latest version 2.5.9 and after that I am facing the below exception randomly. (Thrice in a week). Previously we haven't encountered such exceptions.

com.univocity.parsers.common.TextParsingException: java.lang.NullPointerException - null
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=true
	Ignore trailing whitespaces=true
	Input buffer size=1048576
	Input reading on separate thread=false
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=?
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:368)
	at com.univocity.parsers.common.AbstractParser.stopParsing(AbstractParser.java:431)

@jbax May require your input on this.

**Comment by jbax** [comment]
Thank you for reporting this one.

The line that blows up `AbstractParser.handleException(AbstractParser.java:368)` has this:

```
TextParsingException out = new TextParsingException(context, message, ex);
```

Looking at the code none of  `message` or `ex` can never be null. `context` is initialized when `beginParsing` is called. I looks like the error pops up if you create a parser instance, never use it and call `stopParsing`. I just created a very complex test case that reproduces the error:

```
	public void testStopParsingWithoutParsing() {
		CsvParser parser = new CsvParser(Csv.parseRfc4180());
		parser.stopParsing();
	}
```

I've fixed the error and released a 2.6.0-SNAPSHOT build which you can use already. If you want to stay on version 2.5.9 just change your code to make sure the parser actually parses something before `stopParsing` is called.

Thank you for using our parsers!

**Comment by VCubarP** [comment]
@jbax  Thanks for addressing the problem.

From where, I can get 2.6.0-SNAPSHOT artifact?

**Comment by jbax** [comment]
Here:
https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/2.6.0-SNAPSHOT/
