### ISSUE TITLE
Parsing irregular tsv files

### ISSUE THREAD

**Issue by zasbit** [uniVocity/univocity-parsers#223]
Hi,

I'm parsing a tsv file that is a little bit irregular. For example these 3 lines of the TSV file
`"ID"	"DATE"	"BRAND"	"HASH"	"DESCRIPTION"`
`"7bfb5166eb234913996c61f5af0c0409"	26-05-2017	BMW	"ce2773b0a0464d68bd8e64aa3bac135f"	"Some description text\nand nothing else"`
`"1d7e21e4f31c406898e30fe58fcd2107"	20-05-2017	Mercedez	"4f0de8a9bebb4f10af0ee01a8c52b4cc"	"Seller description\nIn good condition\nGood velocity\n	\nBuyer description:\nNo description\n"`
`	26-05-2017	Mazda	"6501505bb9e94764a672ef2cdb6a00ab"	"No description"`

Will output the following string arrays:
`["7bfb5166eb234913996c61f5af0c0409",26-05-2017,BMW,"ce2773b0a0464d68bd8e64aa3bac135f","Some description text\nand nothing else"]`
`["1d7e21e4f31c406898e30fe58fcd2107",20-05-2017,Mercedez,"4f0de8a9bebb4f10af0ee01a8c52b4cc","Seller description\nIn good condition\nGood velocity\n","\nBuyer description:\nNo description\n"]`
`[26-05-2017,Mazda,"6501505bb9e94764a672ef2cdb6a00ab","No description"]`

So the problem is, the first array (the right one) has size of 5, the second 6 and the last 4. What I was expected was the first is ok, the second the string would not be divided in two, and the last the first field (empty) would be considered:

`["7bfb5166eb234913996c61f5af0c0409",26-05-2017,BMW,"ce2773b0a0464d68bd8e64aa3bac135f","Some description text\nand nothing else"]`
`["1d7e21e4f31c406898e30fe58fcd2107",20-05-2017,Mercedez,"4f0de8a9bebb4f10af0ee01a8c52b4cc","Seller description\nIn good condition\nGood velocity\n\t\nBuyer description:\nNo description\n"]`
`[null,26-05-2017,Mazda,"6501505bb9e94764a672ef2cdb6a00ab","No description"]`

The code I'm using is:

`Collection<String[]> allRows = new ArrayList<>();
			TsvParserSettings settings = new TsvParserSettings();
			settings.setHeaderExtractionEnabled(true);
			settings.setSkipEmptyLines(true);
		
			// creates a TSV parser
			TsvParser parser = new TsvParser(settings);

			// parses all rows in one go.
			InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream(filename), "UTF-8");
			parser.beginParsing(inputStreamReader);
			String[] record = parser.parseNext();
			while (record != null) {
				allRows.add(record);
				record = parser.parseNext();
			}
			// allRows.addAll(parser.parseAll(inputStreamReader));
			
			return allRows;	`

How can I do this?

Thank you

**Comment by jbax** [comment]
You seem to be parsing a CSV input that happens to use the tab character as the delimiter. Just use the CSV parser for this.

The TSV parser has no special consideration for quotes - it's just a regular character without any other meaning or requirement for escaping.

I assume your line with `"Seller description\nIn good condition\nGood velocity\n \nBuyer description:\nNo description\n"` has a tab between `Good velocity\n` and `\nBuyer description`.

For this to be parsed as a single value in in TSV the line should have been written as `"Seller description\nIn good condition\nGood velocity\n\\t\nBuyer description:\nNo description\n"

When using the CSV parser, the quotes around each field will go away. If you want them just use this setting:

`csvParserSettings.keepQuotes(true);`

In addition, if you want to retain any escaped quote inside quotes values, use this:

`csvParserSettings.setKeepEscapeSequences(true);`

With both settings your input fields will be split at the delimiter and retain the original quote and escape sequences.

Hope this helps.

Thank you for using our parsers!
