### ISSUE TITLE
HeaderTransformer with multiple Nested levels

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#225]
I have classes like the following

```
public class User {
	
	@Parsed
	private String name;
	@Nested(headerTransformer = PrefixTransformer.class, args = "country1")
	private Country country1;
	@Nested(headerTransformer = PrefixTransformer.class, args = "country2")
	private Country country2;
	
	//getters and setters...
}

public class Country {
	
	@Parsed
	private String name;
	@Nested(headerTransformer = PrefixTransformer.class, args = "city")
	private City city;
	
	//getters and setters...
}

public class City {
	
	@Parsed
	private String name;
	
	//getters and setters...
}

public class PrefixTransformer extends HeaderTransformer {

	private final String prefix;

	public PrefixTransformer(String... args) {
		prefix = args[0];
	}

	@Override
	public String transformName(Field field, String name) {
		return prefix + "_" + name;
	}
}
```
I then use CsvRoutines to export a `User` object. I'll have fields like `country1_name` and `country2_name`. However, for the cities, both country1 and country2 will export their City field as `city_name`. Would there be a way to get for example **country1_city_name** and **country2_city_name** so that they can be differentiated and exported/imported correctly.

**Comment by jbax** [comment]
There's no way to make this work as all the information about headers is processed by from the classes and their structure, not the actual values of the objects you are writing. 

Essentially, from the class definitions alone, you can't know which given instance of `City` is contained by a given instance of `Country` so you can map to a "country1" or "country2".

As it stands this sort of mapping can't be handled by the library, sorry for that.

Thank you for using our parsers!
