### ISSUE TITLE
Automatic closing on exception when calling parseNext() is undesirable in some cases.

### ISSUE THREAD

**Issue by MrAaronOlsen** [uniVocity/univocity-parsers#227]
When an exception is thrown from parseNext() the default behavior is to close the input-stream and parser, effectively taking control of this out of the hands of the developer. I understand being conservative in this case as it's very possible an exception might be missed, thus keeping the input-stream open, but then again I think the onus for this should be on the developer, even without [AutoClosable](https://github.com/uniVocity/univocity-parsers/issues/71), which it looks like you are working on. I have a use case where I allow rows to fail, give a warning, but then move on to the next row. I can not easily do this right now when CSVParser experiences an error.

In my case this error is due to a column exceeding MaxCharsPerColumn. It starts as an ArrayOutOfBoundsException and is turned into a TextParsingException. Perfect, that's what I want.

I thought maybe sticking my own RetryableErrorHandler in my settings config and just swallowing the error, as I found here in issue [111](https://github.com/uniVocity/univocity-parsers/issues/111), but that doesn't seem to do the trick, probably because that's for writing not parsing... It appears that the issue bubbles down to AbstractParser's catch statement in parseNext():

```Java
}  catch (Throwable ex) {
   try {
      ex = handleException(ex);
   } finally {
      stopParsing(ex);
   }
}
```

So it seems that stopping the error from being thrown at all is really the only way to prevent it from closing. This would be undesirable too though since I'd like to either log or register the error in other ways.

Maybe there's a work around or something I'm missing now?

If not maybe something like:

```Java
}  catch (Throwable ex) {
   try {
      ex = handleException(ex);
   } finally {
      if(settings.keepOpenOnError) {
         throw ex;
      } else {
         stopParsing(ex);
      }
   }
}
```

And thank you for this wonderful tool!

**Comment by jbax** [comment]
Thanks for the suggestions but I'm not really sure if there's a way to reliably continue using the input after an error.

While it's easy to introduce as setting to prevent closing the input in case of errors, it won't be usable in most cases. The parser will stop but what remains in the input is partially processed.

In other words, if we just ignore the exception and try to proceed reading from a random place of the input we can't know what's next. If the input stopped just before a line break in a quoted value you are likely to get inconsistent results from that point forward.

In your case I believe your best bet is to set `MaxCharsPerColumn` to `-1` so any length is OK to the parser. Once you get a row you can validate the length of each value and emit warnings if appropriate.

Hope this helps.

By the way: the purpose of `MaxCharsPerColumn` is only to prevent blindly processing an incorrectly formatted input - imagine the case of someone uploading a 5GB CSV to your server using an unexpected format. The parser may try to load the entire thing into very large Strings and make your server run out of memory quite quickly.

**Comment by MrAaronOlsen** [comment]
Thanks for the reply, and I see your point. Trying to skip to the next line would just start parsing bad data since we have no idea where the real next line is. In fact the use case we encountered has multiple line breaks in a quoted text. Also, that quoted text has additional quotes inside of that causing all sorts of chaos. The problem was never a size limit thing, it was bad data. In this case we have no choice but to fail the parsing since we have no idea what's what anymore. When this happens now I just send along a clearer error of why it might have happened.

Thanks again for the reply and setting me straight!
