### ISSUE TITLE
get the line of original file from record

### ISSUE THREAD

**Issue by dario-frongillo** [uniVocity/univocity-parsers#229]
Hi,
can you kindly tell me how to retrieve the line number of related parsed Record ?
In other words if a csv record is parsed from line 99 of a file i want to retrieve 99.
thanks a lot
Dario

**Comment by jbax** [comment]
You are looking for something like this:

```
CsvParser parser = new CsvParser(settings);
parser.beginParsing(new File("/path/to/your.csv"));
long record = parser.getContext().currentRecord();
long line = parser.getContext().currentLine();
```

Hope this helps.
