### ISSUE TITLE
Trim quoted columns

### ISSUE THREAD

**Issue by ben-manes** [uniVocity/univocity-parsers#230]
In a CSV export, the column value is quoted with spaces; e.g. `"    1"`.

During import, this fails when read with `record.getInt` with a `NumberFormatException`. The default setting of trimming whitespace is enabled.

It looks like the quoted input is not trimmed, and the setting only trims whitespace surrounding it. It seems counter-intuitive that I would need to do my own conversion logic to handle this case.

**Comment by jbax** [comment]
Thanks for the suggestion, I'm not even sure how we got this far without this as it can obviously affect a lot of people.

I'll add an option to trim spaces inside quotes in version 2.6.2, i.e. very soon

**Comment by jbax** [comment]
All done, now you can use:

 * `trimQuotedValues`
 * `setIgnoreLeadingWhitespacesInQuotes`
 * `setIgnoreTrailingWhitespacesInQuotes`

I've released a 2.6.2-SNAPSHOT version which includes these. Let me know if you find any issues.

Thank you for using our parsers!

**Comment by jbax** [comment]
Version 2.6.2 released. Thanks again for the suggestion
