### ISSUE TITLE
Tsv parseall() object output format

### ISSUE THREAD

**Issue by Heavenwalker** [uniVocity/univocity-parsers#234]
I am trying to parse simple csv file (examples attached). If I use the beginparsing() method and print 
records one by one, everything works fine.

On the other hand, if I use the parseAll() and store it in a List<String[]> (let's call it allRows), then trying to print allRows results in something like this 

[[Ljava.lang.String;@15aeb7ab, [Ljava.lang.String;@7b23ec81, [Ljava.lang.String;@6acbcfc0, [Ljava.lang.String;@5f184fc6, [Ljava.lang.String;@3feba861, [Ljava.lang.String;@5b480cf9]

Here is the code that I am using.
```
@Override
    public void parseFile() {

        TsvParserSettings settings = new TsvParserSettings();
        TsvParser parser = new TsvParser(settings);
        List<String[]> allRows = null;
        try {
            allRows = parser.parseAll( new FileReader(getPath()));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        System.out.println(allRows);
    }



```[data.zip](https://github.com/uniVocity/univocity-parsers/files/1979946/data.zip)

**Comment by jbax** [comment]
That's how arrays of objects are printed in java. Use `Arrays.toString(row)` to print each array in your `allRows` list.

Thank you for using our parsers
