### ISSUE TITLE
Annotation parsing error with default Conversion

### ISSUE THREAD

**Issue by xenogew** [uniVocity/univocity-parsers#235]
My field of bean object look like this.
```
    @Convert(conversionClass = ToStringConversion.class)
    @Parsed(index=6, applyDefaultConversion = false)
    private String yearMonth;
```
But when run, it thrown the exception `DataProcessingException: Error converting value '2018/01' using conversion com.univocity.parsers.conversions.IntegerConversion`

Even I expected to force the conversion to pass the string value to the field. I don't know why algorithm don't do as I expected.

**Comment by jbax** [comment]
It looks like the error comes from another field. Can you share your
annotated class and a few rows of your input?

Thanks!

**Comment by xenogew** [comment]
@jbax It's alright now, look like it is my mistake that indicate the wrong order of the `index` value.
Thanks for you care.
