### ISSUE TITLE
heap memory consumption increase significantly after over 10 million rows reading and processing

### ISSUE THREAD

**Issue by jltz922181** [uniVocity/univocity-parsers#237]
Hi, 

I am using the univocity java parser to parse a large  tsv file with size of about 1.2 GB and totally about 20 million rows. I use the Object Row Processor, following the example code in the parser code repository:

ObjectRowProcessor rowProcessor = new ObjectRowProcessor() {
            @Override
            public void rowProcessed(Object[] row, ParsingContext context) {
                //System.out.println(Arrays.toString(row));
                processEachRow(row);
                increaseProcessedRowCounter(); 
            }
        };

I have my own function: processEachRow, to take the row passed from the parser, and then formulate a query to store the row into the backend data store. After that, I increase the processed row counter.

I found that after processing several million of rows,  the heap memory continues to grow, up to the point that the GC time is so huge that the application gets frozen. 

Right now, I just use the default parser settings and then invoke: 

parser.parse(new FileReader(myDataFileName));

I wonder what are the necessary parser settings that can have the parser to release the objects that passed to my code, so that the parsed row objects can be GC'ed. 

Regards,

Jun

**Comment by jbax** [comment]
It should not cause the heap size to increase. Does it happen if you
comment out the lines in your row processor?

If after removing 'processEachRow(row);' and 'increaseProcessedRowCounter();'
your heap size stops growing then there is something in your code that's
causing the problem.

Let me know if the issue persists and I'll have a look.

Thank you for using our parsers!

**Comment by jbax** [comment]
Any updates?

**Comment by jbax** [comment]
Closing for lack of updates.
