### ISSUE TITLE
CsvParser does not report certain serious errors.

### ISSUE THREAD

**Issue by derekmahar** [uniVocity/univocity-parsers#24]
[`CsvParser`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/csv/CsvParser.java) suppresses certain serious exceptions instead of throwing or returning them to the client.  For example, when using a [`BeanListProcessor`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/processor/BeanListProcessor.java), when `CsvParser` encounters a bean field for which a corresponding column name does not exist in the CSV file, `CsvParser` creates a [`TextParsingException`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/TextParsingException.java) containing the following message, but it neither throws this exception nor returns it to the client:

> java.lang.IllegalStateException: Could not find field with name 'Account Concurrency Code' in input. Names found: [Report Type, Filer Name, Filer Address, Filer City, Filer State/Province/Region, Filer Country, Filer GIIN, Filer TIN, Sponsored Entity Name, Sponsored Entity Address, Sponsored Entity City, Sponsored Entity State/Province/Region, Sponsored Entity Country, Sponsored Entity GIIN, Sponsored Entity TIN, Account Holder Name, Account Holder Address, Account Holder City, Account Holder State/Province/Region, Account Holder Country, Account Holder TIN, Account Holder Type, Owner Name, Owner Address, Owner City, Owner State/Province/Region, Owner Country, Owner TIN, Account Number, Account Currency Code, Account Balance, Interest, Gross proceeds/Redemptions, Dividends, Other, Pooled Reporting Type, Number of Accounts, Aggregate Payment Amount, Aggregate Account Balance, Pooled Currency Code]

The source of the problem appears to be in the [catch block](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/AbstractParser.java#L103) of method [`AbstractParser#parse(Reader)`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/AbstractParser.java#L76).  Though the call to method [`AbstractParser#handleException(Throwable)`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/AbstractParser.java#L177) returns a `TextParsingException` which it subsequently passes to method [`AbstractParser#stopParsing(Throwable)`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/AbstractParser.java#L261), none of these methods actually throw the exception (`AbstractParser#stopParsing(Throwable)` throws it, but only if it encounters *another* exception) and `AbstractParser#parse(Reader)` doesn't return the exception to its client.  When such an exception happens, [`BeanListProcessor#getBeans()`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.3/src/main/java/com/univocity/parsers/common/processor/BeanListProcessor.java#L74) also does not fail, but instead returns an empty list.  Consequently, `CsvParser` effectively suppresses serious exceptions without giving the client any clue as to why `BeanListProcessor` produces an empty result.

**Comment by jbax** [comment]
you WILL always find the original exception! The original exception appears
in the exception chain. Look at the stacktrace. There's a reason why the
Exception class has the "reason" attribute.

The exception message you got could not be more clear, and it helps you
find the problem. This is the whole point of Java's exception handling.

Don't get too mired by the "catch ( Throwable ex ) " blocks. They are there
to grab any error and populate a rich message with heaps of details about
the state of the parser when the error occurred, the potential causes of
the errors, and suggestions for you to fix the error.

In fact, I think the exception message you got is pretty fantastic and is
much more helpful than receiving an IndexOutOfBoundsException and leave you
without a clue why you got an error.

Best regards

**Comment by derekmahar** [comment]
How can I examine the stack trace or retrieve the error message if the
parser doesn't actually throw the exception? The error handler constructs
the exception, but then never actually throws it!

The exception message that I reported I copied from a watch variable in the
Eclipse debugger after the debugger stopped at a breakpoint that I had
placed in the error handler.  As far as I can tell, there is no other way
to access the exception and its contents.

Derek

**Comment by derekmahar** [comment]
Essentially, the parser error handler creates a `TextParsingException` that it subsequently neglects to throw.  The error is easy to reproduce. Using `@Parsed`, bind a column to a bean field, but specify a column name that doesn't exist in the CSV. The parser won't throw an exception and the `BeanListProcessor` will return an empty list of beans.

**Comment by derekmahar** [comment]
The problem should also be easy to fix. Simply throw the `TextParsingException` at some point in the error handling stack after invoking `stopParsing()`.

**Comment by jbax** [comment]
You are 100% correct!  

I think I misread your first comment and did not understand precisely what you said. Sorry for that.

I'll release a new version to fix this issue today. It is a regression introduced in the latest version.

Thank you so much for for your help, and for using our parsers,
Best regards

**Comment by jbax** [comment]
Fixed in this commit:
https://github.com/uniVocity/univocity-parsers/commit/4bc0c553e40ce1e47d8d2a6a43df5c5923898f8c

Will release version 1.5.4 soon.

**Comment by jbax** [comment]
Version 1.5.4 released to include a fix for this horrible issue.

It may take some time until you can get the artifact from the maven central repository. In this case grab the jar directly from [here](http://oss.sonatype.org/content/repositories/releases/com/univocity/univocity-parsers/1.5.4/univocity-parsers-1.5.4.jar)
