### ISSUE TITLE
Support Enum alternative values

### ISSUE THREAD

**Issue by exper0** [uniVocity/univocity-parsers#240]
I wonder if it's possible to support alternative input for the same Enum constant. Example: strings "Some value", "S" and "Some - value" may result in same logical enumeration constant SOME_VALUE. 
It's already possible to some degree - there are STRING, NAME and CUSTOM_FIELD selectors to deal with strings. However, if I have more than 3 synonyms it will not work. Also, NAME has limitations since it's java identifier. 
I'd actually change CUSTOM_METHOD behavior (or may be add new EnumSelector) to call some method of given Enum class:
`Enum<T> <method_name>(String value)`
i.e. delegate actual conversion to Enum itself. Or even better - utilize Java 8 functional capabilities and pass something like `Function<String, Enum<T>>` to EnumSelector to do actual conversion

**Comment by jbax** [comment]
I believe what you look for already exists. Try using `@EnumOptions(customElement = "methodFromEnum"):`

Where `methodFromEnum` is a method in your enumeration that returns a `String` that will match with what is in your input.

The `customElement` can also be an attribute defined inside your enum. The following example demonstrates both:

```
	public static enum Gender {
		MALE('M'),
		FEMALE('F'),
		UNSPECIFIED('U');

		private final char code;

		Gender(char code) {
			this.code = code;
		}

		public char code() {
			return code;
		}

		public String getCode() {
			if (code == 'M') {
				return "MAL";
			} else if (code == 'F') {
				return "FEM";
			} else {
				return "UNS";
			}
		}
	}

	public static class AB {

		@Parsed(index = 0)
		private Gender a;

		@Parsed(index = 1)
		private Gender b;

		@EnumOptions(customElement = "code")
		@Parsed(index = 2, defaultNullRead = "UNSPECIFIED", defaultNullWrite = "U")
		private Gender c;

		@EnumOptions(customElement = "getCode")
		@Parsed(index = 3)
		private Gender d;

		public AB() {

		}
	}

	@Test
	public void testConversionToEnumAndBack() {
		CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.getFormat().setLineSeparator("\n");
		BeanListProcessor<AB> beanProcessor = new BeanListProcessor<AB>(AB.class);
		parserSettings.setRowProcessor(beanProcessor);

		String input = "0,MALE,,MAL\n1,FEMALE,M,FEM";

		CsvParser parser = new CsvParser(parserSettings);
		parser.parse(new StringReader(input));

		List<AB> beans = beanProcessor.getBeans();
		assertEquals(beans.get(0).a, Gender.MALE);
		assertEquals(beans.get(0).b, Gender.MALE);
		assertEquals(beans.get(0).c, Gender.UNSPECIFIED);
		assertEquals(beans.get(0).d, Gender.MALE);
		assertEquals(beans.get(1).a, Gender.FEMALE);
		assertEquals(beans.get(1).b, Gender.FEMALE);
		assertEquals(beans.get(1).c, Gender.MALE);
		assertEquals(beans.get(1).d, Gender.FEMALE);

		CsvWriterSettings writerSettings = new CsvWriterSettings();
		writerSettings.getFormat().setLineSeparator("\n");
		writerSettings.setRowWriterProcessor(new BeanWriterProcessor<AB>(AB.class));

		beans.get(0).c = null;

		StringWriter out = new StringWriter();
		CsvWriter writer = new CsvWriter(out, writerSettings);
		writer.processRecordsAndClose(beans);

		String result = out.toString();
		assertEquals(result, "MALE,MALE,U,MALE\nFEMALE,FEMALE,MALE,FEMALE\n");
	}
```

Hope it helps.

**Comment by jbax** [comment]
Got it. So if you could use this: 

`@EnumOptions(customElement = "fromCode")`

Where `fromCode` takes a `String` parameter, it would work. For example:

```
     public Gender fromCode(String code) {
          switch(code){
               case "M":
               case "MAL":
               case "BLAH":
                    return Gender.MALE;
               case "F":
               case "FEM":
               case "LALA":
                    return Gender.FEMALE;
               default:
                    return Gender.UNSPECIFIED;
          }   
	  		
```

That's an easy adjustment. Will do it for the next version

**Comment by exper0** [comment]
@jbax right, this is what I meant. Thank you

**Comment by exper0** [comment]
@jbax any idea when 2.6.4 will be released?

**Comment by jbax** [comment]
By the end of the month, along with our new HTML parser.

**Comment by jbax** [comment]
Implemented and released a 2.6.4-SNAPSHOT build that includes support for this.

**Comment by exper0** [comment]
@jbax many thanks. Do you have any plans to move to java 8/functional style in further versions? Reflection, method names in strings and static methods are not so fancy

**Comment by jbax** [comment]
Yes, version 3.0.0 will be built with Java 8 and include streams, etc
