### ISSUE TITLE
Flexible creation of custom conversions

### ISSUE THREAD

**Issue by exper0** [uniVocity/univocity-parsers#241]
Imagine I need to create custom Enum conversion to support multiple String values for same Enum constant. I have to pass specific Enum class as a string in args parameter of Convert annotation. A bit ugly, isn't it? At the same time type is already there - it's available for default conversions. (e.g. default EnumConversion). I think there should be a way to create Custom conversions a bit more intelligent and support passing some parser metadata(field type) to conversion

**Comment by jbax** [comment]
Sounds like a duplicate of #240 . Have a look at my answer there and update the issue if you have further concerns.
Thank you for using our parsers!

**Comment by exper0** [comment]
No, it's not a duplicate. Situation with Enum is just example I encountered. Essentially, your parser is difficult to extend - I offered to improve this.
