### ISSUE TITLE
Use with Zip file

### ISSUE THREAD

**Issue by lionelhe** [uniVocity/univocity-parsers#242]
Hello,

I read csv files contained in a zip file.

The fact that the parser always close the reader or stream at the end of parsing causes problem with a ZipInputStream.
The stream shall stay opened for ZipInputStream, is there a way to avoid closing?

Thanks,

**Comment by jbax** [comment]
I believe you should be using the `InputStream` of each `ZipEntry` in your file. For example:

```
		CsvParser parser = new CsvParser(new CsvParserSettings());

		ZipFile zipFile = new ZipFile("/tmp/test.zip");

		Enumeration<? extends ZipEntry> entries = zipFile.entries();

		while(entries.hasMoreElements()){
			ZipEntry entry = entries.nextElement();
			InputStream stream = zipFile.getInputStream(entry);

			System.out.println(parser.parseAll(stream).size());
		}
```

My test.zip has 3 files, and I get all of them read properly without errors. I don't believe there's an issue here. Let me know if you think otherwise.

Thank you for using our parsers!

**Comment by lionelhe** [comment]
Hey, thank you for your quick answer.

The problem is that file is retrieved as MultipartFile so I cannot use it as ZipFile, I have to use the stream directly.

`protected void uploadZip(MultipartFile file) throws IOException, NoSuchAlgorithmException {
                ZipInputStream zis = new ZipInputStream(file.getInputStream());
		
		// get the zipped file list entry
		ZipEntry ze = zis.getNextEntry();

		while (ze != null) {

			String fileName = ze.getName();

			if (!ze.isDirectory()) {
				updateCsvData(zis);
			}
			ze = zis.getNextEntry();
		}

		zis.closeEntry();
		zis.close();`

I guess the solution would be to create a temp file on my backend but I would want to avoid doing that.
