### ISSUE TITLE
Escaping delimiting character

### ISSUE THREAD

**Issue by sunilkumarbm** [uniVocity/univocity-parsers#244]
Hi

I have a scenario where one of the rows in the data has the delimiting character in the content.

5 |0St"|"ring |field[1]: Should always pass - quoted field separator

where the delimiting character is | and it is also present in one of the columns as shown above.

My configuration is as below:
quoteChar = "
quoteEscapeChar = \\

But when I try to parse the row, it is splitting the column into two separate columns ("0St" and "ring") and failing.

If the put quote around the entire columns as shown below, it works fine.
5 |"0St|ring" |field[1]: Should always pass - quoted field separator

Is there any setting to specify delimiter escaping character?

I'm using 2.5.9

**Comment by jbax** [comment]
Any value that has a delimiter MUST be enclosed within quotes. Just adding quotes around the delimiter character is not enough. That's how the CSV format is supposed to work, so there's nothing to be done on the parser in this case. You must write the values properly. Maybe use the CsvWriter to generate the proper CSV data.

Thank you for using our parsers!
