### ISSUE TITLE
Delimiter works not well, when semicolon in value

### ISSUE THREAD

**Issue by KaijuDeluxe** [uniVocity/univocity-parsers#245]
I have values which html for example 

Frummel;hling; Summer; Winter

While uuml; is a html for ü, the semicolon is read as delimiter. So i geht a indexoutofbunds

**Comment by jbax** [comment]
Can you please provide a sample of your input file and the code used to parse and reproduce the error you are getting?

**Comment by KaijuDeluxe** [comment]
sure:

` CsvParserSettings parserSettings = new CsvParserSettings();
      parserSettings.detectFormatAutomatically();
      parserSettings.setNumberOfRowsToSkip(2);
      parserSettings.setMaxCharsPerColumn(-1);
      parserSettings.setEmptyValue("");
      parserSettings.setNullValue("");
      CsvParser parser = new CsvParser(parserSettings);
      List<String[]> resolvedData = parser.parseAll(new File("C://file.csv"),
          Charset.forName("ISO-8859-15"));
      System.out.println(parser.getDetectedFormat());

      for (String[] parts : resolvedData) {
//doing stuff
}`


[test.csv.zip](https://github.com/uniVocity/univocity-parsers/files/2115609/test.csv.zip)

**Comment by jbax** [comment]
I don't get any apparent error here. I just had to comment out the line with: `parserSettings.setNumberOfRowsToSkip(2);`, because the file has only 2 lines.

My code to print out the first and second rows (each value in a line, as the input is large) is:

CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.detectFormatAutomatically();
//		parserSettings.setNumberOfRowsToSkip(2);
		parserSettings.setMaxCharsPerColumn(-1);
		parserSettings.setEmptyValue("");
		parserSettings.setNullValue("");
		CsvParser parser = new CsvParser(parserSettings);
		List<String[]> resolvedData = parser.parseAll(new File("/tmp/test.csv"), Charset.forName("ISO-8859-15"));
		System.out.println(parser.getDetectedFormat());

		for (String[] parts : resolvedData) {
			int i = 0;
			for(String part : parts){
				System.out.println((++i) + "\t>>> " + part);
			}
			System.out.println("=====================");
		}

And produces this:

```
CsvFormat:
		Comment character=#
		Field delimiter=;
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
1	>>> XTSOL
2	>>> p_model
3	>>> p_stock
4	>>> p_sorting
5	>>> p_shipping
6	>>> p_tpl
7	>>> p_manufacturer
8	>>> p_fsk18
9	>>> p_priceNoTax
10	>>> p_priceNoTax.1
11	>>> p_priceNoTax.2
12	>>> p_priceNoTax.3
13	>>> p_priceNoTax.4
14	>>> p_priceNoTax.5
15	>>> p_priceNoTax.6
16	>>> p_priceNoTax.7
17	>>> p_priceNoTax.8
18	>>> p_priceNoTax.9
19	>>> p_priceNoTax.10
20	>>> p_tax
21	>>> p_status
22	>>> p_weight
23	>>> p_ean
24	>>> p_disc
25	>>> p_opttpl
26	>>> p_vpe
27	>>> p_vpe_status
28	>>> p_vpe_value
29	>>> p_image.1
30	>>> p_image.2
31	>>> p_image.3
32	>>> p_image.4
33	>>> p_image.5
34	>>> p_image.6
35	>>> p_image.7
36	>>> p_image.8
37	>>> p_image
38	>>> p_name.de
39	>>> p_desc.de
40	>>> p_shortdesc.de
41	>>> p_meta_title.de
42	>>> p_meta_desc.de
43	>>> p_meta_key.de
44	>>> p_keywords.de
45	>>> p_url.de
46	>>> p_cat.0
47	>>> p_cat.1
48	>>> p_cat.2
49	>>> p_cat.3
50	>>> p_cat.4
51	>>> p_cat.5
52	>>> 
=====================
1	>>> XTSOL
2	>>> Chef Cleaner BS2360-B/Iron
3	>>> 0
4	>>> 30
5	>>> 1
6	>>> default
7	>>> 
8	>>> 0
9	>>> 478.9496
10	>>> 
11	>>> 
12	>>> 
13	>>> 1:263.4202
14	>>> 1:263.4202
15	>>> 1:263.4202
16	>>> 
17	>>> 
18	>>> 1:263.4202
19	>>> 
20	>>> 1
21	>>> 0
22	>>> 13.000
23	>>> 4260184614059
24	>>> 0.00
25	>>> default
26	>>> 0
27	>>> 0
28	>>> 0.0000
29	>>> 98_1.jpg
30	>>> 98_2.jpg
31	>>> 
32	>>> 
33	>>> 
34	>>> 
35	>>> 
36	>>> 
37	>>> 98_0.jpg
38	>>> Dampfsauger Dampfstaubsauger mit Bügeleisen Blau
39	>>> <h2>Staubsaugen und Dampfreinigen mit einem Ger&auml;t</h2><p>incl. Dampfb&uuml;geleisen</p><p style="text-align: justify;">Technische Daten:</p><p style="text-align: justify;">mit satten 2350 Watt Leistung</p><p style="text-align: justify;">4 bar Dampfdruck</p><p style="text-align: justify;">Dampfvolumen ca. 30 g/mins</p><p style="text-align: justify;">Ger&auml;uschpegel kleiner als 80 DB</p><p style="text-align: justify;">Dampf Bereitschaftsanzeige&nbsp;</p><p style="text-align: justify;">Kombination von R&auml;dern und Rollen f&uuml;r leichte Bewegung&nbsp;</p><p style="text-align: justify;">nur 3 Minuten warten bis zur vollen Power</p><p style="text-align: justify;">25 Minuten kontinuierlicher Dampfdruck, sp&auml;testens an dieser Stelle trennt sich dann die Spreu vom Weizen</p><p style="text-align: justify;">Saugleistung gr&ouml;&szlig;er als 15 Kpa</p><p style="text-align: justify;">&nbsp;</p><p style="text-align: justify;">Das Ger&auml;t wird in schwarz / blau geliefert.</p><h3>Zubeh&ouml;r:</h3><p style="text-align: justify;">gro&szlig;e Reinigungsb&uuml;rste mit 2 Klingen</p><p style="text-align: justify;">gro&szlig;e Reinigungsb&uuml;rste mit 1 Klinge</p><p style="text-align: justify;">Wasserschiebe bzw. Fensterputzaufsatz</p><p style="text-align: justify;">Dampf und Vakuum-D&uuml;se</p><p style="text-align: justify;">4 tlg &nbsp;Dampfstrahl-D&uuml;senset</p><p style="text-align: justify;">Messbecher</p><p style="text-align: justify;">Trichter</p><p style="text-align: justify;">2 x T&uuml;cher</p><p style="text-align: justify;">Ger&auml;teabmessungen: 50 x 29 x 23.5cm</p><p style="text-align: justify;">Verpackungsabmessungen: 59,5 x 43,5 x 41 cm</p><p style="text-align: justify;">Gewicht nur ca. 7.5 kg&nbsp;</p><p style="text-align: justify;">ca. 5 Meter Anschlussleitung</p>
40	>>> 
41	>>> Dampfsauger mit passenden Dampfbügeleisen bei Syntrox.de
42	>>> Dampfsauger und Staubsauger in einem Gerät, für eine saubere Umgebung in seinem Haushalt. Dampfsauger mit passenden Bügeleisen in der Farbe Blau bei Syntrox.
43	>>> Dampfsauger mit Bügeleisen Blau
44	>>> Dampfsauger mit Bügeleisen Blau
45	>>> 
46	>>> Haushalt
47	>>> Dampfsauger
48	>>> 
49	>>> 
50	>>> 
51	>>> 
52	>>> 
=====================
```

Which is apparently correct. Which version of the library are you using? Maybe try the latest if you are not using it.

Thank you for using our parsers!

**Comment by KaijuDeluxe** [comment]
the file has hundred of rows i deleted them 

so i get this info when reading. the field delimiter is wrong. Any idea?

CsvFormat:
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Comment character=#
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Field delimiter=<
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Line separator (normalized)=\n
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Line separator sequence=\r\n
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Quote character="
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Quote escape character="
2018-06-19 16:14:29,365 INFO  [stdout] (EJB default - 1) 		Quote escape escape character=null

**Comment by jbax** [comment]
Ah that explains a lot. My first suggestion as you have HTML in this dataset is to limit the number of characters to be used as delimiters. You can do something like this:

`parserSettings.detectFormatAutomatically(';', ',');`

To limit the possible delimiters to be only `;` or `,`. You can add change the list of possible delimiter characters to suit your needs.

Also, the line separator detected for you is `\r\n`, which I'm guessing is what the parser finds inside the HTML content in your file.

My suggestion is that you should use the following:

		parserSettings.getFormat().setLineSeparator("\n"); //line ending set to "\n"
		parserSettings.setDelimiterDetectionEnabled(true, ';', ',');  //try to detect only the delimiter

Let me know if that helps

**Comment by KaijuDeluxe** [comment]
with a updated version, it works well :) Very good! Thank you

**Comment by jbax** [comment]
Glad to help!
