### ISSUE TITLE
I want to set mutli null value

### ISSUE THREAD

**Issue by YuanZhencai** [uniVocity/univocity-parsers#246]
```
     CsvParserSettings settings = new CsvParserSettings();
     settings.setNullValue("", "NULL", "NA");
```

**Comment by jbax** [comment]
Sorry but I don't see how this makes sense. When the parser reads a line such as `A,,C` , you will get a row with

`A, null, C`

If you set the null value to "NA" then the resulting row will be:

`A, NA, C`

The parser won't be able to decide when to pick `""`, `NULL` or `NA`. You should write your own custom code to replace the `null` in rows extracted from the parser, such as the original `A, null, C`,  with one of the tree null values you want.

**Comment by YuanZhencai** [comment]
OK, I'll replace it myself
