### ISSUE TITLE
Reading Multiple Header Lines in One Fixed-Width File

### ISSUE THREAD

**Issue by DanielJMaher** [uniVocity/univocity-parsers#249]
I can not see a reference in the documentation, so I am opening this issue to help me get a resolution.

The file is in this form

H dateOfFile metadata
D this is fixed width
D more of fixed width
E ending statement
H dataOfFile metadata
D that is fixed width
D more of fixed width
E ending statement

Would parsing a file like this (with multiple header lines) be possible?  Also, I do not see a reference for Footer lines.  Are they supported for parsing?

**Comment by jbax** [comment]
I'm not really clear on your requirements. Can you provide an actual sample
of the input to parse? Just the headers and a couple of rows should be
sufficient.
Thanks!

**Comment by jbax** [comment]
Closing as I didn't get an updated. Feel free to reopen when you are able to provide more info.
