### ISSUE TITLE
Concise documentation please

### ISSUE THREAD

**Issue by ozzioma** [uniVocity/univocity-parsers#25]
Hi!
Nice library you have here.
Been going through the intro articles and sample code, needed a quick solution to a data import problem. I bumped on this line : getReader("/examples/example.csv")
It's all over the examples and no code reference shown to explain exactly what it does.
You know there's only so much time to explore the myriad frameworks and libraries out there, so...I'm just thinking maybe a little clarification on the examples will make it look less confusing.

My 2 cents.
Thanks.

**Comment by jbax** [comment]
getReader() is used by our examples to provide an instance of `java.io.Reader`.

If you try to use the code you will see that the only input the parsers receive is a `java.io.Reader`.

You can actually use the search function of github to find it: https://github.com/uniVocity/univocity-parsers/search?utf8=%E2%9C%93&q=getReader.

[Here](https://github.com/uniVocity/univocity-parsers/blob/5f9e9137daf72ab5e953c3210c862c138ac1ef2f/src/test/java/com/univocity/parsers/examples/Example.java) is the implementation of `getReader`.

[Here](https://github.com/uniVocity/univocity-parsers/tree/5f9e9137daf72ab5e953c3210c862c138ac1ef2f/src/test/java/com/univocity/parsers/examples) is the source code of all examples.

But thanks for the suggestion. I thought the code was kind of self-explanatory, but I'll update the documentation to clarify the intention behind this `getReader` method.

**Comment by jbax** [comment]
Done in the following commit: https://github.com/uniVocity/univocity-parsers/commit/2865f8b631babdac10d5bfd426aa93babb86a59c

Thanks for your suggestion!

**Comment by ozzioma** [comment]
Quick response and nicely done!
Thanks.
