### ISSUE TITLE
Column names in the header row get printed in wrong order despite index values being set correctly

### ISSUE THREAD

**Issue by manish-in-java** [uniVocity/univocity-parsers#255]
I have the following class:

```
@Headers
public class Employee
{
  @Parsed(field = "Code", index = 0)
  private final String code;

  @Convert(args = "yyyy-MM-dd", conversionClass = DateConversion.class)
  @Parsed(applyDefaultConversion = false, field = "Exit date", index = 6)
  private final Date   exitDate;

  @Parsed(field = "Full/ part-time", index = 3)
  private final String fullPart;

  @Convert(args = "yyyy-MM-dd", conversionClass = DateConversion.class)
  @Parsed(applyDefaultConversion = false, field = "Joining date", index = 5)
  private final Date   joiningDate;

  @Parsed(field = "Name", index = 1)
  private final String name;

  @Parsed(field = "Title", index = 2)
  private final String title;

  @Parsed(field = "Type", index = 4)
  private final String type;
}
```

Things to note about this class:

1. It is annotated with `@Headers` so that a header row can be printed when records of this class are written using a `Writer`, such as, `CsvWriter`.
1. Fields to be printed are marked appropriately with `@Parsed`.
1. Column names for fields are specified appropriately with `@Parsed(field = ...)`.
1. Column order is specified appropriately with `@Parsed(index = ...)`.
1. Fields have been declared in alphabetical order instead of the order in which they should be printed.

I tried writing objects of this class as:

```
    final CsvWriterSettings settings = new CsvWriterSettings();
    settings.setQuoteEscapingEnabled(true);
    settings.setQuoteAllFields(true);
    settings.setRowWriterProcessor(new BeanWriterProcessor<>(Employee.class));

    final CsvWriter writer = new CsvWriter(System.out, settings);

    writer.processRecords(employees);

    writer.close();
```

I was expecting to see the following header row:

```
"Code","Name","Title","Full/ part-time","Type","Joining date","Exit date"
```

However, I am getting the following header:

```
"Code","Type","Title","Joining date","Name","Full/ part-time","Exit date"
```

The actual records get printed correctly.

I am attaching [a sample](https://github.com/uniVocity/univocity-parsers/files/2188062/univocity-writer-sample.zip).

**Comment by manish-in-java** [comment]
Looking at the part of the code that was changed for the fix, I am wondering if it would not be better for the class `TransformedHeader` to implement `Comparable`, sort instances first by `@Parsed#index` and then by `@Parsed#field`, and let `getFieldSequence` method return a `SortedSet` instead of a `List`? The implementation will become much simpler, and will avoid any similar bugs in the future, given that `SortedSet` guarantees correct order, as long as `Comparable#compareTo` has been implemented correctly.

**Comment by jbax** [comment]
Thanks for the suggestion. I even started to something about it but realized it's not that simple: the implementation has to take into account `TransformedHeader` instances that come from `@Nested` classes - you can't easily build a `Comparable` that takes into account the relationships among classes and their annotated fields.
