### ISSUE TITLE
Problems when using two BeanProcessors with an InputValueSwitch 

### ISSUE THREAD

**Issue by RocketPuppy** [uniVocity/univocity-parsers#256]
First, thanks for the great library! It's solved my use case handily.

I suspect this is user error on my part, but I'm receiving an error from the library when trying to parse one of my files. It has two different schemas, where the first row is one schema and the following rows are a second schema. For various reasons I distrust the originator of the files and I also don't have control over where and how this processor will eventually be run. For that reason I've structured things in such a way that there may be more than one "section" in a file being processed. 

I've decided to use an InputValueSwitch to handle processing the two schemas in my files. I supply two custom BeanProcessors, neither of them doing anything particularly exotic. One implements `beanProcessed` by setting a field on the incoming object and adding it to a storage array. The other implements `beanProcessed` by saving the processed record.

First question: I've specified all the fields for the two schemas on the same FixedWidthFields object. They are in order. I've also referenced them in `addSwitchToValue` and `setDefaultSwitch`. Is that the correct way of doing this? Should I actually have two FixedWidthFields objects, and if so how do I set up the processors?

Second question: I'm receiving a runtime error when processing my files. Specifically, I'm receiving `Caused by: java.lang.ClassCastException: com.univocity.parsers.common.processor.core.AbstractProcessorSwitch$1 cannot be cast to com.univocity.parsers.common.ParsingContext`. I've debugged a bit, and the problem seems to be here: https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/processor/core/AbstractProcessorSwitch.java#L118-L133. That is instantiating a new ContextWrapper, which seems to be resolved to the AbstractProcessorSwitch. Further down, my custom BeanProcessor's `beanProcessed` method is called with that value as the context, and the exception is thrown. Note though that the bean is instantiated correctly in that call.

Let me know if there's any more detail I can provide or if this is just a silly user error.

**Comment by jbax** [comment]
Hello there, I'm happy to help but can you provide the relevant code you are using to configure the parser? It would be helpful if you could also give me a sample test file with fake data that I could use to build a unit test that reproduces the bug.

Thank you for using our parsers!

**Comment by RocketPuppy** [comment]
@jbax Here's a small example of what I'm trying to do, although this example is failing on an integer conversion error.
```java
public class ParseFooFile {
    private final Resource file; //Spring resource
    private final FixedWidthParser parser;
    @Getter
    private final ArrayList<Foo> fooList;

    public ParseFooFile(Resource file, ArrayList<Foo> fooList) {
        this.file = file;
        this.fooList = fooList;

        FixedWidthFields fields = new FixedWidthFields();
        // Header fields
        fields.addField("RecordType", 1);
        fields.addField("FileName", 10);
        fields.addField("RecordCount", 10, FieldAlignment.RIGHT, '0');

        // Foo fields
        fields.addField("UserId", 10, FieldAlignment.RIGHT, '0');

        FixedWidthParserSettings settings = new FixedWidthParserSettings(fields);
        settings.getFormat().setLineSeparator("\n");
        settings.getFormat().setPadding(' ');
        FooFileProcessor fileProcessor = new FooFileProcessor();
        FooProcessor fooProcesser = new FooProcessor(fooList);
        InputValueSwitch processor = new InputValueSwitch("RecordType") {
            public void rowProcessorSwitched(RowProcessor from, RowProcessor to) {
                if(from == fileProcessor) {
                    fooProcesser.prepareForRecords(((FooFileProcessor) from).getFile());
                }
            }
        };
        processor.addSwitchForValue("H", fileProcessor,  "FileName", "RecordCount");
        processor.setDefaultSwitch(fooProcesser, "UserId");
        settings.setProcessor(processor);
        // settings.setProcessorErrorHandler(); // not implemented yet
        this.parser = new FixedWidthParser(settings);
    }

    public void parse() throws IOException {
        parser.parse(file.getInputStream());
    }
}
```
```java
@Data
public class Foo {
    @Trim
    @Parsed(field = "UserId")
    private Long userId;

   private FooFile fooFile;
}
```
```java
@Data
@AllArgsConstructor
@NoArgsConstructor
public class FooFile {
    @Trim
    @Parsed(field = "FileName")
    private String name;

    @Trim
    @Parsed(field = "RecordCount")
    private Integer recordCount;
}
```
```java
public class FooProcessor extends BeanProcessor<Foo> {
    private FooFile currentFile;
    private final ArrayList<Foo> foos;

    public FooProcessor(ArrayList<Foo> list) {
        super(Foo.class);
        this.foos = list;
    }

    public void prepareForRecords(FooFile file) {
        this.currentFile = file;
        this.foos.ensureCapacity(this.foos.size() + file.getRecordCount());
    }

    @Override
    public void beanProcessed(Foo f, ParsingContext parsingContext) {
        f.setFooFile(currentFile);
        this.foos.add(f);
    }
}
```
```java
public class FooFileProcessor extends BeanProcessor<FooFile> {
    @Getter
    private FooFile file;

    public FooFileProcessor() {
        super(FooFile.class);
    }

    @Override
    public void beanProcessed(FooFile f, ParsingContext parsingContext) {
        this.file = f;
    }
}
```
Sample file:
```
HFooFile   0000000001\n
0000000001\n
```
Bytes:
```
4648 6f6f 6946 656c 2020 3020 3030 3030
3030 3030 0a31 3030 3030 3030 3030 3130
000a
```

Error:
```
Caused by: com.univocity.parsers.common.DataProcessingException: Error converting value 'FooFile' using conversion com.univocity.parsers.conversions.IntegerConversion
Internal state when error was thrown: line=1, column=0, record=1, charIndex=32, headers=[RecordType, FileName, RecordCount, UserId], row=[H, FooFile, 1, null], value=FooFile, columnName=FileName, columnIndex=1
	at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:225) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.DefaultConversionProcessor.applyConversions(DefaultConversionProcessor.java:114) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:522) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.rowProcessed(AbstractBeanProcessor.java:54) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.AbstractProcessorSwitch.rowProcessed(AbstractProcessorSwitch.java:151) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.Internal.process(Internal.java:30) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:682) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:135) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:720) ~[univocity-parsers-2.7.1.jar:2.7.1]

Caused by: com.univocity.parsers.common.DataProcessingException: Error converting value 'FooFile' using conversion com.univocity.parsers.conversions.IntegerConversion
Internal state when error was thrown: line=1, column=0, record=1, charIndex=32, headers=[RecordType, FileName, RecordCount, UserId], row=[H, FooFile, 1, null], value=FooFile, columnName=FileName, columnIndex=1
	at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:225) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.DefaultConversionProcessor.applyConversions(DefaultConversionProcessor.java:114) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:522) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.rowProcessed(AbstractBeanProcessor.java:54) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.processor.core.AbstractProcessorSwitch.rowProcessed(AbstractProcessorSwitch.java:151) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.Internal.process(Internal.java:30) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:682) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:135) ~[univocity-parsers-2.7.1.jar:2.7.1]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:720) ~[univocity-parsers-2.7.1.jar:2.7.1]
```

**Comment by RocketPuppy** [comment]
Sorry, I'm a little confused. Where can I get the 2.7.2-SNAPSHOT release? I don't see it in the maven repository or in the github releases.

**Comment by jbax** [comment]
Fixed, I've updated your code to define one field configuration per record type, and also removed the header names you declared on calls to `addSwitchForValue`. 

                // Foo fields - the default format to use as nothing in the rows identify their type
 		FixedWidthFields fooFields = new FixedWidthFields();
		fooFields.addField("UserId", 10, FieldAlignment.RIGHT, '0');

		// Create the parser settings using foo fields as the default format.
		FixedWidthParserSettings settings = new FixedWidthParserSettings(fooFields);

		// Header fields - rows identified by the "H" lookahead
		FixedWidthFields headerFields = new FixedWidthFields();
		headerFields.addField("RecordType", 1);
		headerFields.addField("FileName", 10);
		headerFields.addField("RecordCount", 10, FieldAlignment.RIGHT, '0');
		// associate the "H" lookahead with the header fields
		settings.addFormatForLookahead("H", headerFields);


		settings.getFormat().setLineSeparator("\n");
		settings.getFormat().setPadding(' ');


		final FooFileProcessor fileProcessor = new FooFileProcessor();
		final FooProcessor fooProcesser = new FooProcessor(fooList);
		InputValueSwitch processor = new InputValueSwitch("RecordType") {
			public void rowProcessorSwitched(RowProcessor from, RowProcessor to) {
				if(from == fileProcessor) {
					fooProcesser.prepareForRecords(((FooFileProcessor) from).file);
				}
			}
		};
		processor.addSwitchForValue("H", fileProcessor);
		processor.setDefaultSwitch(fooProcesser);
		settings.setProcessor(processor);

I've released another SNAPSHOT build because I found other bugs that had to be fixed. If you use maven you can add this to your pom:

```
<repositories>
    ...
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
    ...
```

Alternatively the builds can be downloaded directly from here: https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/

But I'll try to release the final 2.7.2 version today anyway.

**Comment by RocketPuppy** [comment]
I see, so I needed to use both the lookahead and the InputValueSwitch. Thanks so much for the help and prompt response times! Is there any way I can contribute to the documentation/tutorials to help make this use case clearer there?

**Comment by jbax** [comment]
Yeah it's currently a special case for fixed width because you need to associate the fields with the lookahead. Then you need to associate the processors you want to use for each row format, which again is identified by the lookahead. While this is flexible it also ended up messing the API a bit. We're going to work on improving this on version 3.0.0.

Any contribution is welcome, documentation included. Feel free to send a PR. Thanks!
