### ISSUE TITLE
record.toFieldMap() not working on FixedWidth

### ISSUE THREAD

**Issue by joke** [uniVocity/univocity-parsers#258]
Hi,

I can't seem to get the `record.toFieldMap()` function to work. The map returned does not include any of the field names at all. The meta data seems to contain strange information.

Parsing works perfectly and all the rows can be parsed perfectly if I use the String[] output. And partial example of my setup is attached.

```
final FixedWidthParserSettings settings = new FixedWidthParserSettings();
...

final FixedWidthFields cp = new FixedWidthFields()
        .addField("id", 2)
        .addField("number", 7);
settings.addFormatForLookahead("CP", cp);

final FixedWidthFields da = new FixedWidthFields()
        .addField("id",  2)
        .addField("constant", 1);
settings.addFormatForLookahead("DA", da);

final FixedWidthFields as = new FixedWidthFields()
        .addField("id", 2)
        .addField("subsidiary", 2)
        .addField("articleNumber", 7);
settings.addFormatForLookahead("AS", as);

parser.parseAllRecords(...)
```

**Comment by jbax** [comment]
Thank you for reporting the bug! It's fixed on the latest 2.7.3-SNAPSHOT build you can use to test. [This link](https://www.univocity.com/pages/univocity_parsers_download#snapshot-releases) tells how you can get this build.

Thank you for using our parsers!
