### ISSUE TITLE
When BeanLisProcessor fails to convert a cell value, record name of invalid column in TextParsingException.

### ISSUE THREAD

**Issue by derekmahar** [uniVocity/univocity-parsers#26]
When the [`BeanListProcessor`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/processor/BeanListProcessor.java) fails to convert the value in a row and column, it should record not only the row number, but also the name of the invalid column in [`TextParsingException`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/TextParsingException.java).  Presently, the column name is not available in `TextParsingException`.

Though the invalid column index is available in the parser context given to `TextParsingException`, this column index is zero when the parser throws the exception because by the time the parser begins conversion, it has read all columns in the row and resets the column index to zero.  Consequently, the index of the invalid column is no longer available in the parser context when conversion takes place.  The invalid column index is available in [`FieldConversionMapping#applyConversions(int,String)`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/fields/FieldConversionMapping.java#L145), but the [`IllegalStateException`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/fields/FieldConversionMapping.java#L153) that this methods creates to report the error has no field to hold the invalid column index.

**Comment by derekmahar** [comment]
In order to implement this enhancement, I believe method [`FieldConversionMapping#applyConversions(int,String)`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/fields/FieldConversionMapping.java#L145), instead of throwing `IllegalStateException`, should throw a custom exception class that contains a field to store the invalid column index.

**Comment by derekmahar** [comment]
An alternative approach might be to record not only the parser context, but a conversion context that records the index of the column that the parser is converting and then when conversion fails, the parser could supply both the parser and conversion context to the `TextParsingException`.

**Comment by jbax** [comment]
Thank you for the suggestions. This should have been fixed by the following commit:
https://github.com/uniVocity/univocity-parsers/commit/2fa0b0aa404632ca19be811483c0783c3cada846

The [DataProcessingException](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/DataProcessingException.java) has been introduced to provide, when available, extra information such as row data, column index, name, and value.

I'll release a SNAPSHOT version of uniVocity-parsers 1.6.0. Let me know if you find any issue.
Thank you for using our parsers

**Comment by derekmahar** [comment]
Thank you for the quick turnaround time for this enhancement!  In a simple unit test that I wrote, `DataProcessingException` correctly recorded the column name of the cell containing invalid data in a CSV file.

**Comment by jbax** [comment]
Thank you! If you can, please submit your unit tests as a pull request. This is very useful for us to avoid the introduction of regressions when adding new features or fixing bugs.

**Comment by derekmahar** [comment]
Sorry, my comment wasn't clear.  The unit test that I wrote was for our private project and not specifically for the `univocity-parsers` project.
