### ISSUE TITLE
Bean: FixedWidth Integer with padding parsed as null

### ISSUE THREAD

**Issue by joke** [uniVocity/univocity-parsers#260]
Hi,

Created a fixed width parser and writer as described below:
```
@NullString(nulls = "   ")
@Parsed(defaultNullWrite = "   ")
@FixedWidth(value = 3, padding = '0', alignment = RIGHT)
private Integer number;
```

The fields in the fixed string input can either be `000`, `012` or `   ` (three blanks). During parsing the field is always parsed an null even if the input is `000`. The padding seems to be interfering with with the input reading and thus the value is read as null.

Unfortunately I can't remove the padding because the output needs to be padded if the input actually was actually an Integer like 12 or 4. In case the input is actually is null the output should be `   ` (three blanks).

Seems like a bug or am I missing some configuration options?

Regards
Joke

**Comment by joke** [comment]
Thanks for the information. Wouldn't have guess to apply individual settings on the getters and setters even though it's kind of obvious.

Unfortunately is not working as expected. The parser messes up the field order now. The bean looks like this:
```
@Parsed
@FixedWidth(value = 16)
private String name;

private Integer number;

@Parsed(defaultNullWrite = "   ")
@FixedWidth(value = 3, padding = ' ', alignment = RIGHT)
public Integer getNumber() {
	return number;
}

@Parsed
@FixedWidth(value = 3, alignment = RIGHT)
public void setNumber(final Integer number) {
	this.number = number;
}

@Parsed
@FixedWidth(value = 16)
private String description;
```

A NPE error is thrown during parsing but it seems to be caused by a wrong field order. The error message contains the header information: ```headers=[name, description, setNumber]```. The setter is added to the last position.

I tried setting an index option on the `@Parsed`-Annotation but that simply replaced the property at that position with the setter.

Is it possible to specify the position of the setter somehow without indexing all the properties or specifying `from` or `to` on the `@Parsed`-Annotation? The actual class has over 40 properties.

Regards
Joke

**Comment by jbax** [comment]
The field order is not guaranteed to be processed in the sequence they are declared and there is nothing we can do about it because it's JVM dependent. Even though it works most of the time (especially on older VMs), since JDK 1.8 you will get fields in any random order via reflection.

You must either explicitly set `@Parsed(index=<POSITION>)`, or call `settings.setHeaders(...)` with the sequence of attribute names in the correct order.

**Comment by joke** [comment]
Ah, good to know.
I tried specifying the positions and reading and writing works as expected.

Thank you very much.

Regards
Joke

**Comment by joke** [comment]
Sorry to bother again but I my success was a little bit to premature.
I condensed my test setup a little bit and now It seems the output padding is not working as it should be.
The `padding = "0"` option one the getter seems to be ignored. The output written without preceding `0`. The parsing on the other hand is working correctly: 000 is parsed as 0 and '   ' is parsed as null.

Regards
Joke

**Comment by joke** [comment]
I created an example project you https://github.com/joke/univocity
During the process I noticed that everything works as long as I don't use an OutputValueSwitch.

Regards
Joke

**Comment by joke** [comment]
Now I found the reason with the output with an OutputValueSwitch was not working correctly.
Unfortunately I registered the look ahead format by using `FixedWidthFields.forParsing` instead of `FixedWidthFields.forWriting`. Everything works as it should be.

I'm terrible sorry to have cause this much uproar. Thank you very much for your assistance. 

Regards
Joke
