### ISSUE TITLE
CsvRoutines.getInputDimension() returns one row less rowCount regardless of csvParserSettings.setHeaderExtractionEnabled()

### ISSUE THREAD

**Issue by karayv** [uniVocity/univocity-parsers#262]
For example, if I scan a CSV with 120 lines without header gives me 119. In case of a file with a header, this could be a correct result.

My code
```java
	private long countRows(InputStream fileInputStream, boolean skipHeader) {
		CsvParserSettings csvParserSettings = new CsvParserSettings();
		csvParserSettings.getFormat().setLineSeparator("\n");
		// csvParserSettings.setHeaderExtractionEnabled(skipHeader);
		CsvRoutines csvRoutines = new CsvRoutines(csvParserSettings);
		long rowCount = csvRoutines.getInputDimension(fileInputStream).rowCount();
		// issue workaround
		return skipHeader ? rowCount : rowCount + 1;
	}
```

In my case `rowCount + 1` is a sufficient workaround.

**Comment by jbax** [comment]
Thank you! I've fixed it and released another 2.7.3-SNAPSHOT release with the adjustment. Instructions on how to get a SNAPSHOT build are [here](https://www.univocity.com/pages/univocity_parsers_download#snapshot-releases)

Thanks for using our parsers!
