### ISSUE TITLE
New line ("\n") inside unquoted text

### ISSUE THREAD

**Issue by talberkoSB** [uniVocity/univocity-parsers#265]
Hi.
I have this example:

"a,b,c,d\na,b,c,d\na,b,c,d\nd"

I expect it to be parsed as:
a,b,c,d
a,b,c,d
a,b,c,d\nd

What I get as a result is:
a,b,c,d
a,b,c,d
a,b,c,d
d

Any way to handle it?

**Comment by jbax** [comment]
Sorry but that's not how the CSV format works at all. A line ending means end of the record unless it's inside a quoted value.

Thank you for using our parser
