### ISSUE TITLE
Support for java8 LocalDate, ZonedDateTime, Instant

### ISSUE THREAD

**Issue by unclethehornet** [uniVocity/univocity-parsers#267]
Hi, 

It seems that only java.util date/time classes are supported.  

Can support for java.time date/time classes (LocalDate, ZonedDateTime, Instant) be added 
so that they work out of the box?

Regards,
Dave.

**Comment by jbax** [comment]
Coming on version 3.0.0. Versions 1.* and 2.* are java 6 only.
