### ISSUE TITLE
How parse multi columns into one List field ?

### ISSUE THREAD

**Issue by kerraway** [uniVocity/univocity-parsers#269]
Hi, I'm using univocity-parsers, and I have a problem with it. Hope you can help me, thanks.
Csv file, without head, and I want to parse several serial columns into one List field. There are about 40  columns, I want put columns' index into list if the value equals 1.
This is my pojo.
```java
@Data
public class Car {

  @Parsed(index = 0)
  private Integer year;

  @Parsed(index = 1)
  private String make;

  @Parsed(index = 2)
  private String model;

  @Parsed(index = 3)
  @Convert(conversionClass = WordsToSetConversion.class, args = {",", "true"})
  private Set<String> description;

  @Parsed(index = 4)
  private BigDecimal price;
  
  // Not supported.
  // I hope so.
  @Parsed(index = {5, 35})
  private List<Integer> codes;

}
```
How can I make it? Please help me, thanks.

**Comment by jbax** [comment]
Currently your only option is to create a custom bean processor:

     public static class MyBeanConversionProcessor extends BeanConversionProcessor<Car> implements Processor<ParsingContext> {
		public MyBeanConversionProcessor() {
			super(Car.class);
		}

		@Override
		public void processStarted(ParsingContext context) {
			super.initialize(context.headers());
		}

		@Override
		public void rowProcessed(String[] row, ParsingContext context) {
			Car instance = createBean(row, context);
			if (instance != null) {
				instance.codes = new ArrayList<Integer>();
				for (int i = 5; i < 35; i++) {
					instance.codes.add(Integer.valueOf(row[i]));
				}

				// TODO: do whatever you need to do with your car instance.
			}
		}

		@Override
		public void processEnded(ParsingContext context) {
		}
	}

Don't even bother adding an annotation on the `codes` attribute of your class.
Hope this helps

Thank you for using our parsers!

**Comment by jbax** [comment]
A custon bean processor won't work with csv routines. You can probably copy
the code used by CsvRoutines and adjust it to use your processor.

Your case is a very specific one and there is nothing that will work out of
the box.

**Comment by kerraway** [comment]
I read the source codes. The CsvRoutines is connected with many classes, eg. AbstractRoutines, AbstractBeanProcessor. And the direct method is AbstractBeanProcessor#rowProcessed(String[] row, C context).
It's difficult to rewrite them for me. Can you show me some codes.
Thanks a lot.
