### ISSUE TITLE
Space delimiter not working

### ISSUE THREAD

**Issue by talberkoSB** [uniVocity/univocity-parsers#270]
` a      b      c 

asdad -0.111 -1.111

asdad -0.111 -1.111

asdad -0.111 -1.111
`

I cannot manage to make it work. Any idea?

**Comment by jbax** [comment]
Works fine for me:

		CsvParserSettings s = new CsvParserSettings();
		s.getFormat().setDelimiter(' ');
		for (String[] row : new CsvParser(s).iterate(new StringReader("a b c\nasdad -0.111 -1.111\nasdad -0.111 -1.111\nasdad -0.111 -1.111"))){
			System.out.println(Arrays.toString(row));
		}

Prints out:

    [a, b, c]
    [asdad, -0.111, -1.111]
    [asdad, -0.111, -1.111]
    [asdad, -0.111, -1.111]

"Not working" is not very specific. What code you use to parse and what are you getting as a result?

Maybe you need to define the correct line delimiter as well, or just use `s.setLineSeparatorDetectionEnabled(true);` in the code above to make it work.

Thanks for using our parsers!

**Comment by talberkoSB** [comment]
This is my code:

```		settings.setEmptyValue("")
		settings.setNullValue("")
		settings.setIgnoreTrailingWhitespacesInQuotes(true)
		settings.setIgnoreLeadingWhitespacesInQuotes(true)
		settings.getFormat.setDelimiter(' ')
		settings.setUnescapedQuoteHandling(UnescapedQuoteHandling.STOP_AT_CLOSING_QUOTE)
		settings.setLineSeparatorDetectionEnabled(true)
		val rowProcessor = new RowListProcessor()
		settings.setProcessor(rowProcessor)
		val parser = new CsvParser(settings)
                parser.parse(source.compression(source.source.open()))

		val rows = rowProcessor.getRows
		val data = JavaConverters.collectionAsScalaIterableConverter(rows).asScala
```

Result is first line is: `a b c`
Other lines are: `0 asdad` `0.111` `1.111`

**Comment by jbax** [comment]
The pure java code produces the correct results:

		CsvParserSettings settings = new CsvParserSettings();
		settings.setNullValue("");
		settings.setIgnoreTrailingWhitespacesInQuotes(true);
		settings.setIgnoreLeadingWhitespacesInQuotes(true);
		settings.getFormat().setDelimiter(' ');
		settings.setUnescapedQuoteHandling(UnescapedQuoteHandling.STOP_AT_CLOSING_QUOTE);
		settings.setLineSeparatorDetectionEnabled(true);
		RowListProcessor rowProcessor = new RowListProcessor();
		settings.setProcessor(rowProcessor);
		CsvParser parser = new CsvParser(settings);

		parser.parse(new StringReader("a b c\nasdad -0.111 -1.111\nasdad -0.111 -1.111\nasdad -0.111 -1.111"));

		List<String[]> rows = rowProcessor.getRows();

		for (String[] row : rows) {
			System.out.println(Arrays.toString(row));
		}

You should get:

[a, b, c]
[asdad, -0.111, -1.111]
[asdad, -0.111, -1.111]
[asdad, -0.111, -1.111]

Are you using the latest 2.7.5 version? I can only think this is some bug in your call to `JavaConverters.collectionAsScalaIterableConverter` or `source.compression(source.source.open())`, which is not used in my example as I have no access to these APIs.

**Comment by talberkoSB** [comment]
I tried with the same code as you, it still happens:

```
parser.parse(new StringReader("a b c\nasdad -0.111 -1.111\nasdad -0.111 -1.111\nasdad -0.111 -1.111"))
rowProcessor.getRows
val rows = rowProcessor.getRows
```

**Comment by jbax** [comment]
Does it happen if you use java instead of scala?

**Comment by talberkoSB** [comment]
Not sure, I will test it when I will get to it (our product is Scala). In Scala, I am sure it is not working :(

**Comment by jbax** [comment]
What version of univocity parsers are you using?

**Comment by talberkoSB** [comment]
The latest one - 2.7.+

**Comment by talberkoSB** [comment]
@jbax any idea? I think this ticket can be reopened, as there is probably a real problem with SCALA + JDK 8.0.

**Comment by jbax** [comment]
If it works in java then I can't do much as what happens on a given JVM
language is beyond my control.

Make sure you don't have an older version hanging around in your classpath.

If nothing works, then try another library to see if the issue still pops
up.

Sorry I couldn't assist more.
