### ISSUE TITLE
`headerExtractionEnabled` property works inproperly with ConditionalRowProcessorSwitch

### ISSUE THREAD

**Issue by BParnikel** [uniVocity/univocity-parsers#274]
**Scenario:**
- There is a CVF file with:
    - file header (e.g.with 2 columns)
    - data header + data itself (e.g. with 3 columns)
So `ConditionalRowProcessorSwitch` is used

**Problem:**
`null` value in columns with index > 1 of actual data leads to parsing exception 

**Analysis:**
Before `2.5.3` there was a check for headers initialization in `ParserOutput#initializeHeaders`
It was removed in this commit:
https://github.com/uniVocity/univocity-parsers/commit/eada3cb93e80842f63b9c784862fa45024dee7b4#diff-d1dde3ae43b3019e85d1f5930e35e915L140

For `AbstractProcessorSwitch#wrapContext` I am using the same implementation of `ParsingContextWrapper` as it used to be inside `AbstractProcessorSwitch#rowProcessed`
```java
@Override
protected ParsingContext wrapContext(ParsingContext parsingContext) {
    return new ParsingContextWrapper(parsingContext) {
        private final String[] fieldNames = ConditionalRowProcessorSwitch.this.getHeaders();
        ...
        public String[] headers() {
            return this.fieldNames != null && this.fieldNames.length != 0 ? this.fieldNames : this.context.headers();
        }
    };
}
```
	
Now without the mentioned check `context.headers` is initialized by file header's columns during `ParserOutput#initializeHeaders` execution.

Next, `DefaultConversionProcessor#initializeConversions` uses `contextHeaders` to build conversions for indexed fields `FieldConversionMapping#prepareExecution`
In its turn here map of conversions by index `conversionsByIndex` is filled.
As there are only 2 context headers instead of 3, default conversion (i.e. `NullStringConversion`) for primitives/numbers etc. is set only for first and second columns.
It leads to parse error if value in column with `index` > 1 is null as it tries to perform, for example, new `BigDecimal(null)`

**Comment by jbax** [comment]
Hi, I've created a unit test for this [here](https://github.com/uniVocity/univocity-parsers/blob/3575d30f32aca01abbabdfd9cda433e64ad6d550/src/test/java/com/univocity/parsers/issues/github/Github_274.java) but I didn't get any error.

I'm going to close this issue until you come back with a reproducible unit test the isolates the error you mentioned. Feel free to reopen and provide more details if you have them.

Thank you for using our parsers.
