### ISSUE TITLE
Expose byte position of current line's beginning

### ISSUE THREAD

**Issue by twiechert** [uniVocity/univocity-parsers#278]
It would be useful to access through the parser api the byte position the current line begins with ( within the underlying input stream).

The is useful in situations where data comes from a source that allows range-based (byte-wise) access of the data source. If something in the processing pipeline fails, the position of the last processed line can be saved and the pipeline be restarted beginning at this byte position.

In case this is not considered as relevant, I would be thankful for any advice regarding places in the code where I could reliably extract this information from.

**Comment by jbax** [comment]
The parser works with a `java.io.Reader` which abstracts away the input bytes - these are decoded into characters so you won't find any byte position anywhere in the code.

You can wrap your input into an `InputStream` and do whatever you like from it, but be mindful of the performance impact: it may make processing around 5 times slower depending on the case.

From the parser, the closest thing you can get is the current character position in the input, via `ParsingContext.currentChar()`

Hope this helps
