### ISSUE TITLE
record.fillFieldObjectMap and record.toFieldMap() return first line as Header as key and Header as value like(Name=Name))

### ISSUE THREAD

**Issue by amit210001** [uniVocity/univocity-parsers#284]
I am not sure whether it's a bug or not , if is there any way to get the key value in map instead of  ignoring the first line 
eg {Name=Name,RollNo=RollNo}
{Name=Test,RollNo=1} ...

Is there any API to get only {Name=Test,RollNo=1}...

**Comment by jbax** [comment]
I guess you need to use `settings.setHeaderExtractionEnabled(true);` so that the first record is considered the header row instead of a regular data row.

If you have trouble with this please post the code you are using so I can help you.

Thank you for using our parsers!
