### ISSUE TITLE
CsvRoutines.iterate & freeing resources

### ISSUE THREAD

**Issue by MartyIX** [uniVocity/univocity-parsers#285]
Hi,

Is it necessary to close some resource when I use the following code:

```java
// Let's configure our input format using the parser settings, as usual
// This configuration will be used as the base configuration for our routine.
CsvParserSettings parserSettings = new CsvParserSettings();
parserSettings.getFormat().setLineSeparator("\n");

// Here we create an instance of our routines object.
CsvRoutines routines = new CsvRoutines(parserSettings); // Can also use TSV and Fixed-width routines

// the iterate() method receives our annotated class and an input to parse, and return
// an Iterator for objects of this class.

// internally, it will create a special instance of BeanRowProcessor
// to handle the conversion of each record to a TestBean
for (TestBean bean : routines.iterate(TestBean.class, getReader("/examples/bean_test.csv"))) {
    println(bean); //let's print it out.
}		
```

?

Excerpt from: https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/examples/RoutineExamples.java#L29

Best regards,
Martin

**Comment by jbax** [comment]
Usually no. If all beans are read, or if any error occurs during the parser process all resources will be closed automatically.

The only case you have to care about is when you don't want to consume all elements, or if your code is can raise exceptions that will make the iteration to be aborted.

For this, `routines.iterate` returns a `IterableResult` (which extends from `Iterable`). You can call manually call `getContext().stop();` from it, like this:

```    
IterableResult<TestBean, ParsingContext> iterableResult = routines.iterate(TestBean.class, getReader("/examples/bean_test.csv"));
		try {
			for (TestBean bean : iterableResult) {
				println(bean);
			}
		} finally {
			iterableResult.getContext().stop();
		}
```

Hope this helps.
Thank you for using our parsers!

**Comment by MartyIX** [comment]
Thank you very much for detailed answer!
