### ISSUE TITLE
Auto-detect number of columns

### ISSUE THREAD

**Issue by benmccann** [uniVocity/univocity-parsers#286]
We recently switched to Univocity CSV parsing because it's faster. However, we ran into one place where using it can be more cumbersome. For large files, we now need to call `setMaxColumns`

Would it be possible for Univocity to buffer the first line into memory and detect how many columns there are rather than making us specify it?

**Comment by jbax** [comment]
That's a non issue. Just set the max columns to an absurd value, like 10
million, and forget about it.

Using the first row to determine the number of columns is unsafe as there
is no guarantee that subsequent rows will have that number of columns.

If your format is misconfigured, for example, your input uses \n as the
delimiter but the parser is configured to use \r\n. In this case it will
never find the end of the records and will accumulate all values of all
rows seuentially in an internal array, which expands up to the specified
limit of columns and then blows up in your face to let you know something
is wrong in your setup.

In such a scenario there won't ever exist a "first record" as the parser
can't know where it ends.

That setting protects you from misconfiguration and prevents your server
from spending a lot of resources (even risking running out of memory)
processing something unnecessarily.

Hope this helps to clarify.
 Thank you for using our parsers!

**Comment by benmccann** [comment]
I had tried setting it to a really large value and got:
```
java.lang.OutOfMemoryError: Java heap space
	at com.univocity.parsers.common.ParserOutput.<init>(ParserOutput.java:111)
	at com.univocity.parsers.common.AbstractParser.<init>(AbstractParser.java:79)
	at com.univocity.parsers.csv.CsvParser.<init>(CsvParser.java:67)
```

Perhaps another option would be to use growable data structures like a `List` instead of using an array?

**Comment by jbax** [comment]
Really, just use this and I'm sure all your problems will be solved:

```
settings.setLineSeparatorDetectionEnabled(true);
settings.setMaxColumns(10000);
```

You are having trouble with the line ending setting. Let the parser detect the line ending for you.

On your OutOfMemoryError case, this happens because an absurdly large value, such as `Integer.MAX_VALUE - 4`, will require you to allocate something like 12Gb of memory to the JVM (in my PC I had to go with `-Xms12G -Xmx12G`).

Also note that you must always limit to `Integer.MAX_VALUE-4`. The following code will always give you an `OutOfMemoryError`
```
public static void main(String ... args){
    String[] s = new String[Integer.MAX_VALUE];
}
```

You can never use Integer.MAX_VALUE to allocate an array.

**Comment by benmccann** [comment]
If we set it to 10000 won't we also be allocating much more memory than required? What's the reason for using an array instead of another data structure?

**Comment by jbax** [comment]
10000 uses around 40kb of memory which is a very small amount compared to Integer.MAX_VALUE. Using any other data structure will be slower than the array. Many data structures use arrays internally so there's no difference in changing the implementation. You also won't be able to grow an `ArrayList` to have more than `Integer.MAX_VALUE - 4` elements.

FYI, array of length:
 * 10 = 56 bytes
 * 100 = 416 bytes
 * 1000 = 4 kb
 * 10000 = 40 kb
 * 100000 = 400 kb
 * 1000000 = 4 mb
 * 10000000 = 40 mb
 * 100000000 = 400 mb
 * 1000000000 = 4gb
 * 2147483643 = 8.6gb --> (i.e. `Integer.MAX_VALUE - 4`)

But in reality you should not care too much about this. If you use any other parser instead, they will not stop if the format is not configured correctly, and you will risk running out of memory anyway. univocity-parsers will stop quickly let you know something is wrong.

Using a "data structure" will simply slow things down, leave you prone to a crash at runtime, and not fix your misconfiguration at all.

**Comment by benmccann** [comment]
Thanks for the very helpful explanation! This makes sense

**Comment by benmccann** [comment]
I wonder why the default of 512 columns was chosen though. Why not make the default 10000 given that it won't have much impact on memory and users would be far less likely to hit the limit?

**Comment by jbax** [comment]
The point is not the likelihood of hitting the limit or not. 512 columns should cover more than 90% of the use cases. Setting it too high will increase the rate of people running with a misconfigured parser and getting a bullshit result (i.e. a long row with 10000 columns or less) instead of an error telling them what's the issue.
