### ISSUE TITLE
Column validation mode.

### ISSUE THREAD

**Issue by derekmahar** [uniVocity/univocity-parsers#29]
Presently, when [`BeanListProcessor`](https://github.com/uniVocity/univocity-parsers/blob/v1.5.4/src/main/java/com/univocity/parsers/common/processor/BeanListProcessor.java) encounters a data conversion error, it throws an exception and stops processing.  The parser could benefit from a validation mode where instead of stopping after it encounters an error, it continues processing and collections all the conversion (or validation) errors.  This validation could involve performing a conversion, catching and recording the exception, and continuing to process the input while collecting all the errors in a row.  Or, it might test input against regular expression patterns and record all the cells in a row whose values don't match these patterns.  The result would be a list of pairs where each pair may contain a set of column errors or a valid bean (i.e. `List<Either<Set<Error>, Bean>>`) .

**Comment by jbax** [comment]
Thank you Derek. This is a great suggestion and I implemented this in a more flexible way in the following commit: https://github.com/uniVocity/univocity-parsers/commit/10633ef111c6b4f355196943768c183cc3963c2b

Both writers and parsers can now be configured with a [RowProcessorErrorHandler](
https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/RowProcessorErrorHandler.java). All non-fatal errors (such as conversions applied to a specific field) will result in your implementation of this handler to be invoked.

You can get all details you need from the parameters (the exception with column information when available, the input row, and the parsing context).

If this error handler is not defined, the behaviour remains the same as before. 

A new uniVocity-parsers-1.6.0-SNAPSHOT version has been released with this feature.

Thank you for the great suggestions to improve this library!
