### ISSUE TITLE
detect comments without comment-char

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#290]
Hi
we have to parse a csv file which contains something like this:
```

date:;26.11.2018
count:;3

some key;some value
another key;another value
"header1";"header2";"header3"
"value row1.1";"value row1.2";"value row1.3"
"value row2.1";"value row2.2";"value row2.3"
"value row3.1";"value row3.2";"value row3.3"
```

At the top of the file there is some filtercriteria which was used in the source-tool as well as some general comments and an arbitrary number of empty lines. Also the line with `count:;3` indicates that three rows of real data are contained down below.
After all of this more or less "comments section" there follows the real data with a header-row. Headers and the real data all use double quotes as shown above. This makes it ease for a human to distinguish where the real data starts.
What I need to do is just parse and use the data, the comments-section above isn't of any interest. 
To achieve this we used `parserSettings.setNumberOfRowsToSkip(6);` so far as there is no '#' or other sign indicating the first lines as comments. This works as long as the file is produced the same way everytime but you might already guess: the number of 'comments' changes sometimes. Getting one more comment results in an invalid comment-row beeing parsed; one missing comment results in the first line of correct data beeing skipped.
The only solution I see at the moment is pre-reading the file to count the lines not starting with a quote and pass this dynamically number into the above mentioned parserSetting. I'm just wondering if univocityParsers have any feature I missed so far to achieve this?

**Comment by blackfoxoh** [comment]
PS: as the comments are semicolon-separated key-value-pairs as well I propably will parse them for the value of the 'count:' key to doublecheck no data was skipped. But that isn't intended to be the topic here - just for completeness as I mentioned this above

**Comment by jbax** [comment]
The easiest thing to do in your case is to read these first few rows BEFORE submitting the rest of the input to the parser:

- create a `BufferedReader` to read the first lines without the parser
- once you get the first header row, break it down using CsvParser.parseLine()
- then use the parser to parse what is left in the `BufferedReader`.

Try this code:

```

		String input = "" +
				"date:;26.11.2018\n" +
				"count:;3\n" +
				"\n" +
				"some key;some value\n" +
				"another key;another value\n" +
				"\"header1\";\"header2\";\"header3\"\n" +
				"\"value row1.1\";\"value row1.2\";\"value row1.3\"\n" +
				"\"value row2.1\";\"value row2.2\";\"value row2.3\"\n" +
				"\"value row3.1\";\"value row3.2\";\"value row3.3\"\n";

		//Creates a buffered reader for convenience
		BufferedReader reader = new BufferedReader(new StringReader(input));

		//Read lines directly, until you get a quoted line.
		String line;
		while((line = reader.readLine()) != null){
			if(line.startsWith("\"") && line.endsWith("\"")){
				//got the first row
				break;
			}
			//process your comment lines.
			System.out.println("Comment: " + line);
		}

		if(line != null){
			//break the first line down using the parser.
			CsvParserSettings settings = new CsvParserSettings();
			settings.getFormat().setDelimiter(';');
			String[] headers = new CsvParser(settings).parseLine(line);
			System.out.println("Headers: " + Arrays.toString(headers));

			//Finally you can parse the input.
			settings.setHeaders(headers);
			CsvParser parser = new CsvParser(settings);
			List<String[]> rows = parser.parseAll(reader);

			for(String[] row : rows){
				System.out.println("Row:     " + Arrays.toString(row));
			}
		}
```

Hope this helps!
