### ISSUE TITLE
Usage from Maven?

### ISSUE THREAD

**Issue by oliviercailloux** [uniVocity/univocity-parsers#291]
Please document the usage of uniVocity from Maven. Following the tutorial does not give any information about this important step, therefore I am stuck at that very basic starting point.

I can [see](https://search.maven.org/search?q=g:com.univocity) many recent bundles but don’t which one(s) I should depend on (I suppose it depends on my needs?).

**Comment by jbax** [comment]
What don you mean from usage from maven? Are you trying to build it
yourself or just adding it as a dependency?

Check the bottom of the download page:
https://www.univocity.com/pages/univocity_parsers_download

Thank you for using our parsers!

**Comment by oliviercailloux** [comment]
Oh, sorry, I was confused and was looking at univocity download page (not univocity parsers).
