### ISSUE TITLE
Write BOM

### ISSUE THREAD

**Issue by oliviercailloux** [uniVocity/univocity-parsers#292]
Is there any way to ask univocity CsvWriter to write a BOM before anything else? A file with a BOM is required for import into [Blackboard Learn](https://www.blackboard.com/learning-management-system/blackboard-learn.html), it seems.

**Comment by oliviercailloux** [comment]
In my case I need to encode in UTF-8 and start with a BOM. How can I do this?

**Comment by jbax** [comment]
By hand:

BufferedWriter out = new BufferedWriter(new OutputStreamWriter(new
FileOutputStream(...), StandardCharsets.UTF_8));

//write UTF-8 bom marker
out.print('\ufeff');

//create csv writer to continue writing to 'out':
new CsvWriter(out, settings);

That should do the trick.

**Comment by oliviercailloux** [comment]
Ok, thanks for this. But I was hoping that CsvWriter would do it for me (upon demand in the settings). I consider it a feature of the desired format. Not that important, I admit, but nice to have.

Please consider this post as a feature request.

**Comment by jbax** [comment]
Closing as this is a non-issue and adding support for it in the settings will only add complexity for almost no benefit.
