### ISSUE TITLE
Fixed width parsing with look-ahead and non-contiguous field definitions

### ISSUE THREAD

**Issue by b3rnix** [uniVocity/univocity-parsers#294]
Here are two test, the first goes well and the second fails. I'm using the latest stable release, 2.7.6.
```
@Test
    public void withoutLookAhead(){
        StringReader input = new StringReader("XAAAAABBBBBCCCCCDDDDD\n");
        FixedWidthFields fields = new FixedWidthFields();
        fields.addField("chunk_1", 6, 11);
        fields.addField("chunk_2", 16, 21);
        FixedWidthParserSettings settings = new FixedWidthParserSettings(fields);
        settings.getFormat().setLineSeparator("\n");
        settings.setRecordEndsOnNewline(true);
        settings.setSkipTrailingCharsUntilNewline(true);
        FixedWidthParser parser = new FixedWidthParser(settings);
        Iterable<Record> iterator = parser.iterateRecords(input);
        for (Record r : iterator){

            Assert.assertEquals("BBBBB", r.getString(0));
            Assert.assertEquals("DDDDD", r.getString(1));
        }
    }
```

```
  @Test
    public void withLookAhead(){
        StringReader input = new StringReader("XAAAAABBBBBCCCCCDDDDD\n");
        FixedWidthFields fields = new FixedWidthFields();
        fields.addField("chunk_1", 6, 11);
        fields.addField("chunk_2", 16, 21);
        FixedWidthParserSettings settings = new FixedWidthParserSettings();
        settings.getFormat().setLineSeparator("\n");
        settings.setRecordEndsOnNewline(true);
        settings.setSkipTrailingCharsUntilNewline(true);
        settings.addFormatForLookahead("X", fields);
        FixedWidthParser parser = new FixedWidthParser(settings);
        Iterable<Record> iterator = parser.iterateRecords(input);
        for (Record r : iterator){
            System.out.println(r.getString(0));
            System.out.println(r.getString(1));
            Assert.assertEquals("BBBBB", r.getString(0));
            Assert.assertEquals("DDDDD", r.getString(1));
        }
    } 
```
The problem seems to arise when you combine a setup of non-contiguous fields and look-ahead.  I investigated further this issue. I found that when you setup non-contiguous fields, intermediate fields are created to fill the gaps and then marked as ignored. In a non-look-ahead setup, the parsers obtains the entire array of field lengths, (including ignored fields), and handles ignored fields as if they were normal fields and then simply doesn't add them to the resulting record. However, when the look-ahead setup is used, the field lengths are obtained in a different way in which the ignored fields get filtered. This can be seen here: 

[https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/fixed/FixedWidthFields.java], (method getFieldLengths).  

That causes the parser to grab the desired fields from the wrong locations within the file, as if they were all contiguous.

Thank you!

**Comment by jbax** [comment]
Thank you for reporting this bug! I've fixed it a couple of days ago but am having trouble uploading SNAPSHOT builds to maven central (I'm using a quirky backup pc). Will let you know once a build is available.

**Comment by jbax** [comment]
Version 2.8.0 released. Thank you!
