### ISSUE TITLE
[Question] How to improve performance to parse the selected fields from CSV files

### ISSUE THREAD

**Issue by QiangCai** [uniVocity/univocity-parsers#295]
Hi,
I have a scenario to extract one field from CSV files to create sample data.

After it selects the field, it still parses all fields, but output one field in the end.

The result is correct, but it wastes the resources to parse the other fields.

How can we parse only the selected fields to improve performance?

**Comment by jbax** [comment]
Thanks for your concern, but if you select fields with `settings.selectFields()` or `settings.selectIndexes` ,no resources will be wasted. The characters read from the input will be simply discarded as the `NoopCharAppender` will be active, this should be as fast as it can get.

Hope this clarifies how the parser works.

Thank you for using our parsers!

**Comment by QiangCai** [comment]
I can find all fields in the output object. 
It contains the actual data of all fields before selecting one field.

**Comment by QiangCai** [comment]
version: 2.2.1

**Comment by jbax** [comment]
Can you provide some test code and a sample input so I can verify this? The parser has been implemented with (hopefully) the proper field selection mechanism since version 1.0.0

**Comment by QiangCai** [comment]
csv file: 
the content of file1.csv as follows.
```csv
1|155190|7706|1|17|21168.23|0.04|0.02|N|O|1996-03-13|1996-02-12|1996-03-22|DELIVER IN PERSON|TRUCK|egular courts above the|
3|67310|7311|2|36|45983.16|0.09|0.06|N|O|1996-04-12|1996-02-28|1996-04-20|TAKE BACK RETURN|MAIL|ly final dependencies: slyly bold |
5|63700|3701|3|8|13309.60|0.10|0.02|N|O|1996-01-29|1996-03-05|1996-01-31|TAKE BACK RETURN|REG AIR|riously. regular, express dep|
7|2132|4633|4|28|28955.64|0.09|0.06|N|O|1996-04-21|1996-03-30|1996-05-16|NONE|AIR|lites. fluffily even de|
9|24027|1534|5|24|22824.48|0.10|0.04|N|O|1996-03-30|1996-03-14|1996-04-01|NONE|FOB| pending foxes. slyly re|
```

test code:
```java
public class TestUnivocityParser {

  public static void main(String[] args) throws IOException {

    try(Reader reader = new FileReader("/opt/bigdata/dataloading/file1.csv")) {
      CsvParserSettings settings = new CsvParserSettings();
      settings.selectIndexes(0);
      settings.getFormat().setDelimiter('|');
      CsvParser csvParser = new CsvParser(settings);
      csvParser.beginParsing(reader);
      String[] oneRow = csvParser.parseNext();
      System.out.format("%s", Arrays.toString(oneRow));
    }
  }

}

```

When I debug into the method ParserOutput.rowParsed, I watch two variables as following images.
I just need the first field, but it show we already parsed all fields.

![selection_099](https://user-images.githubusercontent.com/15495227/49910779-fefc7780-febe-11e8-93f4-f76f7d17db2d.jpg)

![selection_101](https://user-images.githubusercontent.com/15495227/49910785-028ffe80-febf-11e8-83e0-6cf56d8999b3.jpg)

**Comment by jbax** [comment]
Thank you for the details. The parser reads everything just on the first row (to possibly use these values as headers). If you change your test code to execute another call to `csvParser.parseNext();` you will see that it will generate strings only for the selected fields, and the rest will be `null`.
