### ISSUE TITLE
Wrong line ending detection when normalizeLineEndingsWithinQuotes = false

### ISSUE THREAD

**Issue by adutra** [uniVocity/univocity-parsers#299]
I would expect the following assertion to pass, but it doesn't:

```
CsvFormat format = new CsvFormat();
format.setLineSeparator("\r\n");
CsvParserSettings settings = new CsvParserSettings();
settings.setFormat(format);
// comment out the line below to make the assertion pass
settings.setNormalizeLineEndingsWithinQuotes(false);
CsvParser parser = new CsvParser(settings);
Record record = parser.parseRecord("foo,\" bar \",qix\r\n");
assert record.getValues().length == 3;
```

When `normalizeLineEndingsWithinQuotes = false`, the parser generates a spurious 4th field: `[foo,  bar , qix, null]`. When `normalizeLineEndingsWithinQuotes = true`, the assertion passes.

**Comment by jbax** [comment]
Thank you for reporting the bug! It's been fixed and will come up with version 2.8.0 to be released in a week.
