### ISSUE TITLE
handle array fields

### ISSUE THREAD

**Issue by parisni** [uniVocity/univocity-parsers#300]
Hi
csv might contain array columns, eg:

> array_decimal_field,decimal_field
> "{1111.222,2222.332}",222.4555

or

> array_string_field,decimal_field
> "{hello,world}",222.4555

that might be interesting to be able to get them. For eg by introducing new parser parameters such:
- arrayDelimiter (here ",")
- arrayOpening (here "{") 
- arrayClosing (here "}")

**Comment by jbax** [comment]
Thank you for the suggestion but that won't be implemented as part of the current CSV parser. Its API produces plain `String[]` as output rows. To support array columns the output rows would have to be either `String[][]` or `Object[]` which is a huge change that is also not backward compatible.
