### ISSUE TITLE
CsvParser beginParsing closes the stream

### ISSUE THREAD

**Issue by Luke791** [uniVocity/univocity-parsers#303]
Is there a way for beginParsing(Reader) not to close the underlying stream? I'm using it to parse zip entries, so the ZipInputStream needs not to be closed after each entry is parsed. Thanks.

**Comment by Luke791** [comment]
I have access only to the ZipInputStream, I don't have the file.

**Comment by jbax** [comment]
You need to save the input stream as a file first. There is no way to read
multiple entries from a zip inputstream alone as the data is not sequential

**Comment by Luke791** [comment]
No you don't. And yes, the data is sequential. getNextEntry() makes the stream advance to the beginning of next entry:

BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(zipInputStream));
ZipEntry entry = null;
String line = null;
while ((entry = zipInputStream.getNextEntry())!=null) {
    System.out.println("Printing content of file "+entry.getName()+": ");
    while ((line = bufferedReader.readLine())!=null) {
        System.out.println(line);
    }
}

**Comment by jbax** [comment]
Thanks, I stand corrected. That was something I (wrongly) learned a very long time ago and for some reason it stuck with me. 

I will add a flag to prevent closing automatically so it should not be an issue anymore.

**Comment by jbax** [comment]
Done. I just released 2.8.0-SNAPSHOT build with the changes so you can test it.

You can now use `parserSettings.setAutoClosingEnabled(false)` to prevent the parser from closing the stream.

Thanks again!

**Comment by Luke791** [comment]
Ok it works, I wait for the final release in order to use the regular Maven repository. Thanks.

**Comment by jbax** [comment]
Version 2.8.0 released. Thank you!
