### ISSUE TITLE
Allow longer line separators than two characters

### ISSUE THREAD

**Issue by pavelarnost** [uniVocity/univocity-parsers#307]
I have to parse CSV files where line separator is ";<CR><LF>" but setLineSeparator() allows maximum of two characters. I can set lineSeparator to ";<CR>" but that's not correct line separator as specified from data producer. Example of CSV record is:

"1.11","","","","21012019","";

Is there a reason for maximum of two characters for line separator?

**Comment by jbax** [comment]
Support for that has never been added simply because no one has ever asked for it :). This can also affect performance but I'll take a look into it.

**Comment by jbax** [comment]
Thanks for the suggestion but it's not going to be implemented: this requires a LOT of changes, added complexity and performance overhead for a corner case that up until now no one has ever needed.

Closing.
