### ISSUE TITLE
Problem after update to 2.8.0

### ISSUE THREAD

**Issue by glascaleia** [uniVocity/univocity-parsers#309]
After updating to 2.8.0 version i have problem in my code.
I think that depends on the fact that in the class ParserOutput when you call reset in the method will must added this 
final void reset() {
		this.columnsToExtractInitialized = false;
		this.currentRecord = 0;
		this.column = 0;
		this.headers = null;
                 this.headerStrings = null;
	}
Regards Giuseppe

**Comment by jbax** [comment]
Can you please provide a snippet of code that highlights the issue you found?

**Comment by glascaleia** [comment]
I have created a simple test.
I attach the test here and the files to parse.
Regards Giuseppe

[SimpleTest.zip](https://github.com/uniVocity/univocity-parsers/files/2831369/SimpleTest.zip)

**Comment by jbax** [comment]
Thank you for reporting this bug. I've fixed it and released a 2.8.1-SNAPSHOT build and will release the final version today as that's a pretty bad regression.

Thank you for using our parsers
