### ISSUE TITLE
Possible to add ignore annotation for java bean

### ISSUE THREAD

**Issue by jamking** [uniVocity/univocity-parsers#317]
For the csv data read as javabean, I won't write all the fields in the javabean to csv file. Is it possible to add annotation like "ignore" so only export the required field in csv.

**Comment by jbax** [comment]
Use `settings.setSelectedFields` or `settings.setSelectedIndexes` to choose what to write and in what order.

You can also map fields by hand without any annotations using a `FieldMapping`

        BeanWriterProcessor<Model> processor = new BeanWriterProcessor<>(Model.class);

		FieldMapper mapper = processor.getColumnMapper();

		//model
		mapper.attributeToIndex("a", 0);
		mapper.methodToIndex("_B", int.class, 1);
		mapper.methodToIndex("_B", 1);
		mapper.methodToIndex("setC", String.class, 2);
		mapper.methodToIndex("getC", 2);
		mapper.attributeToIndex("d", 3);


		//model.topmodel
		mapper.methodToIndex("m.setE", 0);
		mapper.methodToIndex("m.getE", 0);
		mapper.methodToIndex("m.setF", int.class, 1);
		mapper.methodToIndex("m.getF", 1);

        processor.setColumnMapper(mapper);

     CsvWriterSettings settings = new CsvWriterSettings();
		settings.setRowWriterProcessor(processor);
