### ISSUE TITLE
Unicode BOMs stripped for data but not(!) for header

### ISSUE THREAD

**Issue by wernerdaehn** [uniVocity/univocity-parsers#320]
When you read the data, the Unicode BOM is stripped. But if the reader is set to include headers because the csv file has a header line, then the first column header (cols[0] is below's code) has the Unicode BOM included. It is not stripped here.

				ObjectRowListProcessor rowprocessor = new ObjectRowListProcessor();
				settings.setProcessor(rowprocessor);				
				CsvParser parser = new CsvParser(settings);
				parser.parse(in, getCharset(format));
				List<Object[]> result = rowprocessor.getRows();
				String[] cols = parser.getRecordMetadata().headers();

**Comment by jbax** [comment]
As you are providing the charset explicitly, the parser won't try to extract a BOM from it. I believe you addressed this in issue #321 so I'll close this issue.

For this current issue. the following should work:

```
parser.parse(in);
```

Thanks
