### ISSUE TITLE
The result of the method of Exception class is wrong.

### ISSUE THREAD

**Issue by TalkWithWater** [uniVocity/univocity-parsers#324]
https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/TextParsingException.java#L118-L120

Maybe,the reference variable of the method is "recordNumber".

p.s.
 As it is the first issue report, I'm sorry if how to  write it wrong.

**Comment by jbax** [comment]
Silly mistake. Thanks for reporting this bug. Fixed already.

Thank you for using our parsers!
