### ISSUE TITLE
auto detect format with upper and lower thom is not working 

### ISSUE THREAD

**Issue by howie-merkle** [uniVocity/univocity-parsers#328]
i'm adding detectFormatAutomatically with upper and lower THOM (231 & 232) in the delimiter list to the setting then calling CVSParser.  the auto detect is not finding the THOM as a separator ,

I bereave that the issue is in isSymbol because the THOM is a Letter via isLetterOrDigit

charterers in allowedDelimiters should be considered symbols

**Comment by howie-merkle** [comment]
private boolean isSymbol(char ch) {
        return isAllowedDelimiters(ch) || ch != comment && !Character.isLetterOrDigit(ch) && (ch == '\t' || ch >= ' ');
    }

    private boolean isAllowedDelimiters(char ch) {
        boolean found = false;
        for (int i = 0; i < allowedDelimiters.length; i++) {
            if (allowedDelimiters[i] == ch) {
                found = true;
                break;
            }
        }
        return found;
    }

**Comment by jbax** [comment]
Thank you for reporting this bug and suggesting a solution, I've fixed this and released 2.8.3-SNAPHOT version that you can use to test.

Thanks for using our parsers!
