### ISSUE TITLE
Parsing flat file error logic when "from / to" is used

### ISSUE THREAD

**Issue by PiotrDuz** [uniVocity/univocity-parsers#332]
Hello,
I would like to flash some light on following issue:
My flat file:
"
tol  er
fer  de
"

My Bean class:
`
public class UniBean
{
    @FixedWidth(from = 0, to = 4)
    @Parsed()
    private String first;

    private String second;

    @Override
    public String toString()
    {
        return "Bean{" + "a1=" + first + " " + '}';
    }
}
`

(second field is not parsed ON purpose)
And now reading test:
`File input = new File(testPath, "in/cat.dat");

        FixedWidthParserSettings settings = new FixedWidthParserSettings();
        settings.getFormat().setLineSeparator("\n");
        settings.setRecordEndsOnNewline(false);
        settings.setHeaderExtractionEnabled(false); // This one is important as
                                                    // your input has no
                                                    // headers.

        FixedWidthRoutines routines = new FixedWidthRoutines(settings);
        for (UniBean bean : routines.parseAll(UniBean.class,
                                              new FileReader(input)))
        {
            System.out.println(bean);
        }`

What do I expect: 
First line will be parsed. Field "first" will get values from 0 to 4. There are no other fields, so parser will wait for newline. 
In new line, again chars from 0 to 4 will be parsed and saved to "first" field. 

What is happening: 
The parser is not waiting for newline. It is parsing 0 - 4 chars properly, and for next chars, starts parsing as soon as there are no other fields to save. 

Output from running the program: 
`Bean{a1=tol }
Bean{a1=er }
Bean{a1=fer }
Bean{a1=de }`

Regards.

**Comment by jbax** [comment]
The problem here is that the fixed width parser will not wait for a new line to show up. It needs to know in advance the full format of your records so the data can be processed properly. Your annotations are not providing the correct record layout. You need to do this:

In your case you need to specify the field lengths without using the annotations:

		FixedWidthFields fields = new FixedWidthFields();
		fields.addField(0,4);
		fields.addField(4,6);

		FixedWidthParserSettings settings = new FixedWidthParserSettings(fields);
		settings.getFormat().setLineSeparator("\n");

Now you can annotate your bean with this:

	public static class UniBean {
		@Parsed(index = 0)
		private String first;
                ...
       }

This will generate 2 beans, with values `tol` and `fer` respectively, which is what you want to get.

Hope this helps and thank you for using our parsers

**Comment by PiotrDuz** [comment]
When someone wants to still use annotations, little hack is to annotate the last column. Then parser will have the full length of a row.
