### ISSUE TITLE
how to append new rows to exist file but not override it?

### ISSUE THREAD

**Issue by jujusharp** [uniVocity/univocity-parsers#333]
Hi,
  I'm now using this parser in my project, but I can't find anyway to append content into a exist file, I read the tutorials, and read all constructors in the CsvWriter, but can't find anyway to do this.
 If I've missed any thing or the parser now not support this feature?

**Comment by jbax** [comment]
Use a FileWriter setting the append flag to true.

**Comment by jujusharp** [comment]
Ok, got it , and thanks very much

**Comment by hromao** [comment]
I am having the same problem and could not solve it. Can you provide any sample?

**Comment by jbax** [comment]
@hromao just give the CsvWriter a `FileWriter`:
 
    Writer fileWriter = new FileWriter("/path/to/your.csv", true);
    CsvWriter csvWriter = new CsvWriter(fileWriter, settings);

Hope this helps
