### ISSUE TITLE
Suppressing Scientific Notation on CsvWriter

### ISSUE THREAD

**Issue by pmengaziol** [uniVocity/univocity-parsers#335]
I have not been able to figure out how to suppress scientific notation while writing out csv data. I am trying to attach the formatting override to any numeric instance dynamically but it seems like the convertType approach fails in this case.

**Comment by jbax** [comment]
Can you show some test code so I can help you out?

**Comment by pmengaziol** [comment]
I will have to create some since I cannot send you my entire app plus data. Please give me a couple of days.

**Comment by pmengaziol** [comment]
Hey Jeronimo,

My use case needs to use dynamically defined data (coming from json). I will not be able to annotate any classes ahead of time.

I copied my Junit class ->

publicclassCsvTests {

@Test

publicvoidscanRows() {

             ArrayList<LinkedHashMap<String,Object>>rows;

rows=newArrayList<LinkedHashMap<String,Object>>();

              LinkedHashMap<String, Object>row1=newLinkedHashMap<String, Object>();

row1.put("key", 1);

row1.put("longValue", 1111111111000L);

row1.put("doubleValue", 1234567890.12345);

rows.add(row1);

              LinkedHashMap<String, Object>row2=newLinkedHashMap<String, Object>();

row2.put("key", 2);

row2.put("longValue", 2222222222000L);

row2.put("doubleValue", 2234567890.12345);

rows.add(row2);

rows.stream().forEach(System.out::println);

// CsvWriter (and all other file writers) work with an instance of java.io.Writer

              CsvWriterSettingssettings=newCsvWriterSettings();

settings.setHeaderWritingEnabled(true);

settings.setEmptyValue("-");

settings.setSkipEmptyLines(true);

settings.setNullValue("-");

              CsvWriterwriter=newCsvWriter(System.out,settings);

              Set<String>fieldsNames=rows.get(0).keySet();

writer.writeHeaders(fieldsNames);

rows.stream().forEach(writer::writeRow);

writer.close();    

       }

}

Thanks in advance,

Peter

From:Peter Mengaziol <pmengazi@optonline.net mailto:pmengazi@optonline.net >
Sent:Wednesday, June 19, 2019 3:18 PM
To:Mengaziol, Peter <pmengaziol@ofiglobal.com mailto:pmengaziol@ofiglobal.com >
Subject:[EXT] Fwd: Re: [uniVocity/univocity-parsers] Suppressing Scientific Notation on CsvWriter (#335)

Original Message From: Jeronimo Backes <notifications@github.com> To: uniVocity/univocity-parsers <univocity-parsers@noreply.github.com> Cc: pmengaziol <pmengazi@optonline.net>, Author <author@noreply.github.com> Date: June 18, 2019 at 4:06 PM Subject: Re: [uniVocity/un…

****************************************************************
Confidentiality Note: The information contained in this
message, and any attachments, may contain confidential
and/or privileged material. It is intended solely for the
person(s) or entity to which it is addressed. Any review,
retransmission, dissemination, or taking of any action in
reliance upon this information by persons or entities other
than the intended recipient(s) is prohibited. If you received
this in error, please contact the sender and delete the
material from any device.
****************************************************************

**Comment by jbax** [comment]
It's all a matter of formatting the numbers otherwise the result of `Double.toString()` will be used. You can use a `DecimalFormat` to convert these double values to a `String` in the format you like then put that in your map, or let the parser do it for you with a processor:

    CsvWriterSettings settings = new CsvWriterSettings();
    ObjectRowWriterProcessor processor = new ObjectRowWriterProcessor();
    // formats any double value to print up to 10 decimal places (the rest is left out)
    processor.convertType(Double.class, Conversions.formatToNumber("#.##########"));
    settings.setRowWriterProcessor(processor);

When using a processor, you need to write your rows using `processRecord`, so use this when writing:

    rows.stream().forEach(writer::processRecord);

Hope this helps.

**Comment by pmengaziol** [comment]
// Did not work!
public class CsvTests {
	@Test
	public void scanRows() {	
		ArrayList<LinkedHashMap<String, Object>> rows;
		rows = new ArrayList<LinkedHashMap<String, Object>>();
		
		LinkedHashMap<String, Object> row1 = new LinkedHashMap<String, Object>();
		row1.put("key", 1);
		row1.put("longValue", 1111111111000L);
		row1.put("doubleValue", 1234567890.12345);
		rows.add(row1);
		
		LinkedHashMap<String, Object> row2 = new LinkedHashMap<String, Object>();
		row2.put("key", 2);
		row2.put("longValue", 2222222222000L);
		row2.put("doubleValue", 2234567890.12345);
		rows.add(row2);

		rows.stream().forEach(System.out::println);

		// CsvWriter (and all other file writers) work with an instance of java.io.Writer
		CsvWriterSettings settings = new CsvWriterSettings();
		ObjectRowWriterProcessor processor = new ObjectRowWriterProcessor();
		// formats any double value to print up to 10 decimal places (the rest is left out)
		processor.convertType(Double.class, Conversions.formatToNumber("#.##########"));
		processor.convertType(Float.class, Conversions.formatToNumber("#.##########"));
		processor.convertType(double.class, Conversions.formatToNumber("#.##########"));
		processor.convertType(float.class, Conversions.formatToNumber("#.##########"));
		processor.convertType(Number.class, Conversions.formatToNumber("#.##########"));

		settings.setRowWriterProcessor(processor);
		settings.setHeaderWritingEnabled(true);
		settings.setEmptyValue("-");
		settings.setSkipEmptyLines(true);
		settings.setNullValue("-");
		CsvWriter writer = new CsvWriter(System.out, settings);
		
		Set<String> fieldsNames = rows.get(0).keySet();
		writer.writeHeaders(fieldsNames);
		rows.stream().forEach(writer::writeRow);
		writer.close();
	}
}
// results are
// {key=1, longValue=1111111111000, doubleValue=1.23456789012345E9}
// {key=2, longValue=2222222222000, doubleValue=2.23456789012345E9}
// key,longValue,doubleValue
// 1,1111111111000,1.23456789012345E9
// 2,2222222222000,2.23456789012345E9

**Comment by jbax** [comment]
you forgot to change the line with `rows.stream().forEach(writer::writeRow);` to `rows.stream().forEach(writer::processRecord);`
