### ISSUE TITLE
Spark Univocity parser - LineSeparatorDetection not working

### ISSUE THREAD

**Issue by AadhiKat** [uniVocity/univocity-parsers#340]
I am trying to parse [this](https://drive.google.com/file/d/17il3TI_WGzvPHooTDyc-rF1C2YlNq1SW/view?usp=sharing) csv file using univocity csv parser with the following options

```
HEADER -> true
DELIMITERS -> ,
MULTILINE -> true
DEFAULT_TIME_STAMP -> yyyy/MM/dd HH:mm:ss ZZ
IGNORE_TRAILING_WHITE_SPACE -> false
IGNORE_LEADING_WHITE_SPACE -> false
TIME_ZONE -> Asia/Kolkata
COLUMN_PRUNING -> true
ESCAPE -> "\""

val csvOptionsObject = new CSVOptions(readerOptions, COLUMN_PRUNING , TIME_ZONE)
val parserInstance = csvOptionsObject.asParserSettings
parserInstance.setLineSeparatorDetectionEnabled(true)
val parserObject = new CsvParser(parserInstance)
val readerStream = parserObject.beginParsing(dataObj.getInputStream, csvOptionsObject.charset)
val row = parserObject.parseNext()
```

The file has 30 columns but when I parse it is showing as 2302 rows.

The file has \r as line separator. (as I can see it while parsing)

Setting the line separator explicitly as \r resolves this issue. But I will also have files with \n as separator that is replaced as \r. To resolve this setting setNormalizedLineEndingWithinQuotes(false) resolves , but fails with other files where all the values are quoted.(Again fails to detect the separator).

Any possible work around ?

**Comment by jbax** [comment]
Which version of the library do you have on your classpath? I could not reproduce the error with the latest version, so try to upgrade to 2.8.2 and see if it helps.

Thank you for using our parsers!

**Comment by AadhiKat** [comment]
I tried using 2.8.2 . Still the line separator is always detected as \n. Even if the file has windows line endings or Mac OS line endings. Can you please tell me what am I missing or what could be possibly wrong with this setting!

**Comment by jbax** [comment]
It might be a spark issue. If I'm not mistaken some versions split the
lines then send each one to the parser.

You can try to use the parser directly instead to see if it works

**Comment by AadhiKat** [comment]
Yes ! You were right . Directy using the parser resolved this ! Thanks a ton!
