### ISSUE TITLE
CsvParser restrict to number of rows

### ISSUE THREAD

**Issue by abhi18121** [uniVocity/univocity-parsers#341]
How to restrict CsvParser to number of rows?

**Comment by jbax** [comment]
parserSettings.setNumberOfRecordsToRead(9);

Thank you for using our parsers

**Comment by abhi18121** [comment]
Thank you for update.  If I want to restrict user to upload more than specified limit? Ex 10k

**Comment by jbax** [comment]
csvRoutines.getInputDimension should do the trick for you
