### ISSUE TITLE
Exception while Parsing

### ISSUE THREAD

**Issue by Sundarcj** [uniVocity/univocity-parsers#346]
Hi am using 2.8.2 version  got this exception always while parsing .

> 
> Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.NullPointerException - null
> Parser Configuration: CsvParserSettings:
> 	Auto configuration enabled=true
> 	Auto-closing enabled=true
> 	Autodetect column delimiter=false
> 	Autodetect quotes=false
> 	Column reordering enabled=true
> 	Delimiters for detection=null
> 	Empty value=null
> 	Escape unquoted values=false
> 	Header extraction enabled=null
> 	Headers=null
> 	Ignore leading whitespaces=true
> 	Ignore leading whitespaces in quotes=false
> 	Ignore trailing whitespaces=true
> 	Ignore trailing whitespaces in quotes=false
> 	Input buffer size=1048576
> 	Input reading on separate thread=true
> 	Keep escape sequences=false
> 	Keep quotes=false
> 	Length of content displayed on error=-1
> 	Line separator detection enabled=true
> 	Maximum number of characters per column=4096
> 	Maximum number of columns=100
> 	Normalize escaped line separators=true
> 	Null value=null
> 	Number of records to read=all
> 	Processor=sheetapp.version2.parsing.CSVFileParser$CSVRowListener
> 	Restricting data in exceptions=false
> 	RowProcessor error handler=null
> 	Selected fields=none
> 	Skip bits as whitespace=true
> 	Skip empty lines=true
> 	Unescaped quote handling=nullFormat configuration:
> 	CsvFormat:
> 		Comment character=#
> 		Field delimiter=,
> 		Line separator (normalized)=\n
> 		Line separator sequence=\n
> 		Quote character="
> 		Quote escape character="
> 		Quote escape escape character=null
> Internal state when error was thrown: line=22489344, column=0, record=22489344, headers=[Transaction unique identifier, Price, Date of Transfer, Property Type, Old/New, Duration, Town/City, District, County, PPDCategory Type, Record Status - monthly file only]
> 	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:389)
> 	at com.univocity.parsers.common.AbstractParser.stopParsing(AbstractParser.java:445)
> 	at sheetapp.version2.parsing.CSVFileParser.parse(CSVFileParser.java:30)
> 	at sheetapp.version2.parsing.CSVFileSplitter.splitIntoChunks(CSVFileSplitter.java:19)
> 	at sheetapp.version2.parsing.CSVFileSplitter.main(CSVFileSplitter.java:45)
> Caused by: java.lang.NullPointerException
> 	at sheetapp.version2.parsing.CSVFileSplitter.lambda$0(CSVFileSplitter.java:26)
> 	at sheetapp.version2.parsing.CSVFileParser$CSVRowListener.processEnded(CSVFileParser.java:52)
> 	at sheetapp.version2.parsing.CSVFileParser$CSVRowListener.processEnded(CSVFileParser.java:1)
> 	at com.univocity.parsers.common.AbstractParser.stopParsing(AbstractParser.java:433)
> 	... 3 more
>

**Comment by jbax** [comment]
The exception is coming from this CSVFileSplitter: 

> sheetapp.version2.parsing.CSVFileSplitter.lambda$0(CSVFileSplitter.java:26)
