### ISSUE TITLE
Parser Re-Use and Headers?

### ISSUE THREAD

**Issue by geoffreywiseman** [uniVocity/univocity-parsers#350]
When I re-use a parser, I'm getting weird results with headers.  Basically, if I load one CSV file with a parser into a List<Record>, I can then print out the headers from the first record's metadata, and they look ok.

If I load another CSV file and print out its headers, they also look ok.

But if I go back to the first record list and print the headers, they now look like the second file -- it's as if both lists of records are sharing a single metadata instance, or if the metadata for both sets of records is sharing a single header collection that gets overwritten. Either way, it's resulting in errors.

I don't have an isolated test case, but if you can't reproduce, then I might be able to create one.

**Comment by jbax** [comment]
Thank you for reporting this bug. It's been fixed on the latest 2.8.4-SNAPSHOT build.

Thanks for using our parsers!
