### ISSUE TITLE
Unable to Parse CSV file fetched from AWS S3 bucket in Linux Server

### ISSUE THREAD

**Issue by jainneerja** [uniVocity/univocity-parsers#354]
We are trying to parse stored file from Amazon S3 bucket and it is working perfectly fine when we ran the jar from our local machine which is windows based.
However, when we run the same jar from AWS Linux server, it is unable to parse the file.
Only the first Column is parsed and others are inserted as null in database.
We have tried printing the settings which are identical and enforced encoding format but nothing seems to have work.

univocity-parsers version -2.7.6
java version-1.8
Can you please help? 

		BeanListProcessor<Report> rowProcessor = new BeanListProcessor<>(Report.class);
		rowProcessor.convertFields(Conversions.toDate("dd/MM/yyyy")).add("Start Date",
				"End Date");

		rowProcessor.convertFields(Conversions.toDate("dd/MM/yyyy HH:mm:ss")).add("DateTime (Site)",
				"DateTime (Site)");

		CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.setProcessor(rowProcessor);
		parserSettings.setHeaderExtractionEnabled(true);
		parserSettings.setSkipEmptyLines(true);
		parserSettings.setDelimiterDetectionEnabled(true);
		
	
	

		
		
		parserSettings.setProcessorErrorHandler(new RowProcessorErrorHandler() {
		    @Override
		    public void handleError(DataProcessingException error, Object[] inputRow, ParsingContext context) {
		    	log.info( "Error processing row: " + Arrays.toString(inputRow));
		    	log.info("Error details: column '" + error.getColumnName() + "' (index " + error.getColumnIndex() + ") has value '" + inputRow[error.getColumnIndex()] + "'");
		    }
		    });
		    
	
		CsvParser parser = new CsvParser(parserSettings);
		
		InputStreamReader instReader =new InputStreamReader(inputStream,Charset.forName("UTF-8"));
		
		
		instReader.getEncoding();
		
		parser.parse(instReader);****

**Comment by jbax** [comment]
Did you try with

settings.detectFormatAutomatically();

**Comment by jainneerja** [comment]
yes, we have tried that but when we use this setting it gives error in Local and on server.



Caused by: com.univocity.parsers.common.TextParsingException: Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096).
Identified line separator characters in the parsed content. This may be the cause of the error. The line separator in your parser settings is set to '\r\n'. Parsed content:   Client  ID" ,"  Series Code" ,"  Form Name" ," Registration ID" ," Registration Status" ," Registration DateTime (Site)" ," Grade" ," Score" ," Registration Method" ,"  DateTime (Site)" ," Test Center" ," Test Center " ," Scheduled Status" ,"  Start Date" ," Eligibility End D
ate" ," Candidate Last Name" ," Candidate First Name" ," Candidate Middle Initial" ," Candidate Suffix" ,"  Form Name" ,"  Series Code" ," Authorization ID" ," Authorized Attempts" ," Client Code" ,[\n]
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
        Auto configuration enabled=true
        Autodetect column delimiter=true
        Autodetect quotes=true
        Column reordering enabled=true
        Delimiters for detection=[]
        Empty value=null
        Escape unquoted values=false
        Header extraction enabled=false
        Headers=null
        Ignore leading whitespaces=true
        Ignore leading whitespaces in quotes=false
        Ignore trailing whitespaces=true
        Ignore trailing whitespaces in quotes=false
        Input buffer size=1048576
        Input reading on separate thread=true
        Keep escape sequences=false
        Keep quotes=false
        Length of content displayed on error=-1
        Line separator detection enabled=true
        Maximum number of characters per column=4096
        Maximum number of columns=512
        Normalize escaped line separators=true
        Null value=null
        Number of records to read=all
        Processor=com.univocity.parsers.common.processor.BeanListProcessor
        Restricting data in exceptions=false
        RowProcessor error handler=com.accaglobal.examentry.reconciliation.report.reader.AuthorizationStatusReportReader$1@47a86fbb
        Selected fields=none
        Skip bits as whitespace=true
        Skip empty lines=true
        Unescaped quote handling=nullFormat configuration:
        CsvFormat:
                Comment character=#
                Field delimiter=,
                Line separator (normalized)=\n
                Line separator sequence=\r\n
                Quote character="
                Quote escape character="
                Quote escape escape character=null

**Comment by jbax** [comment]
Was the format detected correctly? If yes use
settings.setMaxCharsPerColumn(-1); to allow it to parse very long fields.

**Comment by jainneerja** [comment]
Format is not being detected correctly when we use settings.detectFormatAutomatically(); , there are 4 lines before header and those are not skipped if we use these settings.
however when we ran the original code in local, it do skips those line without using this setting.

We have tried skipping 4 lines(settings.setNumberOfRowsToSkip()) as well but even then it does not detect format correctly.

Only the original code works in Local but same does not work on server.
We noticed on server that it is parsing 4 lines of CSV which does not contain header and same it does not parse in local.

**Comment by jbax** [comment]
Enable detection of the line separator only then as that is 99% the cause
of your troubles

**Comment by jainneerja** [comment]
In local it works without below settings but with below settings in server it works perfectly fine.

	settings.setLineSeparatorDetectionEnabled(false);
	settings.getFormat().setLineSeparator("\r\n");

Thank you very much for your help :)
