### ISSUE TITLE
Empty cell after each character while parsing using Univocity

### ISSUE THREAD

**Issue by hitheshkola** [uniVocity/univocity-parsers#360]
Hi, 
I am trying to parse text file using univocity parser, output contains empty cell after each character as shown in the attached file. 
<img width="1281" alt="Screen Shot 2019-11-05 at 2 00 06 PM" src="https://user-images.githubusercontent.com/57390271/68191072-ad784200-ffd4-11e9-89b9-9fd8eedd121c.png">

Second line is using opencsv parser.

**Comment by jbax** [comment]
You are clearly having trouble with the encoding here. My guess is that you are not providing it explicitly and by sheer luck OpenCsv uses a default that works for you. Make sure you are providing the correct character encoding when parsing/writing. 

If you still have issues with that please attach the actual file to be parsed so I can have a look. 
Hope this helps and thank you for using our parsers

**Comment by hitheshkola** [comment]
I used same encoding for both which is windows-1252. Attached the file.
[tmp.txt](https://github.com/uniVocity/univocity-parsers/files/3808798/tmp.txt)

**Comment by jbax** [comment]
The encoding of the file you gave me is UTF-16LE. If you try to force the encoding to be something else you will get that broken output.
