### ISSUE TITLE
CSV Annotation - Get number of columns for row

### ISSUE THREAD

**Issue by NicklasWallgren** [uniVocity/univocity-parsers#365]
It would be handy to be able to retrieve the number of columns/fields for a row.

```
@FieldCount
private int numberOfFields;
```

**Comment by jbax** [comment]
You can get that from the `ParsingContext` object that's available from within any `Processor` implementation or the parser itself.

**Comment by NicklasWallgren** [comment]
@jbax What method are you referring to in the context?

**Comment by jbax** [comment]
int currentColumn();
