### ISSUE TITLE
Using method: exception.setErrorContentLength(0) is not always enough to remove sensitive data from the exception message.

### ISSUE THREAD

**Issue by PawelPacholek** [uniVocity/univocity-parsers#367]
The problem has been noticed only for very specific kinds of TextParsingException with the following part of the message:

"Length of parsed input (...) exceeds the maximum number of characters defined in your parser settings (...). Identified line separator characters in the parsed content. This may be the cause of the error. The line separator in your parser settings is set to '[lf]'. Parsed content: **********************...."

The text just after "Parsed content:" contains sensitive data from csv rows even when method setErrorContentLength(0) has been previously executed on the exception.

The problem does not occur when method setErrorContentLength(0) is executed for initial CsvParserSettings instead.

**Comment by jbax** [comment]
Thanks! Do you have a simple unit test I could use to reproduce this specific issue?

**Comment by PawelPacholek** [comment]
Yes I do, but it is not really a unit test:
[UnitTest.txt](https://github.com/uniVocity/univocity-parsers/files/3916846/UnitTest.txt)

It uses the following csv:
[transactions_single_quote.txt](https://github.com/uniVocity/univocity-parsers/files/3916838/transactions_single_quote.txt)

Is it enough for you?

**Comment by jbax** [comment]
Works great, thank you.

You actually need to set the error content length on the parser settings:

`settings.setErrorContentLength(0);`

`exception.setErrorContentLength(0);` is used internally.

That should solve your problems. Hope it helps.

**Comment by PawelPacholek** [comment]
Hello,

Thank you for the answer. I have already considered the solution you propose and concluded that it is not fully satisfactory. The reason is that every programmer in our project would need to remember about using settings.setErrorContentLength(0); when creating new CsvParserSettings object. I prefer to set this option globally, because then programmers would not need to remember about it. I thought that setting setErrorContentLength(0); on the exception in our global exception handler is a good way to do it.

**Comment by jbax** [comment]
Maybe create a subclass of CsvParserSettings?

E.g. `public class DefaultParserSettings extends CsvParserSettings` ...

Then set the company defaults on the constructor.

Now everyone has to remember to use that class, but it's easier than
remembering individual configuration details. And you can do a full search
(new CsvParserSettings)/replace (new DefaultParserSettings) on the entire
codebase without breaking anything.

**Comment by PawelPacholek** [comment]
OK. Thanks. I think that method `exception.setErrorContentLength` should be deprecated to inform that it should not be used externally. Then, you will probably avoid issues like this one (#367).
