### ISSUE TITLE
Can we have a functionality so that all errors in a row can be collected and finally row is skipped?

### ISSUE THREAD

**Issue by rahulbagad** [uniVocity/univocity-parsers#371]
Is there any way to collect all errors in a row and skip the row finally. I am using retryableErrorHandler which on getting DataValidationException reports error and row is skipped. I want to collect all the errors and skip the row finally. The approach I was using to achieve this is parse CSV once for collecting all errors by using setDefaultValue() and keepRecord() and second time parsing will actually give me valid records. Is there any better way to achieve this?

**Comment by jbax** [comment]
Did you try ErrorHandler or RetryableErrorHandler?

**Comment by rahulbagad** [comment]
I did try both ErrorHandler and RetryableErrorHandler

**Comment by jbax** [comment]
Can you show what you need with code?

**Comment by ndLong94** [comment]
I've faced the same issue. When i do error handle, it just catch the first error in a row, and skip all the other error in that row. How can i collect all the error in a row instead?

**Comment by jbax** [comment]
@ndLong94 I really need a unit test demonstrating what you are trying to do and not being able to achieve. A description is just too vague for me to try and help.

**Comment by ndLong94** [comment]
Ah, sorry about that. I've try to upload a csv file that have 9 column. Each column have a different condition/regex to check. And i want to collect all the error when the file is uploaded successfully. For example:
Row 1: Username is invalid.
Row 1: Email is invalid.
Row 2: BirthDate is invalid.

**Comment by jbax** [comment]
Code?

**Comment by ndLong94** [comment]
val settings = CsvParserSettings()
        settings.format.setLineSeparator(System.lineSeparator())
        settings.isHeaderExtractionEnabled = true
        settings.maxColumns = 9
        settings.setProcessor(rowProcessor)
        settings.setProcessorErrorHandler { error, _, _ ->
            errorMessage.append(messageSource.getMessage(MessageResourcePath.VALIDATION_CSV_HEADER, null, Locale.JAPAN))
                    .append(error.lineIndex).append(Constant.CSV_ERROR_SEPARATOR)
                    .append(CsvColumnEnum.getByValue(error.columnIndex).message)
                    .append(System.lineSeparator())
        }
        return settings

**Comment by ndLong94** [comment]
val errorMessage = StringBuilder()
        val settings = setting(rowProcessor, errorMessage)
        val parser = CsvParser(settings)
        BufferedReader(InputStreamReader(file.inputStream)).use { reader ->
            parser.parse(reader)
            if (errorMessage.isNotEmpty()) {
                throw IllegalArgumentException(errorMessage.toString())
            }
            return rowProcessor.beans
        }

**Comment by jbax** [comment]
On your call to `setProcessorErrorHandler`, use a `RetryableErrorHandler` and call `keepRecord();`.

**Comment by ndLong94** [comment]
Thank you, it's ok for now. Cause i use Kotlin so it is difference a little bit.

**Comment by jbax** [comment]
Glad to help, thank you for using our parsers!

Please consider sponsoring this project if you find it useful.
