### ISSUE TITLE
Profiles for Parsed Annotation

### ISSUE THREAD

**Issue by alzkiria** [uniVocity/univocity-parsers#379]
Currently if you want `clean` or `simplify` columns in an existing csv file, you need to define a similar bean with different `@Parsed` annotations. For example:

```java
class BeanA {
...
    @Parsed(index = 5) Integer id
    @Parsed(index = 6) String name
...
}
```

```java
class BeanB {
    @Parsed(index = 0) Integer id
    @Parsed(index = 1) String name
}
```

it would be good to have profiles associated to parsed indices

```java
@Parsed(index = 5, profile = "import")
@Parsed(index = 0, profile = "export")
Integer id
```

with a default working for all profiles.
It would be also useful for polymorphic csv files, where the user has a limited number of optional columns + compulsory columns.

**Comment by jbax** [comment]
Did you try to use field selection on the settings object? That way you won't have to resort to messy annotations.

**Comment by alzkiria** [comment]
Yes, I was adding a custom `@CsvProfile` for that and using column selection reading the info from the annotation. It is an issue of keeping all the info about the format in the file in the same place.

**Comment by jbax** [comment]
Not going to do it as it's less flexible and more cumbersome than just selecting fields or using a `ColumnMapper`
