### ISSUE TITLE
Problem determining the quote char

### ISSUE THREAD

**Issue by bhouleupgrade** [uniVocity/univocity-parsers#384]
Given the following input data:

Input **A**:
```csv
id,date,description,amount
20108680,2019-03-07,Some description,9.18
20108680,2019-03-10,This's description,113.91
20108680,2019-03-14,"Some description, with double quotes",113.91
```

Input **B**:
```csv
id,date,description,amount
20108680,2019-03-07,Some description,9.18
20108680,2019-03-14,"Some description, with double quotes",113.91
20108680,2019-03-10,This's description,113.91
```
For pojo:
```java
public class MyPojo {
    private static final String DATE_FORMAT = "yyyy-MM-dd";

    @Parsed
    private Long id;
    @Convert(conversionClass = LocalDateConversion.class, args = { DATE_FORMAT })
    private LocalDate date;
    @Parsed
    private String description;
    @Parsed
    private Double amount;
}
```

Input **A** is failing to parse properly because the ```singleQuoteCount``` is getting greater or equals than ```doubleQuoteCount``` hence the quote char is getting set to ```39```. The problem is since double quote isn't detected properly, it consider ```with double quotes``` as the next field which is a ```Double```:
```Caused by: java.lang.NumberFormatException: For input string: "with double quotes""
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.lang.Double.valueOf(Double.java:506)
	at com.univocity.parsers.conversions.DoubleConversion.fromString(DoubleConversion.java:47)
```

With Input **B** ```doubleQuoteCount``` is getting greater or equals than ```singleQuoteCount``` hence the quote char is getting set to ```34``` which is what I was expecting 🤔 

So it looks like the row ordering have a side effect to the quote char detection.

I'm using the latest version ```2.8.4```

Thanks for your help

**Comment by jbax** [comment]
Hello there, I seems to be resolved on the latest 2.8.5-SNAPSHOT build I just generated. Can you please check it out and confirm it's working for you?

If not, can you please provide the code you are using to parse these inputs into `MyPojo`?

**Comment by Bios-Marcel** [comment]
@jbax Where would I find a snapshot? I'd like to confirm that #409 isn't already fixed.

**Comment by jbax** [comment]
Snapshot instructions detailed here:

https://www.univocity.com/pages/univocity_parsers_download

**Comment by jbax** [comment]
Closing as I got no respose and my tests are working fine
