### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by gurpal2000** [uniVocity/univocity-parsers#385]
I see some pages saying the library is crippled (batching?) if you don't use a license. Is that still true?

On StackOverflow I see a comment that it is "free" and "open source" with an "Apache 2.0 license".

Can the library (from Maven Central) be used in a commercial environment without a paid (or otherwise) license?

thanks

**Comment by jbax** [comment]
That concerns the data migration framework (univocity.jar), not univocity
parsers which is a separate project.
