### ISSUE TITLE
Make line separator OS independent 

### ISSUE THREAD

**Issue by MarkOrtmann** [uniVocity/univocity-parsers#386]
We're currently writing some code / UI that allows users to select a csv file and read it. This also means that the user has to tell us various format information, one of them being the line separator. 

Typically, CSV files use a line break separator, however this is OS dependent. To the best of my knowledge there is currently no way to tell univocity that I don't care whether it is `\n,\r\n,\r`, but I know it is line break separated. Is this correct? If so, would it be possible to add this functionality, e.g., by implementing a java.io.Reader that replaces those characters by `\n`. 

With a little guidance we could also contribute this feature,
Mark

**Comment by jbax** [comment]
Use the format or line separator autodetection for that.

**Comment by MarkOrtmann** [comment]
This is not an option for us, but thanks anyways.

**Comment by jbax** [comment]
An option here is to rewrite the file replacing all characters to use \n
only.
