### ISSUE TITLE
Questions regarding comments

### ISSUE THREAD

**Issue by MarkOrtmann** [uniVocity/univocity-parsers#387]
I have two questions regarding comments:

1. Would it be possible to have a different line separator for comments than for data rows
2. Currently a line containing the comment has to start with the comment char (here `#,)` i.e., `#this is a comment` will be recognized, however, if it contains white spaces (and or new line characters) before `#`, e.g., `   #this is also a comment` it is not considered a comment. Is this intended behavior or a bug?

Thanks for you help,
Mark

**Comment by jbax** [comment]
1 - no
2 - intended behavior
