### ISSUE TITLE
Ignore last row if it is empty

### ISSUE THREAD

**Issue by MarkOrtmann** [uniVocity/univocity-parsers#388]
If I parse the following file with line separator `;` and delimiter `,`
`A,B,C;\n`
`D,E,F;\n`
the output contains three rows with the last row being an empty String[] (note the `\n`). 

I know this is a kind of weird csv format, however, are you considering to support it, i.e., suppress the last line if its empty? The lib correctly trims the last row which is `\n`. I know that there is an option for this, however I don't think that it was introduced to resolve this issue, so it rather feels like a work around.

Thank for your help and I really want to thank you for this great library!
Mark

**Comment by jbax** [comment]
This example is a 2 line CSV. It 's NOT a 3 line CSV. The line ending
denotes the end of the record.

**Comment by MarkOrtmann** [comment]
Just for clarification reason. You say this is a two line csv, because the proper line separator is `\n` right?

**Comment by jbax** [comment]
Ok I see what you mean. Setting the line separator to ; also requires you
to to set the normalized line ending to ;

Also disable automatic trimming of white spaces.

With that you will get the 3 rows, the last one containing the \n

Sorry for the confusion I'm working on other stuff while replying to you as
fast as I can

**Comment by MarkOrtmann** [comment]
I think I'm confusing you rather than the other way around and I really appreciate your quick response.

So this is my problem. I have the following file [semicolon.zip](https://github.com/uniVocity/univocity-parsers/files/4579242/semicolon.zip) and run the following code.

`final CsvParserSettings settings = new CsvParserSettings();`
`settings..getFormat().setLineSeparator(";");`
`final CsvParser parser = new CsvParser(settings);`
`parser.beginParsing(<path to semicolon.csv>);`
`String row;`
`while((row = parser.parseNext()) != null) { System.out.println(Arrays.toString(line)); }`

Output:
`[A]`
`[B]`
`[null]`

The last entry is is actually `\n`, but due to trimming it becomes null. What I'd prefer is that the output does not contain `[null]` and that's the option I'm asking for.

Thanks for you help once more
Mark

**Comment by jbax** [comment]
Try adding this:

settings.getFormat().setNormalizedNewline('\n');

Now it won't produce that extra row with [null]. Basically this instructs
the parser to consider any \n character as a line ending, along with the
configured ';'. Note that this won't handle '\r\n'.

Hope this helps.

**Comment by MarkOrtmann** [comment]
Seems like I need to make myself more familiar with the normalized Newline option.

Btw. would auto-guessing the line separator resolve the `\r\n` issue, as you proposed in the other issue, where I asked about OS independent line breaks?

Thx again for you quick reply!
Mark

**Comment by MarkOrtmann** [comment]
Ok now I understand I little more. 

Added the following two lines before creating the parser
`settings.getFormat().setNormalizedNewline('\n');`
`settings.setSkipEmptyLines(false);`

The problem is now that when I disable skipEmptyLines it returns 1 ` String[null]` for row `A` and 2 rather than one String[null] array for the last `\n` row.
