### ISSUE TITLE
RowProcessor and external exceptions

### ISSUE THREAD

**Issue by wernerdaehn** [uniVocity/univocity-parsers#390]
I have searched now for a few hours and not found any good answer. Hence asking for some hints and suggest at the same time to add some lines about this in the tutorial - the error handling chapter.

I am reading a CSV file and loading it into a database via JDBC. Hence I extended the ObjectRowProcessor and added code in rowProcessed() and processesStarted(). What I don't understand is how to deal with SQLExceptions. Which Throwable should I throw? How to wrap the SQLException for getting the best feedback to the user?

Example 1:
In processStarted() I create the insert statement based on the context.parsedHeaders() but one column name is wrong. Hence I would like to return the information details and stop processing.

Example 2:
In rowProcessed() I execute the insert statement but it fails with an unique-key-violation. This error should be returned (so yes, will use a RowProcessorErrorHandler) and the process should continue. But if more than 20 errors happened, then I want to stop the processing immediately - no value in trying to load millions of records and get an error for each.

Would appreciate any hints!

**Comment by jbax** [comment]
Wrap your exception in a `DataProcessingException`. They will end on the error handler from where you can call `context.stop` after you count 20 errors.

Thank you for using our parsers!

**Comment by wernerdaehn** [comment]
Perfect!
