### ISSUE TITLE
NullPointerException in DefaultContext

### ISSUE THREAD

**Issue by esbakker** [uniVocity/univocity-parsers#395]
There is a bug in the DefaultContext. I found it during unit testing where I needed to mock a context:
```
@Override
public String[] headers() {
	if(headers == null) {
		if (output == null) {
			headers = ArgumentUtils.EMPTY_STRING_ARRAY;
		}
		headers = output.getHeaderAsStringArray();
	}
	return headers;
}
```
if output == null headers is set but not returned. So it will still try to get the headers from output, which is still null

**Comment by jbax** [comment]
Can you provide a unit test that reproduces the error you reported?

**Comment by jbax** [comment]
Closing as I got no response yet
