### ISSUE TITLE
Conflicting field mappings defined in annotated class

### ISSUE THREAD

**Issue by KaijuDeluxe** [uniVocity/univocity-parsers#396]
When there is a space in the header, when parsing a csv into beans i get a Conflicting field mappings defined in annotated class

for example: 

 @Parsed(field = "Image 1")
    private String image1;

**Comment by jbax** [comment]
I'm not sure I understand what's the error you are dealing with

Can you please provide a runnable unit test that I can run to reproduce the issue?

**Comment by KaijuDeluxe** [comment]
Sorry, i only got it local. But its easy to reproduct. A CSV File Column Header is named **Image 1**
with space.
When i try to read this column into a beans attribute annotated with @parsed(field = "Image 1")
the Error came up that it could not be mapped. Other columns without a space in the name are working well.

**Comment by jbax** [comment]
No errors for me:

```
public class Github_396 {

	public static class T {
		@Parsed(field = "Image 1")
		private String image1;
	}


	public static void main(String[] args) {
		for(T t : new CsvRoutines().parseAll(T.class, new StringReader("Image 1\nimg.png"))) {
			System.out.println(t.image1);
		}
	}
}

```

Will print out "img.png" as expected.

**Comment by KaijuDeluxe** [comment]
oO Thats Strange :( 
Maybe there is something in the String which is parsed. There is a URL Link to an image, but this should not be the problem i think. hm

**Comment by jbax** [comment]
Closing for now. Please reopen if you still think there's an error in the parser. Thank you!
