### ISSUE TITLE
feature needed Format based on column name 

### ISSUE THREAD

**Issue by krswin** [uniVocity/univocity-parsers#401]
Hello,

when using BeanListProcessor, I want to map 2 different column names with different format to same java property, I want to use custom formatter which can format based on my logic based on the column name from csv.

For example: 
	@Trim
	@NullString(nulls = { "-" })
	@Parsed(field = { "ABC", "ABCD" })
	private Double a;

if ABC then a = 123(in thousand)
and if ABCD then a = 123(in thousand)

Note: here ABC(Value in thousand) and ABCD(Value in millions)

Thank you.

**Comment by jbax** [comment]
Add the annotations to setter methods that will modify the internal attribute.

```
@Trim
@nullstring(nulls = { "-" })
@parsed(field = "ABC")
setAOneWay(Double a){
}

@Trim
@nullstring(nulls = { "-" })
@parsed(field = "ABCD")
setAAnotherWay(Double a){
}

```
