### ISSUE TITLE
Wrong Format detected in unquoted csv

### ISSUE THREAD

**Issue by bhoeferlin** [uniVocity/univocity-parsers#402]
Using v2.8.4 I encounter an issue with the auto format detection of "unquoted" csv files, such as https://www.yakodo.de/export/elmar.csv
It also seems that the set of potential delimiters provided to setDelimiterDetectionEnabled is just ignored in this case.
Could you have a look into that issue?

**Comment by jbax** [comment]
Can you please provide a reproducible unit test I can execute to verify this?

**Comment by jbax** [comment]
Closing as no updates provided.
