### ISSUE TITLE
Multi-char delimiter incorrectly detected inside quoted string

### ISSUE THREAD

**Issue by adutra** [uniVocity/univocity-parsers#404]
I've been playing with multi-char delimiters (thanks for the feature!!) and came across a weird corner-case:

```
CsvFormat format = new CsvFormat();
format.setDelimiter("||");
CsvParserSettings settings = new CsvParserSettings();
settings.setFormat(format);
CsvParser parser = new CsvParser(settings);
List<Record> lines = parser.parseAllRecords(new StringReader("foo||bar||\"||\"||\"foo||bar\""));
System.out.println(lines);
```

I would expect the above to print:

```
[foo, bar, ||, foo||bar]
```

But it actually prints:

```
[foo, bar, null, null, foo||bar]
```

I guess there is some ambiguity as to how to interpret `\"||\"`.

**Comment by jbax** [comment]
Thanks for reporting this one. I've fixed it and released version 2.8.5-SNAPSHOT if you want to test it to check.
