### ISSUE TITLE
Add @Parsed Annotation dynamically

### ISSUE THREAD

**Issue by KaijuDeluxe** [uniVocity/univocity-parsers#406]
I need to set the column header name in the @Parsed Annotation dynamically without touching the code.
Is that possible?

Background:
We have a bean and the software user can import Data, but must mapp his CSV to our Bean. This Mapping gets saved in DB

**Comment by jbax** [comment]
Your best bet is to use the ColumnMapper and forget annotations for that.

**Comment by KaijuDeluxe** [comment]
Ah okay, is there a Documentation? Couldnt find something to that

**Comment by jbax** [comment]
Check this out:
https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/processor/core/BeanConversionProcessor.java#L135


Sorry for the limited help I'm on mobile. For examples look for unit tests
that use this.

**Comment by jbax** [comment]
Here's what you are looking for: invoke `getColumnMapper()` from:

 * any `*Routines` class
 * any `*Bean*Processor` class (including `BeanWriterProcessor`) for writing

```
    mapper.attributeToIndex("name", 0); //name goes to the first column
    mapper.attributeToColumnName("name", "client_name"); .// same thing, but the first column has header "client_name"
```

Nested classes are also supported, you can do stuff such as the following, where `name` is buried in an object structure (assume a class Purchase with a Buyer attribute, which in turn has a Contact attribute, where the name is located:

```
    mapper.methodToIndex("buyer.contact.name", 0); 
   
    // use methods too. This assumes Contact has a `fullName(java.lang.String)` setter method:
    mapper.methodToColumnName("buyer.contact.fullName", String.class, "client_name");

    // this maps getter and setter methods named `fullName` to column `client_name`. The getters or setters are used depending if you are writing to a file or reading from it.
    mapper.methodToColumnName("buyer.contact.fullName", "client_name");
```

You can also just give it a map:

```
    Map<String, Integer> mappings = new HashMap<String, Integer>();
    ... fill your map
    mapper.attributesToIndexes(mappings);

```

Unit tests here: https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_287.java

Hope this helps. Thank you for using our parsers!

**Comment by KaijuDeluxe** [comment]
Is there a Documentation for the Mapper?
