### ISSUE TITLE
The master branch has test failures

### ISSUE THREAD

**Issue by chanduhawk** [uniVocity/univocity-parsers#410]
Hi Team

Could you please check the junits. The master branch has various test failures.

**Comment by jbax** [comment]
No errors for me.

I'm sure you are having localization related errors. If you fix them then
they will fail for me.

No quick and easy solution for that and I have zero time to look into it.

**Comment by chanduhawk** [comment]
sure, i will check again in my local.

**Comment by chanduhawk** [comment]
It turns out to be carriage return issue. In windows new line character is followed by \r (CR). But in unix it will have only \n (LF).

**Comment by jbax** [comment]
That's an issue on the unit test not the code. What tests are failing?

**Comment by chanduhawk** [comment]
correct there is no issues with the code. most of the scenarios due to carriage return. For example in the test code

@DataProvider(name = "csvProvider")
	public Object[][] csvProvider() {
		return new Object[][]{
				{"/csv/essential.csv", new char[]{'\n'}},
				{"/csv/essential-dos.csv", new char[]{'\r', '\n'}},
				{"/csv/essential-mac.csv", new char[]{'\r'}},
				{"/csv/essential.csv", null},
				{"/csv/essential-dos.csv", null},
				{"/csv/essential-mac.csv", null}
		};

in essential.csv file the new line character as '\n'. but while opening in windows its coming as '\r' '\n'. so test case will pass if we will add carriage return as below

{"/csv/essential.csv", new char[]{'\r','\n'}},

Total 43 scenarios are getting failed. few of them as below
parse3Records
Test class: com.univocity.parsers.csv.CsvWriterTest
Parameters: /csv/essential.csv

parseColumns
Test class: com.univocity.parsers.tsv.TsvParserTest
Parameters: /tsv/essential.tsv, [C@4b2bac3f

**Comment by jbax** [comment]
before I look further: I'm pretty sure your IDE or GIT changed the line endings of the input files and corresponding expected output files. Can you please check and confirm you have no changes in any of the files you got there? `/csv/essential-mac.csv` must have `/r` line endings only for example. If you see it's `/r/n` your tools tried to "help" you by normalizing everything to use the system line ending.

**Comment by chanduhawk** [comment]
/csv/essential-mac.csv has /r ending as you described. But for others i saw /r/n
![image](https://user-images.githubusercontent.com/43758960/90180299-62ddee80-ddcc-11ea-8894-167e78624076.png)
