### ISSUE TITLE
Csv parser record getString error if the selected field not present in the header

### ISSUE THREAD

**Issue by wuxiaomin98** [uniVocity/univocity-parsers#417]
Hi @jbax , I'm having a user case to **parse a csv file line by line, during the parsing, i need to transform it to an object, and write it to a text file line by line**. However, there's an issue that when the one of the fields is not present in the header, then the parse failed.

For example, we have 4 cols, but we want to parse col1, col2, col5, but col5 not present in the file/header, this cause the record.get("col5") nothing and the code can't move forward.

Sample:
col1, col2, col3, col4
a1, a2, a3, a4
b1, b2, b3, b4
c1, c2, c3, c4

        CsvParserSettings settings = new CsvParserSettings();
        settings.setHeaderExtractionEnabled(true);
        settings.selectFields("col1, col2, **col5**");

        CsvParser parser = new CsvParser(settings);
        parser.beginParsing(file, "UTF-8");
        Record record;

        while ((record = parser.parseNextRecord()) != null) {
            try {
                 String col1 = record.getString("col1");
                String col2 = record.getString("col2");
                _**String col5 = record.getString("col5");**_

               Obj obj = new Obj();
                obj.setCol1(col1);
                obj.setCol1(col1);
                obj.setCol1(col5);

               // write obj string to a buffered writer
           }

Note: we don't want to load all the data into memory, as the file size might be large.

Any suggestion on this? Thanks in advance!

**Comment by jbax** [comment]
You can overcome that by setting the header names manually:

```
    s.setHeaderExtractionEnabled(true);
    s.setHeaders("col1", "col2", "col3", "col4", "col5"); //>>> HERE, define column names manually.
    s.selectFields("col1", "col2", "col5");
```

Hope this helps.

**Comment by wuxiaomin98** [comment]
@jbax thanks for the reply. 

Actually, the header may vary for the incoming data, and we only interested in a few of them, so I can't set the headers statically. But I figured out a way to read the header and get a map, with key for the fields we're interested in, value as the index.

Again, thanks for the answer!
