### ISSUE TITLE
CsvParser appends null to each row if the CSV file has a delimiter at the end of each row.

### ISSUE THREAD

**Issue by MrcJkb** [uniVocity/univocity-parsers#418]
How to reproduce:

Given a CSV file with a semicolon as a delimiter, and n columns
And a semicolon at the end of each row
When I parse the file with a CsvParser
Expected: Then the CsvParser produces a List of String arrays of length n
Current: Then the CsvParser produces a List of String arrays of length n + 1, where element n + 1 is null.

Code example:
`CsvParserSettings settings = new CsvParserSettings();`
`settings.detectFormatAutomatically();`
`CsvParser parser = new CsvParser(settings)`
`List<String[]> rows = parser.parseAll(fileReader);`

**Comment by jbax** [comment]
That is exactly what's expected to happen and what any csv parser should
do. That last semicolon indicates there should be a value after it. If
there's nothing you'll get null

Hope this helps

**Comment by MrcJkb** [comment]
In that case, I believe it should return an empty String, rather than null, to be consistent.

**Comment by jbax** [comment]
It can, you can change what empty columns represent the parser settings. It
can also return something like "\N" if you want.

**Comment by MrcJkb** [comment]
Great! Thanks for the info!
P.S. It's an awesome library ;)
