### ISSUE TITLE
get row number

### ISSUE THREAD

**Issue by chaganiu** [uniVocity/univocity-parsers#421]
I am parsing a CSV like this:

```java
        var rowProcessor = new BeanListProcessor<>(PrintCsvData.class);

        var parserSettings = new CsvParserSettings();
        parserSettings.getFormat().setLineSeparator("\n");
        parserSettings.setProcessor(rowProcessor);
        parserSettings.setHeaderExtractionEnabled(true);

        var parser = new CsvParser(parserSettings);
        parser.parse(new FileReader(new File(csvFile).getAbsolutePath()));
        printCsvDataList = rowProcessor.getBeans();
```

I am validating data in my csv file and I when it is found, I would like to capture the row number from the CSV that it was found on.  

I noticed that when there was a parsing error, the exception printed out the row where the error occured.  is that exposed somewhere that I can get at when looping through the parsed records?

**Comment by chaganiu** [comment]
@jbax is there a way to have the processor/parser set a `rowNumber` field as part of the parsing?

**Comment by jbax** [comment]
Nope but you can set that manually from your bean processor

**Comment by chaganiu** [comment]
@jbax is there an example of how to do this?

**Comment by jbax** [comment]
BeanListProcessor<Car> carProcessor = new BeanListProcessor<Car>(Car.class){
    @Override
    public Car createBean(String[] row, Context context) {
         Car car = super.createBean(row, context);

         car.setRowNumber(context.currentRecord());
         //or
         car.setRowNumber(context.currentLine());
    }
};
