### ISSUE TITLE
The parser recognizes different separators for the same file.

### ISSUE THREAD

**Issue by HMazharHameed** [uniVocity/univocity-parsers#425]
Hi,

The parser behaves very differently if I simply add whitespace at the start of a few lines. 
For example, for the below data rows (when there are no whitespaces) the parser detects semicolon as a delimiter which is correct but simply ignores lines 1 to 5 and doesn't read these lines **( which is due to common comment keyword)**.

 #EXPORTTYPE:DATA SINGLE
 #FILE:K1-2.ngb-sdg
 #FORMAT:NETZSCH5
 #FTYPE:ANSI

 50.00000; 3.99962;-0.13861;3.36629
 51.00000; 4.19967;-0.13896;3.36607
 52.00000; 4.39964;-0.13997;3.36581
 53.00000; 4.59950;-0.14076;3.36553
 54.00000; 4.79939;-0.14102;3.36521
 55.00000; 4.99927;-0.14173;3.36487
 56.00000; 5.19921;-0.14184;3.36450
 57.00000; 5.39920;-0.14276;3.36410
 58.00000; 5.59914;-0.14318;3.36367
 59.00000; 5.79909;-0.14351;3.36321
 60.00000; 5.99904;-0.14435;3.36272
 61.00000; 6.19897;-0.14518;3.36221
 62.00000; 6.39898;-0.14574;3.36167
 63.00000; 6.59898;-0.14657;3.36110
 64.00000; 6.79890;-0.14733;3.36050
 65.00000; 6.99884;-0.14818;3.35987
 66.00000; 7.19884;-0.14929;3.35921
 67.00000; 7.39883;-0.15009;3.35853
 68.00000; 7.59882;-0.15122;3.35782
 69.00000; 7.79879;-0.15243;3.35708
 70.00000; 7.99877;-0.15332;3.35632
 71.00000; 8.19874;-0.15378;3.35553
 72.00000; 8.39869;-0.15425;3.35471
 73.00000; 8.59866;-0.15437;3.35386
 74.00000; 8.79868;-0.15466;3.35299
 75.00000; 8.99870;-0.15488;3.35209
 76.00000; 9.19867;-0.15495;3.35116
 77.00000; 9.39864;-0.15461;3.35021
 78.00000; 9.59860;-0.15450;3.34923
 79.00000; 9.79850;-0.15462;3.34822
 80.00000; 9.99847;-0.15448;3.34719

**but if I add  whitespace from lines 1 to 4 it reads these lines but detects comma as a delimiter which is not correct**
  #EXPORTTYPE:DATA SINGLE
  #FILE:K1-2.ngb-sdg
  #FORMAT:NETZSCH5
  #FTYPE:ANSI

 50.00000; 3.99962;-0.13861;3.36629
 51.00000; 4.19967;-0.13896;3.36607
 52.00000; 4.39964;-0.13997;3.36581
 53.00000; 4.59950;-0.14076;3.36553
 54.00000; 4.79939;-0.14102;3.36521
 55.00000; 4.99927;-0.14173;3.36487
 56.00000; 5.19921;-0.14184;3.36450
 57.00000; 5.39920;-0.14276;3.36410
 58.00000; 5.59914;-0.14318;3.36367
 59.00000; 5.79909;-0.14351;3.36321
 60.00000; 5.99904;-0.14435;3.36272
 61.00000; 6.19897;-0.14518;3.36221
 62.00000; 6.39898;-0.14574;3.36167
 63.00000; 6.59898;-0.14657;3.36110
 64.00000; 6.79890;-0.14733;3.36050
 65.00000; 6.99884;-0.14818;3.35987
 66.00000; 7.19884;-0.14929;3.35921
 67.00000; 7.39883;-0.15009;3.35853

**Parser setting:**

          settings.setIgnoreLeadingWhitespaces(false);
	   settings.setIgnoreTrailingWhitespaces(false);
	   settings.setKeepQuotes(true);
	   settings.setQuoteDetectionEnabled(false);
	   settings.setSkipEmptyLines(false);
	   settings.setDelimiterDetectionEnabled(true, ',', '|', ';', '\t');

**Comment by HMazharHameed** [comment]
Similar to my previous question, the parser even ignores reading rows that start with symbol #.
**The data below is the snapshot of the file I am trying to load.** 
#FORMAT      : EMSA/MAS Spectral Data File
#VERSION     : 1.0
#TITLE       : Spectrum 139
#DATE        : 19-APR-2019
#TIME        : 18:59
#OWNER       : 
#NPOINTS     : 2048.0
#NCOLUMNS    : 1.0
#XUNITS      : keV
#YUNITS      : counts
#DATATYPE    : XY
#XPERCHAN    : 0.005
#OFFSET      : -0.1
#SIGNALTYPE  : EDS
#CHOFFSET    : 20.0
#LIVETIME    : 60.026439667
#REALTIME    : 62.514938354
#BEAMKV      : 10.0
#MAGCAM      : 2000.0
#XTILTSTGE   : 0.0
#AZIMANGLE   : 0.0
#ELEVANGLE   : 35.0
#XPOSITION mm: -10.3938
#YPOSITION mm: -9.5002
#ZPOSITION mm: 6.0001
##OXINSTPT   : 4
##OXINSTSTROB: 53.24
##OXINSTELEMS: 6,8,20,38
##OXINSTLABEL: 6, 0.277, C K?1_2
##OXINSTLABEL: 8, 0.525, O K?1
##OXINSTLABEL: 20, 3.692, Ca K?1
##OXINSTLABEL: 20, 4.013, Ca K?1
##OXINSTLABEL: 20, 0.341, Ca L?1,2
##OXINSTLABEL: 20, 0.303, Ca Ll
##OXINSTLABEL: 38, 1.807, Sr L?1
##OXINSTLABEL: 38, 1.649, Sr L?
##OXINSTLABEL: 38, 1.582, Sr Ll
##OXINSTLABEL: 38, 0.114, Sr M?
#SPECTRUM    : Spectral Data Starts Here
-0.10000, 0.0
-0.09500, 0.0
-0.09000, 0.0
-0.08500, 0.0
-0.08000, 1.0
-0.07500, 2.0
-0.07000, 1.0
-0.06500, 3.0
-0.06000, 8.0
-0.05500, 13.0
-0.05000, 27.0
-0.04500, 37.0
-0.04000, 59.0
-0.03500, 99.0
-0.03000, 156.0
-0.02500, 211.0
-0.02000, 274.0
-0.01500, 369.0
-0.01000, 477.0
-0.00500, 549.0
0.00000, 638.0
0.00500, 791.0
0.01000, 894.0
0.01500, 972.0
0.02000, 1019.0
0.02500, 1135.0
0.03000, 1330.0
0.03500, 1370.0
0.04000, 1437.0
0.04500, 1477.0
0.05000, 1514.0
0.05500, 1398.0
0.06000, 1270.0
0.06500, 1167.0

**Comment by jbax** [comment]
lines starting with # are skipped by default (# is a common comment
character)

**Comment by HMazharHameed** [comment]
Thank you for your prompt reply.
But if it is part of the data and I want to keep these rows?

**Comment by HMazharHameed** [comment]
And for my first question what I understood is that parser returns comma as a delimiter whenever it didn't recognize any delimiter.
For example for the below snapshot, it detects comma as a delimiter where the correct choice would be pipe |.

Best partitioning scheme

Scheme Name       : step_47
Scheme lnL        : -351743.40782
Scheme BIC        : 708379.601495
Number of params  : 493
Number of sites   : 20425
Number of subsets : 19

Subset | Best Model | Subset Partitions              | Subset Sites                   | Alignment                               
1      | GTR+I+G    | 12S, 16S                       | 1-1087, 1088-2595              | ./analysis/phylofiles/ffa0bbe48edbae6dfed5dff0ec4c5885.phy
2      | K80+I+G    | 18S                            | 2596-4516                      | ./analysis/phylofiles/55bfa9fe21f6df07a821cc14091ac312.phy
3      | GTR+I+G    | 28S                            | 4517-6828                      | ./analysis/phylofiles/79bdcd3e84ad3fa6a0973f8b28456dc8.phy
4      | GTR+I+G    | ATP6_p1, COIII_p1, ND3_p1      | 6829-7506\3, 9961-10785\3, 14421-14777\3 | ./analysis/phylofiles/99605e5f450550a94db7bb818f5a7957.phy
5      | GTR+I+G    | ATP6_p2, COIII_p2, COII_p2, COI_p2, CytB_p2 | 6830-7506\3, 7688-9240\3, 9242-9960\3, 9962-10785\3, 10787-11956\3 | ./analysis/phylofiles/7e8aa7c86ad5e4b5665fb2cff55808d8.phy
6      | GTR+I+G    | ATP6_p3, ATP8_p3, COIII_p3, COII_p3, ND3_p3 | 6831-7506\3, 7509-7686\3, 9243-9960\3, 9963-10785\3, 14423-14777\3 | ./analysis/phylofiles/0fb72922f65c7ebceb13e5338df8c737.phy
7      | GTR+I+G    | ATP8_p1, tRNA_Arg, tRNA_Asp, tRNA_Glu, tRNA_Gly, tRNA_Leu2, tRNA_Lys, tRNA_Ser1, tRNA_Trp | 7507-7686\3, 18853-18933, 19014-19088, 19231-19303, 19304-19381, 19609-19678, 19679-19750, 19977-20050, 20199-20275 | ./analysis/phylofiles/0189cfd8b9d8a7a5cd0bd5e60914c372.phy
8      | GTR+I+G    | ATP8_p2, ND2_p1, ND6_p1, tRNA_Thr | 7508-7686\3, 13332-14420\3, 18220-18783\3, 20125-20198 | ./analysis/phylofiles/ec4df87e581100524616a6d048c073b1.phy
9      | GTR+I+G    | COI_p1                         | 7687-9240\3                    | ./analysis/phylofiles/9076cb8f0b8ebb01f0a1965d9a882bb2.phy
10     | GTR+I+G    | COI_p3, CytB_p3, ND6_p3        | 7689-9240\3, 10788-11956\3, 18222-18783\3 | ./analysis/phylofiles/6636990320bde1bb704e2d3ca38a76c5.phy
11     | GTR+I+G    | COII_p1, CytB_p1, tRNA_Met     | 9241-9960\3, 10786-11956\3, 19751-19823 | ./analysis/phylofiles/a1043f151ce3e7a0ea29a19230c97e42.phy
12     | GTR+I+G    | H3                             | 11957-12322                    | ./analysis/phylofiles/b14763210c3ab7284e9cbe731d7dc2a5.phy
13     | GTR+I+G    | ND1_p1, ND4L_p1, ND4_p1, ND5_p1 | 12323-13331\3, 14778-16125\3, 16126-16464\3, 16465-18219\3 | ./analysis/phylofiles/7c497f311c6b6309bc74918e87c77592.phy
14     | GTR+I+G    | ND1_p2, ND4L_p2, ND4_p2, ND5_p2 | 12324-13331\3, 14779-16125\3, 16127-16464\3, 16466-18219\3 | ./analysis/phylofiles/cdaca71d445e06b723a58e2957e67d21.phy
15     | GTR+G      | ND1_p3, ND4L_p3, ND4_p3, ND5_p3 | 12325-13331\3, 14780-16125\3, 16128-16464\3, 16467-18219\3 | ./analysis/phylofiles/de93ce98612d3009d38e196acef3ae98.phy
16     | GTR+I+G    | ND2_p2, ND3_p2, ND6_p2         | 13333-14420\3, 14422-14777\3, 18221-18783\3 | ./analysis/phylofiles/805696e22c342e774bd69ab95cb2f354.phy
17     | GTR+G      | ND2_p3                         | 13334-14420\3                  | ./analysis/phylofiles/76760510d66c35bf17420a289ec2b019.phy
18     | GTR+G      | tRNA_Ala, tRNA_Asn, tRNA_Cys, tRNA_Ile, tRNA_Ser2 | 18784-18852, 18934-19013, 19089-19158, 19457-19533, 20051-20124 | ./analysis/phylofiles/4f81e0a287fd4107e66f35db6ace4d61.phy
19     | GTR+I+G    | tRNA_Gln, tRNA_His, tRNA_Leu1, tRNA_Phe, tRNA_Pro, tRNA_Tyr, tRNA_Val | 19159-19230, 19382-19456, 19534-19608, 19824-19901, 19902-19976, 20276-20349, 20350-20425 | ./analysis/phylofiles/f9bc246315d4b67586acae2df8aee6c2.phy

**Comment by jbax** [comment]
ParserSettings. setCommentProcessingEnabled(false)

Will disable comment processing

**Comment by HMazharHameed** [comment]
Before I was using version 2.8.4 and now I have downloaded 2.9.0 but still this method is not showing?

**Comment by HMazharHameed** [comment]
Thank you so much for your reply. I just downloaded the latest version and now I can use this method.
Please also check the problems I asked about earlier as per your convenience.

**Comment by jbax** [comment]
The detection process does not handle inputs where there are multiple formats mixed in. For it to work, ALL lines should have the the same format. What you can do is to skip these first few lines (with `BufferedReader.readLine()` or something) until you get to the actual beginning on the CSV content. THEN, you can submit the input reader to the parser so it can detect the format.
