### ISSUE TITLE
Header duplicates

### ISSUE THREAD

**Issue by yzabudska** [uniVocity/univocity-parsers#426]
It's possible for headers to have duplicates. Even if we're talking about mapping file content on beans. For example:
```
class User {
        @Validate
        @Parsed(field = "Id")
        private String id;

        @Validate
        @Parsed(field = "Name")
        private String name;
}
```
and file content like
```
----------------------------
| Id | Name | Name | Name |
----------------------------
| 1  | Yuliia | Alex | John |
```

Using `BeanListProcessor` in this case, won't throw any exception. So, "Name" header duplicates are just ignored.

It would be really great to have smth like `.setAllowHeaderDuplicates(true)` to handle such cases.

**Comment by jbax** [comment]
With duplicate headers you should really annotate setters, so you can have this:

```
		String lines = "" +
				"| Id | Name | Name | Name |\n" +
				"| 1  | Yuliia | Alex | John|";

		StringReader stringReader = new StringReader(lines);

		CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.getFormat().setDelimiter('|');
		parserSettings.getFormat().setLineSeparator("\n");

		User user = new CsvRoutines(parserSettings).parseAll(User.class, stringReader).get(0);

		System.out.println(user.names);
```

Output:
```
[Yuliia, Alex, John]
```

**Comment by yzabudska** [comment]
@jbax yeah, but that's not what I wanted to have)

According to your example, `User.class` has not `name` field, but `names` (array) which is not valid actually. 

I meant that it would be great to throw an exception in case of mapping file' rows on an entity when headers contain duplicates. 'cause if a file contains more than one header with the same name, but cell value should be mapped on the single-value field, how do you recognize which one should be taken?

**Comment by jbax** [comment]
You can simply get the headers from the parser context and throw an
exception if there are duplicates (2 lines of code needed: add them all to
a set if set has fewer elements than list then there are duplicates)

No need to change the library for this.
