### ISSUE TITLE
How to use IterableResult with multiple beans? 

### ISSUE THREAD

**Issue by rucko24** [uniVocity/univocity-parsers#429]
Hello how are you,

https://stackoverflow.com/questions/47275132/slow-csv-row-parsing-and-splitting

I am guiding myself with several examples to read a very large file, and not load everything in memory.

I see this a bean called **MultiBeanListProcessor**.

I've been doing tests and the way I'm doing great is with **IterableResult**, the HEAP memory consumption is very low, super cool for large files, I've read up to 5 gigabytes so far.

**My real concern** is that my file will come with records of various types, that is, about 3 different beans so far, would there be any way to use the IterableResult with several beans?

always when I call getBeans () it gets loaded into memory from what I have analyzed.

**Comment by jbax** [comment]
Use a `MultiBeanProcessor` instead.

Thank you for using our parsers!

**Comment by rucko24** [comment]
Hi Jeronimo, sorry but I can't quite understand something,

I am aware that the `@Nested` annotation exists when a file contains more than one object

In my case each row will correspond to an object as such, not nested, as I understand it.

- My object one has about 80 fields

- the second about 29

- and the third about 49

I don't know how I would do to place the headers with 

```
settings.setHeaders("fields");
```
Should I mix all the headers?, now I'm ready this

 https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/common/processor/MultiBeanListProcessorTest.java

**Comment by jbax** [comment]
Can you show me a sample input and some test code that illustrates the
problem?

**Comment by rucko24** [comment]
Hi Jeronimo, the input is this:

```
	String input = "date,amount,quantity,pending,comments,active,name,identifier\n"
			+"broken,57878\n"
			+ "10-oct-2001,555.999,1,yEs,que tal?,n";
//			+ "2001-10-10,,?,N,\"  \"\" something \"\"  \",true";
```

headers is `date,amount,quantity,pending,comments,active,name,identifier`

the row with `broken,57878`  I guess I could equal the example bean **BrokenBean**
the row with `10-oct-2001,555.999,1,yEs,que tal?,n` , I guess I could equal the example bean **TestBean**

all the above example using MultiBeanProcessor, which is what I imagine to process the entire file in one go.

In the same way as I see that the api allows to do the same with both **.tsv and .txt**

**Comment by jbax** [comment]
Sorry but I need a full test class to be able to understand what your problem is. I tried to get the bits and pieces you posted and and could not make sense of anything - everything I try works for me. Please provide a simple, complete unit test that reproduces the error you are having.

**Comment by rucko24** [comment]
Hi @jbax , how are you, all the above test is almost exactly the same as my problem.

1- How would it be the correct way to set all the columns with `setHeaders()`, all the Strings corresponding to all the beans in the file?

2- The results obtained in beanProcessed, are these beans the result that I should use?

**Comment by jbax** [comment]
Almost is not exactly. I'm getting proper results so that's why I'm asking
for a full test class.

You don't have to set headers if the input has them and the classes are
mapped to the columns in that input.
