### ISSUE TITLE
Row field update not supported

### ISSUE THREAD

**Issue by Tarun275** [uniVocity/univocity-parsers#431]
Hi,
I'm now using this parser in my project, but I can't find anyway to update specific field value of given row of file, I read the tutorials, and read all constructors in the CsvWriter/TsvWriter/FixedidthParser, but can't find anyway to do this.
If I've missed any thing or the parser now not support this feature?

**Comment by jbax** [comment]
There's no way to update a row in a file without rewriting the whole thing. CSV/TSV do not work like a database.
