### ISSUE TITLE
Custom CsvFormatDetector

### ISSUE THREAD

**Issue by dmsleptsov** [uniVocity/univocity-parsers#434]
Hi guys,

I need to a little bit change the logic for defining CSV separators, but I ran into the problem of the impossibility of doing this in the current implementation of the library. In my case, I need to change the logic in the `CsvFormatDetector#execute ` method But `CsvParser` is a `final` class, moreover, the `getInputAnalysisProcess` method is also `final`. And also the `CsvFormatDetector` class is clearly not intended for extending, since most of the methods are private, which does not allow overriding only one method and using the parent methods. Tell me if there are any planned changes in the API or is there some other way to do it?

Thank you in advance!

**Comment by jbax** [comment]
Done, now you can pass your custom `InputAnalysisProcess` implementations to the parser settings. Also made the CsvFormatDetector public with protected methods if you want to override them.

I'll release a 2.9.1-SNAPSHOT build in an hour from now which you can use to test. Thank you for using our parsers!

**Comment by dmsleptsov** [comment]
Hi @jbax

How soon the new build will be? Or the build is already done, am I using the wrong repository? I use [this repo](https://repo1.maven.org/maven2/com/univocity/univocity-parsers/), but the last version still 2.9.0

Thanks

**Comment by jbax** [comment]
Snapshot releases

You download univocity-parsers SNAPSHOT builds from this link
<https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/>
.

If you use maven, all you need is to add an additional repository entry to
the *repositories* section of your pom.xml:

<repositories>
    ...
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
