### ISSUE TITLE
mapping nested beans to multiple lines in a file!

### ISSUE THREAD

**Issue by niksrivastav** [uniVocity/univocity-parsers#437]
i am working in a camel project where i have a  .DAT file from which i am trying to populate my data in my nested beans and then after some changes from populated beans i am trying to generate a file which have data present in those beans.

my POJO's are like:

```
class POJO1{
field a;
field b;
list<class POJO2>;
list<class POJO3>;
}

class POJO2{
field c;
field d;
field e;
field f;
}

class POJO3{
field g;
field h;
field i;
field j;
}
```
and my file looks like this 
```
a|b
c|d|e|f
g|h|i|k
a|b
c|d|e|f
g|h|i|k
a|b
c|d|e|f
g|h|i|k
a|b
c|d|e|f
g|h|i|k
```

which is mapped to fields of POJO's. Can you please help me to achieve this functionality.

**Comment by jbax** [comment]
Check this example:  https://github.com/uniVocity/univocity-parsers/blob/e09114c6879fa6c2c15e7365abc02cda3e193ff7/src/test/java/com/univocity/parsers/examples/CsvParserExamples.java#L664
