### ISSUE TITLE
CSV parser detects delimiter correctly, but parses the file incorrectly 

### ISSUE THREAD

**Issue by HMazharHameed** [uniVocity/univocity-parsers#440]
Hi, 

The parser recognizes the format correctly but parses all columns as one. It ignores the comma as a delimiter and recognizes the whole row as one attribute. 

**Input  Data**

Sept. 19, 2017   19:24:50
A.C. Impedance
File: c:\users\ldm\desktop\triple kill\Data Source:  Experiment
Instrument Model:  CHI660E
Header: 
Note: 

Init E (V) = 3.28
High Frequency (Hz) = 1e+5
Low Frequency (Hz) = 1
Imp SF
Amplitude (V) = 0.005
Quiet Time (sec) = 2

Freq/Hz, Z'/ohm, Z"/ohm, Z/ohm, Phase/deg

9.995e+4, 4.370e+0, -2.566e+0, 5.067e+0, -30.4
8.252e+4, 4.652e+0, -3.283e+0, 5.693e+0, -35.2
6.812e+4, 4.983e+0, -4.035e+0, 6.412e+0, -39.0
5.625e+4, 5.365e+0, -4.834e+0, 7.221e+0, -42.0
4.644e+4, 5.799e+0, -5.688e+0, 8.123e+0, -44.4
3.833e+4, 6.290e+0, -6.617e+0, 9.130e+0, -46.5
3.164e+4, 6.839e+0, -7.640e+0, 1.025e+1, -48.2
2.612e+4, 7.452e+0, -8.786e+0, 1.152e+1, -49.7
2.153e+4, 8.134e+0, -1.008e+1, 1.295e+1, -51.1
1.777e+4, 8.897e+0, -1.155e+1, 1.458e+1, -52.4
1.470e+4, 9.762e+0, -1.324e+1, 1.645e+1, -53.6
1.211e+4, 1.075e+1, -1.519e+1, 1.861e+1, -54.7
1.001e+4, 1.190e+1, -1.743e+1, 2.110e+1, -55.7
8.252e+3, 1.326e+1, -2.001e+1, 2.401e+1, -56.5
6.812e+3, 1.490e+1, -2.291e+1, 2.733e+1, -56.9
5.625e+3, 1.689e+1, -2.618e+1, 3.116e+1, -57.2
4.643e+3, 1.930e+1, -2.997e+1, 3.565e+1, -57.2
3.833e+3, 2.226e+1, -3.427e+1, 4.086e+1, -57.0
3.164e+3, 2.587e+1, -3.903e+1, 4.682e+1, -56.5
2.612e+3, 3.026e+1, -4.420e+1, 5.356e+1, -55.6
2.153e+3, 3.555e+1, -4.969e+1, 6.110e+1, -54.4
1.777e+3, 4.181e+1, -5.537e+1, 6.939e+1, -52.9
1.470e+3, 4.915e+1, -6.111e+1, 7.843e+1, -51.2
1.211e+3, 5.760e+1, -6.674e+1, 8.816e+1, -49.2
1.001e+3, 6.719e+1, -7.199e+1, 9.847e+1, -47.0
8.252e+2, 7.776e+1, -7.669e+1, 1.092e+2, -44.6
6.836e+2, 8.920e+1, -8.077e+1, 1.203e+2, -42.2
5.615e+2, 1.014e+2, -8.409e+1, 1.317e+2, -39.7
4.639e+2, 1.142e+2, -8.650e+1, 1.433e+2, -37.1
3.809e+2, 1.272e+2, -8.795e+1, 1.546e+2, -34.7
3.174e+2, 1.403e+2, -8.840e+1, 1.658e+2, -32.2
2.588e+2, 1.534e+2, -8.787e+1, 1.768e+2, -29.8
2.148e+2, 1.662e+2, -8.642e+1, 1.873e+2, -27.5
1.758e+2, 1.786e+2, -8.422e+1, 1.974e+2, -25.3
1.465e+2, 1.901e+2, -8.138e+1, 2.068e+2, -23.2
1.221e+2, 2.014e+2, -7.761e+1, 2.158e+2, -21.1
9.766e+1, 2.121e+2, -7.277e+1, 2.242e+2, -18.9
8.254e+1, 2.216e+2, -6.765e+1, 2.317e+2, -17.0
6.813e+1, 2.302e+2, -6.291e+1, 2.386e+2, -15.3
5.623e+1, 2.374e+2, -5.859e+1, 2.445e+2, -13.9
4.642e+1, 2.438e+2, -5.467e+1, 2.498e+2, -12.6
3.831e+1, 2.495e+2, -5.110e+1, 2.547e+2, -11.6
3.162e+1, 2.546e+2, -4.792e+1, 2.591e+2, -10.7
2.610e+1, 2.592e+2, -4.516e+1, 2.631e+2, -9.9
2.154e+1, 2.633e+2, -4.293e+1, 2.668e+2, -9.3
1.778e+1, 2.671e+2, -4.134e+1, 2.703e+2, -8.8
1.468e+1, 2.706e+2, -4.036e+1, 2.736e+2, -8.5
1.212e+1, 2.738e+2, -4.001e+1, 2.767e+2, -8.3
1.000e+1, 2.770e+2, -4.014e+1, 2.798e+2, -8.2
8.254e+0, 2.802e+2, -4.090e+1, 2.831e+2, -8.3
6.813e+0, 2.834e+2, -4.254e+1, 2.866e+2, -8.5
5.623e+0, 2.868e+2, -4.512e+1, 2.904e+2, -8.9
4.642e+0, 2.906e+2, -4.870e+1, 2.947e+2, -9.5
3.831e+0, 2.946e+2, -5.331e+1, 2.994e+2, -10.3
3.162e+0, 2.993e+2, -5.908e+1, 3.051e+2, -11.2
2.610e+0, 3.046e+2, -6.620e+1, 3.117e+2, -12.3
2.154e+0, 3.120e+2, -7.525e+1, 3.210e+2, -13.6
1.778e+0, 3.214e+2, -8.656e+1, 3.329e+2, -15.1
1.468e+0, 3.306e+2, -1.001e+2, 3.454e+2, -16.8
1.212e+0, 3.394e+2, -1.161e+2, 3.587e+2, -18.9
1.000e+0, 3.476e+2, -1.347e+2, 3.728e+2, -21.2

**Parser Settings** 
settings.setIgnoreLeadingWhitespaces(false);
	   settings.setIgnoreTrailingWhitespaces(false);
	   settings.setKeepQuotes(true);
	   settings.setQuoteDetectionEnabled(false);
	   settings.setSkipEmptyLines(false);
	   settings.setCommentProcessingEnabled(false);
	   settings.setDelimiterDetectionEnabled(true, ',', '|', ';',':','\t');

**Comment by jbax** [comment]
How are you parsing this exactly? When I run with this it works fine:

```
		CsvParserSettings settings = new CsvParserSettings();
		settings.setIgnoreLeadingWhitespaces(false);
		settings.setIgnoreTrailingWhitespaces(false);
		settings.setKeepQuotes(true);
		settings.setQuoteDetectionEnabled(false);
		settings.setSkipEmptyLines(false);
		settings.setCommentProcessingEnabled(false);
		settings.setDelimiterDetectionEnabled(true, ',', '|', ';',':','\t');
		CsvParser csvParser = new CsvParser(settings);

		List<String[]> rows = csvParser.parseAll(new StringReader(input));
		for(String[] row : rows){
			System.out.println(row.length + " | " + Arrays.toString(row));
		}
```

**Comment by HMazharHameed** [comment]
Hi,
I am using the same parser setting. 

List<Record> allRecords = parser.parseAllRecords(new File("path"));
 for(Record record : allRecords){
    String[] values = record.getValues();
     for(String value : values){
     System.out.println(value);
     }
 }

**Comment by jbax** [comment]
Can you try it with the 2.9.1 snapshot version?

**Comment by HMazharHameed** [comment]
I am already using 2.9.1 December snapshot.

**Comment by HMazharHameed** [comment]
Hi,

Since this thread is open, I'm posting here instead of opening new issues. But if you prefer a new issue, I will open a new issue next time.

The line below is from the file I am trying to parse. 

**1102,""3,947"",""1,444"",416,""2,087""** 

**The parser output is:**
column value 1102
delimiter  ,
column value  ""3
delimiter    ,
column value  947"" 
and so on for the next values. 

When I change these values with pair of double-quote characters to escape quote it works fine 
**1102,"""3,947""","""1,444""",416,"""2,087"""**

My question is if there is a way to parse this file without using a pair of double quotes for quoteEscape. 

P.S. I have already read the Univocity documentation for quoteEscape and know the CSV standard. I just wanted to know if we can parse such files using the existing version. 


**Parser Settings**
settings.setIgnoreLeadingWhitespaces(false);
settings.setIgnoreTrailingWhitespaces(false);
settings.setKeepQuotes(true);
settings.setQuoteDetectionEnabled(false);
settings.setSkipEmptyLines(false);
settings.setCommentProcessingEnabled(false);
settings.setDelimiterDetectionEnabled(true, ',', '|', ';',':','\t');

**Comment by jbax** [comment]
For your example, `""3,947""` uses unescaped quotes. That's not going to work because that parser is looking for a double quotes inside quoted field. `"""3,947"""` is proper way to escape these quotes around 3,947 (first quote indicates quoted value, second and third quotes represent a single quote character inside that quoted value)
