### ISSUE TITLE
Parse tab separated file using CSV parser ?

### ISSUE THREAD

**Issue by HMazharHameed** [uniVocity/univocity-parsers#441]
Hi,
I have used the CSV parser to parse a file with a tab as an attribute separator. The parser just ignores the delimiter (\t) and reads the whole record as an attribute. 
I was wondering if there is a special command to use the CSV parser for tab-delimited files.

 **Parser setting** 
  settings.setIgnoreLeadingWhitespaces(false);
   settings.setIgnoreTrailingWhitespaces(false);
   settings.setKeepQuotes(true);
   settings.setQuoteDetectionEnabled(false);
   settings.setSkipEmptyLines(false);
   settings.setDelimiterDetectionEnabled(true, ',', '|', ';', '\t');

**Sample Input**
ID    Species     Camera_Site Camera_Site_Latitude    Camera_Site_Longitude   Species_Name_Common     Date  Time
C_477 monkey2     BCI-1-15    9.14395     -79.85052   Capuchin_monkey   16/02/16    11:58
C_478 monkey2     BCI-1-20    9.15627     -79.85049   Capuchin_monkey   13/07/16    10:18
C_479 monkey2     BCI-1-22    9.15676     -79.82481   Capuchin_monkey   11/05/16    11:49
C_480 monkey2     BCI-1-25    9.16901     -79.85085   Capuchin_monkey   27/04/16    11:17
C_481 monkey2     BCI-1-26    9.16912     -79.83784   Capuchin_monkey   19/04/16    9:49                
C_482 monkey2     BCI-3-01    9.17558     -79.84417   Capuchin_monkey   20/10/16    15:08
C_483 monkey2     BCI-3-02    9.16931     -79.85724   Capuchin_monkey   12/11/15    15:45
C_484 monkey2     BCI-3-03    9.16918     -79.84422   Capuchin_monkey   03/03/16    11:19
C_485 monkey2     BCI-3-06    9.16273     -79.85081   Capuchin_monkey   18/03/16    11:09                               
C_486 monkey2     BCI-3-06    9.16273     -79.85081   Capuchin_monkey   06/04/16    13:49
C_487 monkey2     BCI-3-07    9.16276     -79.84415   Capuchin_monkey   14/11/15    12:34
C_488 monkey2     BCI-3-09    9.16257     -79.83144   Capuchin_monkey   19/10/16    12:05
C_489 monkey2     BCI-3-09    9.16257     -79.83144   Capuchin_monkey   25/10/16    8:49
C_490 monkey2     BCI-3-09    9.16257     -79.83144   Capuchin_monkey   14/11/16    12:10
C_491 monkey2     BCI-3-09    9.16257     -79.83144   Capuchin_monkey   18/11/16    13:19
C_492 monkey2     BCI-3-13    9.15621     -79.83135   Capuchin_monkey   13/11/15    10:14
C_493 monkey2     BCI-3-13    9.15621     -79.83135   Capuchin_monkey   15/02/16    10:28
C_494 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   03/07/16    10:52
C_495 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   17/06/16    11:24
C_496 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   21/06/16    13:10
C_497 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   21/06/16    13:18
C_498 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   21/06/16    13:23
C_499 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   21/06/16    13:30
C_500 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   22/06/16    9:14
C_501 monkey2     BCI-3-14    9.15001     -79.86361   Capuchin_monkey   22/06/16    9:21

It is clearly a tab-separated file, but the parser returns "comma" as the detected delimiter which is the first one in the setting ',' even though it doesn't actually appear in the file. But after changing settings to **settings.setDelimiterDetectionEnabled(true, '\t');** it doesn't return comma as a detected delimiter but still reads complete record as one single attribute.

**Comment by HMazharHameed** [comment]
Another Example:

**Sample Input** 

ID\tName\tSex\tAge\tHeight\tWeight\tTeam\tGames\tCity\tSports
1\tDijiang\tM\t24\t180\t80\tChina\t1992 Summer\tBarcelona\tBasketball
4\tEdgar Lindenau Aabye\tM\t34\t170\t76\tDenmark/Sweden\t1900 Summer\tParis\tTug Of War
5\tPaavo Johannes Aaltonen\tM\t28\t175\t64\tFinland\t1948 Summer\tLondon\tGymnastics
6\tPer Knut Aaland\tM\t31\t188\t75\tUnited States\t1992 Winter\tAlbertville\tCross Country Skiing
7\tJohn Aalberg\tM\t33\t183\t72\tUnited States\t1994 Winter\tLillehammer\tCross Country Skiing
8\tCornelia\tF\t18\t168\t76\tNetherlands\t1932 Summer\tLos Angeles\tAthletics
9\tAntti Sami Aalto\tM\t26\t186\t96\tFinland\t2002 Winter\tSalt Lake City\tIce Hockey
10\tEinar Ferdinand Aalto\tM\t26\tNA\tNA\tFinland\t1952 Summer\tHelsinki\tSwimming
11\tJorma Ilmari Aalto\tM\t22\t182\t176.37\tFinland\t1980 Winter\tLake Placid\tCross Country Skiing
20\tKjetil Andr Aamodt\tM\t30\t176\t85\tNorway\t2002 Winter\tSalt Lake City\tAlpine Skiing
21\tRagnhild Margrethe Aamodt\tF\t27\t163\t75\tNorway\t2008 Summer\tBeijing\tHandball
22\tAndreea Aanei\tF\t22\t170\t90\tRomania\t2016 Summer\tRio de Janeiro\tWeightlifting
23\tFritz Aanes\tM\t22\t187\t89\tNorway\t2000 Summer\tSydney\tWrestling
36\tStefan Remco Aartsen\tM\t21\t194\t78\tNetherlands\t1996 Summer\tAtlanta\tSwimming
37\tAnn Kristin Aarnes\tF\t23\t182\t64\tNorway\t1996 Summer\tAtlanta\tFootball
40\tAnna Edgar \tF\t31\t170\t61\tNorway\t1960 Winter\tSquaw Valley\tSpeed Skating
53\tTalaat Abada\tM\t24\t5.10\t58\tEgypt\t2000 Summer\tSydney\tTaekwondo
84\tStephen Anthony Abas\tM\t26\t165\t55\tUnited States\t2004 Summer\t30601\tWrestling
85\tAlejandro Abascal Garca\tM\t28\t181\t82\tSpain\tESP\t1980 Summer\t1980

**Parser Setting** 
           settings.setIgnoreLeadingWhitespaces(false);
	   settings.setIgnoreTrailingWhitespaces(false);
	   settings.setKeepQuotes(true);
	   settings.setQuoteDetectionEnabled(false);
	   settings.setSkipEmptyLines(false);
	   settings.setCommentProcessingEnabled(false);
	   settings.setDelimiterDetectionEnabled(true, '\t',';','|',':',',');
	   
The Parser doesn't recognize the right delimiter and returns the whole record as one attribute. But if I change **settings.setDelimiterDetectionEnabled(true, '\t',';','|',':',',');** to **settings.getFormat().setDelimiter('\t');**
The parser recognize **'\'** as delimiter instead of tab.

**Comment by jbax** [comment]
This one also works fine for me using the following snippet (I had to convert all spaces the input you pasted to tabs):

```
                CsvParserSettings settings = new CsvParserSettings();
		settings.setIgnoreLeadingWhitespaces(false);
		settings.setIgnoreTrailingWhitespaces(false);
		settings.setKeepQuotes(true);
		settings.setQuoteDetectionEnabled(false);
		settings.setSkipEmptyLines(false);
		settings.setCommentProcessingEnabled(false);
		settings.setDelimiterDetectionEnabled(true, '\t',';','|',':',',');
		CsvParser csvParser = new CsvParser(settings);

		List<String[]> rows = csvParser.parseAll(new StringReader(input));
		for(String[] row : rows){
			System.out.println(row.length + " | " + Arrays.toString(row));
		}
```

**Comment by HMazharHameed** [comment]
Actually, my question was if there is a special method for the tab delimited file, but I found my answer. I'm still having problems, but I'll look at them myself first and then ask for more help if needed.

**Comment by jbax** [comment]
closing. If anything else pops up please open a new issue
