### ISSUE TITLE
Error in combination with quoted cells that contain escaped quotes and end on a non alphanummeric character with a trailing tab behind the last quote

### ISSUE THREAD

**Issue by Bios-Marcel** [uniVocity/univocity-parsers#444]
Hey,

I've found a rather mysterious bug that seems to split a single row into multiple rows, causing data that's basically not usable anymore. I've narrowed it down to a specific constelation of characters.

I've got the following input that is being parsed correctly:

```
"""quoted""
G"	
```

**NOTE THE TRAILING TAB!**

This produces two rows with two cells containing `"quoted"\nG` and one empty cell, which is the expected result.

However, if we try to parse the sama data with a slight change, the whole result is different:

```
"""quoted""
)"	
```

Here the `G` is swapped out with a non alphanummeric character, in this case `)`, but any will do.
Now the result is two rows with one cell each, e.g:

```
[["quoted"], [)"]]
```

Expected would have been:

```
[["quoted"\n)]]
```

Like said, to reproduce this, you need a quoted cell, that contains a word with escaped quotes and the cell ending on a non alphanummeric character and a trailing tab after the cell.

The code used to test this:

```java
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import com.univocity.parsers.common.ParsingContext;
import com.univocity.parsers.common.processor.AbstractRowProcessor;
import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;

public class CSV
{
  public static void main( final String[] args ) throws IOException
  {
    final String stringData = new String( Files.readAllBytes( Paths.get( "D:\\data.csv" ) ) );
    final String[][] data = parseCSV( stringData );
    System.out.println( data );
  }

  private static String[][] parseCSV( final String rawData )
  {
    final List<String[]> rows = new ArrayList<>();
    final CsvParserSettings settings = new CsvParserSettings();
    settings.detectFormatAutomatically( '\t', ';', ',' );
    settings.setIgnoreLeadingWhitespaces( false );
    settings.setIgnoreTrailingWhitespaces( false );
    settings.setSkipEmptyLines( false );

    //Ansonsten sind leere Zeilen null-values und führen zu Fehlern.
    settings.setNullValue( "" );

    settings.setProcessor( new AbstractRowProcessor()
    {
      @Override
      public void rowProcessed( final String[] row, final ParsingContext __ )
      {
        if ( row != null )
        {
          rows.add( row );
        }
      }
    } );

    final CsvParser parser = new CsvParser( settings );
    try ( StringReader reader = new StringReader( rawData ) )
    {
      parser.parse( reader );
    }
    return rows.toArray( new String[rows.size()][] );
  }
}
```

We are using version `2.9.1` which is the latest as of today. This bug already existed in version `2.9.0`.

**Comment by jbax** [comment]
Thank you for reporting this. That was caused by an incorrect detection of the quote escape character. The parser would identify ')' as the quote escape in your test. I've fixed and generated a 2.9.2-SNAPSHOT build with the adjusment.

**Comment by Bios-Marcel** [comment]
Thanks, will test this on wednesday (*Whenever i get to go to work again) :+1:

**Comment by Bios-Marcel** [comment]
It seems you've made a tiny typo when uploading the snapshot. It's `SNAPSOHT` instead of `SNAPSHOT`, therefore maven doesn't know that it actually has to access the snapshot repo and we can't get it at all.

Found it out here: https://oss.sonatype.org/#nexus-search;gav~com.univocity~univocity-parsers~2.9.2-SNAPSOHT~~

**Comment by Bios-Marcel** [comment]
Made a PR: https://github.com/uniVocity/univocity-parsers/pull/459
