### ISSUE TITLE
Unable to read empty commented line

### ISSUE THREAD

**Issue by Tarun275** [uniVocity/univocity-parsers#447]
Try to collect  comments from below content. All empty comment lines will get ignored. Tried with all possible configuration.
        
**content:**

\#
\# underscores are used as the padding character, so leading/trailing whitespace can be considered part of the value
\#  
\#4&nbsp;&nbsp;&nbsp;&nbsp;5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;40&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;									     40&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8

        parserSettings.setCommentCollectionEnabled(true);
        parserSettings.getFormat().setComment('#');
        parserSettings.getFormat().setNormalizedNewline('\n');
        parserSettings.getFormat().setLineSeparator("\n");
        parserSettings.setHeaderExtractionEnabled(true);

**fixedWidthParser.getContext().comments()** - returns line 2 and 4 only.  Line 1 and 3 will get ignored.

**Comment by jbax** [comment]
Added an extra flag to `setCommentCollectionEnabled` now `setCommentCollectionEnabled(true, true)` will return blank comment lines as `null`.

I've released a 2.9.2-SNAPSHOT build with this enhancement. Hope this helps
