### ISSUE TITLE
Add support for inherited fields

### ISSUE THREAD

**Issue by manish-in-java** [uniVocity/univocity-parsers#45]
I have a class hierarchy such as the following:

```
abstract class Named {
  @Parsed(field = "Code")
  private String code;
  @Parsed(field = "Name")
  private String name;
}

class Department extends Named {}

class Employee extends Named {}
```

When I use `BeanListProcessor` with a `CsvParser`, the parser fails to read both the fields from the parent class (`Named`).  I can see that this is because of the line `Field[] declared = clazz.getDeclaredFields();` in the `initialize` method of the `BeanConversionProcessor` class.  Due to this line, the CSV parsing code only considers fields declared immediately inside the class being parsed.

I am not sure if this is intended.  I certainly feel this behaviour is incorrect as we cannot use class inheritance if inherited fields cannot be read by the parser.

Is there a way to read inherited fields?  If not, can this be added?

**Comment by jbax** [comment]
Inherited methods work. Try the following example:

```
public class Github_45 {

	public static abstract class Named {
		@Parsed(field = "Code")
		private String code;
		@Parsed(field = "Name")
		private String name;

		public Named(){

		}

		public String toString(){
			return code + ": " + name;
		}
	}

	public static class Department extends Named {}

	public static class Employee extends Named {}

	public static void main(String ... args){
		CsvParserSettings settings = new CsvParserSettings();
		BeanListProcessor<Employee> list = new BeanListProcessor<Employee>(Employee.class);
		settings.setRowProcessor(list);

		CsvParser parser = new CsvParser(settings);
		parser.parse(new StringReader("Code,Name\nA,B\nC,D"));

		for(Employee e : list.getBeans()){
			System.out.println(e);
		}
	}
}
```

You are having trouble because your classes are not public and the parser can't instantiate them.

**Comment by manish-in-java** [comment]
Jeronimo, thanks for your prompt reply.  I took your sample, copied it to a file and ran the code.  I got:

```
null: null
null: null
null: null
```

As for my original code, I had only provided a quick sample, not the actual classes.  Actual classes are all public.  You can download the full sample project from [http://www.filedropper.com/csv-mapping_1](http://www.filedropper.com/csv-mapping_1) and run it with Maven as `mvn clean test`.  You will find that the tests fail with the latest version (1.5.6) as well as the one I am using (1.4.0).  I am running these on a Windows 7 Professional, 64-bit machine (if that matters).

**Comment by manish-in-java** [comment]
See [line 75 in BeanConversionProcessor](https://github.com/uniVocity/univocity-parsers/blob/v1.5.6/src/main/java/com/univocity/parsers/common/processor/BeanConversionProcessor.java#L75) in release 1.5.6 and compare it with the code on the `master` branch.  On the `master`, the code attempts to go up the class hierarchy looking for fields to parse, whereas it doesn't do that in release 1.5.6.

That explains why the released code does not pick up inherited fields.  Most likely, your sample must have been run against the `master`, which is why it would have succeeded.

**Comment by jbax** [comment]
Thanks Manish. You are correct. Use version 2.0.0-SNAPSHOT to get this fixed. We'll release the final 2.0.0 version within a month or so.

**Comment by manish-in-java** [comment]
Cool, I am grateful for having stumbled across this library.  I am using it in a web app that supports uploading .xls and .csv files.  The difference in performance between .xls and .csv parsing is absolutely mind-blowing, and our advanced users who upload .csv files are patently thrilled.

Is it possible for you to release an intermediate version (may be 1.5.7) with just this fix?  Our CSV upload feature is currently in limited beta and users are baying to release it across the application.  Getting a fix will allow us to release CSV uploads to a wider audience.

**Comment by jbax** [comment]
For more immediate needs, we offer [paid support](http://www.univocity.com/products/parsers-support) and will take care of your problem straight away.

**Comment by manish-in-java** [comment]
Jeronimo, do you have a release date for 2.0.0?

**Comment by jbax** [comment]
Will be around January, 2016.
