### ISSUE TITLE
TsvParser skips lines which start with #

### ISSUE THREAD

**Issue by robeeeert** [uniVocity/univocity-parsers#47]
When reading a tsv file with the TsvParser it somehow cannot handle lines which start with the # character. We compared the results of the parser with the results of a simple line-wise reading with a FileReader in a BufferedReader. While the BufferedReader list of line contained all lines from the file, the list created by the parseAll method of the TsvParser did not contain an entry for those lines.

**Comment by jbax** [comment]
It's because by default it skips lines starting with #, This is by default used to indicate a comment line in the file. Change the format settings to use '\0' instead and your are golden

**Comment by dklesev** [comment]
you're extremely quick with your response...

**Comment by jbax** [comment]
Thanks. We monitor issues here daily. Guess why you don't see bugs open in this project for more than 24h?
