### ISSUE TITLE
question: is there a method to detect if a csv file contains header, like python csv.has_header() ?

### ISSUE THREAD

**Issue by csimplestring** [uniVocity/univocity-parsers#480]
Hi, thanks for this amazing parser.

Recently I need to find a way to detect if a csv file contains the header in the first row. I googled a bit and all the answers suggests using Python's csv.has_header(). If there is an existing solution in this package? 

I notice I can set 
```
        CsvParserSettings settings = new CsvParserSettings();
        settings.setHeaderExtractionEnabled(true);

        parser.getContext().headers();
```
but it can not decide if the first row is the header.

Thanks in advance.

**Comment by randy** [comment]
Technically, a CSV is still a CSV without a header row. I'm not going to get into the "standards" discussion here, but suffice it to say, I think the answer is: that's impossible for the library to determine. You'd have to parse the first row and look at that record's contents to determine if headers were provided or not. Which, by the way, you're halfway there in your example. Inspecting the contents of `parser.getContext().header()` should do the trick.

Personally, I think it should be clear to your user that headers have to be included if that's the assumption you're writing the code under. If you "just won't know" until you receive the data, your best bet is checking that first row and going from there.

**Comment by csimplestring** [comment]
Alright, thanks for replying!
