### ISSUE TITLE
null parsing results with leading `#` on FixedWidthParser

### ISSUE THREAD

**Issue by rmalleman** [uniVocity/univocity-parsers#493]
FixedWidthParser.parseLine() is returning a null when there is a leading `#` on the line.  This doesn't seem like intended behavior and I couldnt find anything in FixedWidthParserSettings that looks like it would fix it.  Here is some scala code to reproduce it

```
    val fixedWidthFields = new FixedWidthFields(4)
    val parserSetting = new FixedWidthParserSettings(fixedWidthFields)
    val parsedLine = parser.parseLine("#ABC")
   assert(parsedLine == null)
```

**Comment by battmush** [comment]
It looks like it's treating the line as a comment.  You can change the parser behavior by setting `parserSetting.setCommentProcessingEnabled(false)`

**Comment by rmalleman** [comment]
You're right, that did the trick.  Still seems like strange behavior to return `null`, but that could be my scala bias showing.
