### ISSUE TITLE
Allow fields parsed by BeanListProcessor to be marked as optional

### ISSUE THREAD

**Issue by manish-in-java** [uniVocity/univocity-parsers#50]
If a field in a Java class is annotated with `@Parsed` but does not have a corresponding column in the CSV file, `BeanListProcessor` fails with the exception:

> com.univocity.parsers.common.TextParsingException: Error processing input: java.lang.IllegalStateException - Could not find field with name

We have an existing code base where the same Java class is used to read information for multiple similar entity types and this error is causing problems when the user provides CSV files that do not have columns corresponding to all the fields in the Java class.

It will be useful to mark a field as optional so that the parser does not raise an exception if the CSV field does not contain a column corresponding to the field.  The easiest option would be to annotate the field as `@Parsed(optional = true)`.

**Comment by jbax** [comment]
Thank you! A [similar issue](https://github.com/uniVocity/univocity-parsers/issues/48)  has been recently closed and if you grab univocity-parsers 2.0.0-SNAPSHOT this should not bother you anymore.

Currently, we are making the parser handle the input irrespective of whether or not the input columns are present. This way you won't be required to explicitly set an `optional` flag on every field (this can get annoying in classes with lots of attributes).

Give version 2.0.0-SNAPSHOT a spin and let me know if it solves your case in particular (or not).

**Comment by manish-in-java** [comment]
I compiled a JAR from the master branch (`2.0.0-SNAPSHOT`) and used it with my app but am still getting a similar error if a particular field is not present in the CSV file:

> Caused by: java.lang.IllegalStateException: Unknown field names

It will still be desirable to have control over when a field is treated as optional or mandatory.  I can see that Issue #24 was raised to have a clear notification if a CSV file does not contain all the columns.  This would be a valid use case in many scenarios (for us as well) and should therefore be supported.

**Comment by jbax** [comment]
Well, it should work. Can you send an example of input and code so we can reproduce this?

If you want to make fields mandatory, so it works as before, just do this:

`beanProcessor.setStrictHeaderValidationEnabled(true);`

And it will behave as expected.

**Comment by jbax** [comment]
Also, refer to [this test case](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_24.java).

**Comment by manish-in-java** [comment]
A sample project can be downloaded from [http://www.filedropper.com/csv-mapping](http://www.filedropper.com/csv-mapping).  Running the test cases as `mvn clean test` leads to a build failure.

**Comment by jbax** [comment]
Thank you! The issue has been fixed. I removed the unnecessary validation that was triggering the error.

A new 2.0.0-SNAPSHOT version has been built to include this fix.
