### ISSUE TITLE
Using multiple field delimiters with BeanListProcessor

### ISSUE THREAD

**Issue by manish-in-java** [uniVocity/univocity-parsers#51]
Our users insist on using any one of `,`, `;`, `|`, `#` and tabs as the delimiting character for text files.  This creates a problem for us when using a Univocity CSV parser because the parser accepts only one delimiter at a time (`CsvParserSettings.getFormat().setDelimiter(...)`).

Is there a way to instruct the parser to use any one out of multiple characters as the delimiter by examining the file?

**Comment by jbax** [comment]
No because this can be really problematic in terms of escaping characters and extract data correctly.

We have no plans to add support for this but we can do it if you are happy to pay us to build this under the [feature request]( http://www.univocity.com/products/parsers-support) support option. If you want to go that route send an e-mail to us: support@univocity.com

**Comment by jbax** [comment]
By the way, version 2.0.0 supports auto-detection of the delimiter. If your users are sending files where any of these delimiters is used (but not multiple delimiters in the same file), then do this:

    csvParserSettings.detectFormatAutomatically();

**Comment by manish-in-java** [comment]
Yes, a single file uses only one delimiter.  I will give this option a try as it will simplify my code greatly.  Currently I am using a chain of CSV parsers, each with its own delimiter and giving up only if none of them is able to parse the incoming files.  This suffers from the problem of having to try out all parsers for bad files as well.

Will give this a try with 2.0.0 JARs.

**Comment by danielvdende** [comment]
I'm interested in helping out with this. Would you be interested if I worked on adding support for multiple delimiters within a single file?

**Comment by jbax** [comment]
Thanks for helping out, but I think the original issue has been addressed: detecting what delimiter is being used in a given file. Feel free to submit a PR to add support for parsing multiple delimiters within a single file, just be conscious about the performance impact of any changes. Cheers!
