### ISSUE TITLE
Invalid ParsingContext#currentLine() for the last line

### ISSUE THREAD

**Issue by vojtechsoban** [uniVocity/univocity-parsers#52]
It happens when the file has no new line at the end. ParsingContext#currentLine() returns n-1 where n is actual number of lines.

**Comment by jbax** [comment]
Thanks for reporting the issue. I've just fixed it and released another 2.0.0-SNAPSHOT build you can already use and test. 

For reference, and to prevent this problem won't come back in the future, I also created [this test case](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_52.java).

**Comment by vojtechsoban** [comment]
Thanks for fixing the issue. I've tested our code with 2.0.0-SNAPSHOT and it works perfectly. Just to make sure, wouldn't be better to extend your test with MAC endline?

**Comment by jbax** [comment]
For this test it doesn't really matter what line ending is used. It could be any character configured in the format settings (\r, \t, *, %, etc). The test ensures the configured line ending, with one or two characters, is handled.
