### ISSUE TITLE
Release of master source code

### ISSUE THREAD

**Issue by sshelake** [uniVocity/univocity-parsers#55]
Hi
There are few fixes such as 'accessing Super class fields in bean conversion', 'Ignoring Parsed annotation if header not specified' are fixed in Master source but not yet released.
Is it possible for you to release next version and by when?

**Comment by jbax** [comment]
Just use the 2.0.0-SNAPSHOT builds that are being released every time a new feature or adjustment is introduced in the master branch. There's a lot of new stuff that needs to be documented, and a few more features to come.

You should be all right with the SNAPSHOT builds for the time being as it's pretty stable.

We are planning to release the final 2.0.0 version in January.

**Comment by sshelake** [comment]
Thanks for update, I am using 2.0.0-SNAPSHOT and all issues are resolved in new build.
