### ISSUE TITLE
Way to get a single Bean from a single parsed line?

### ISSUE THREAD

**Issue by racc** [uniVocity/univocity-parsers#56]
It is possible to return a single parsed String[] via AbstractParser.parseLine(String str) for a single line input.

BeanListProcessor provides List<Bean> getBeans() for multiple parsed lines.

Is there a way to return a single Bean from a single parsed line?
Perhaps BeanListProcessor could provide a method:
public Bean getBean(String[] parsedLine)

**Comment by jbax** [comment]
Use the BeanProcessor (without "List" in the name) and you'll be able to control everything

**Comment by racc** [comment]
Isn't BeanProcessor an abstract class - how do I instantiate it?
And which method am I calling within BeanProcessor to do what I want?

**Comment by jbax** [comment]
Using `new` :) Just provide an implementation to the `beanProcessed` method and you are set.

**Comment by jbax** [comment]
I just copied that from the tutorial. Do the same thing but using the `BeanProcessor` insead of `ObjectRowProcessor`:

```
    ObjectRowProcessor rowProcessor = new ObjectRowProcessor() {
        @Override
        public void rowProcessed(Object[] row, ParsingContext context) {
            //here is the row. Let's just print it.
            println(out, Arrays.toString(row));
        }
    };
```

**Comment by racc** [comment]
I see :)
Cheers mate.
