### ISSUE TITLE
trim() for header-fields?

### ISSUE THREAD

**Issue by lniemann** [uniVocity/univocity-parsers#58]
Hi, i'm currently running into the problem, that the header-fields are extracted without a .trim(), so i have a '\r' in the last element now in a spample feed.

I will work around it by manually trim the header now on startup. I din't find a setting for this like 'trimHeaderOnExtraction'.

Do I miss the setting or is it not available. Interesting feature or not?

**Comment by jbax** [comment]
Did you set the line separator to \r\n ? You can also enable auto-detection
of the line separator.

Alternatively you can read the first line, trim all values, set these as
the headers, and parse again.

If nothing works, please attach a sample of your input data and the code
used to parse it.

Thank you for using our parses!

**Comment by jbax** [comment]
Closing the issue as no answer has been provided. Assuming the line separator was incorrectly configured.
