### ISSUE TITLE
support different delimiter with the same parser

### ISSUE THREAD

**Issue by chesterxgchen** [uniVocity/univocity-parsers#59]
Can you set different delimiters ( instead of default "," ) using settings ? If yes, can you show an example in the setting example ?

**Comment by jbax** [comment]
Did you try:

CsvSettings.getFormat().setDelimiter (';');

?

**Comment by chesterxgchen** [comment]
Thanks for the pointer. 

 Notice that setDelimiter() takes a Char instead of String, we can't set delimiter as  Ctrl-A ("\u0001"). 
Is there a way to get around this ?

**Comment by jbax** [comment]
We don't support String as the parser won't accept more than one character as the delimiter. Try the hex representation of `"\u0001"` to get what you want:

```
    settings.getFormat().setDelimiter((char)0x01);
```
