### ISSUE TITLE
provide something like "getComments()"

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#62]
I just had a first look at univocity-parsers and they seem to be really great already.
One feature I discovered in the desciption and tryed out is to set a comment-indicator so filecomments are skipped. While this is great for parsing the real content it would be best if the RowProcessor could provide them by calling getComments() returning a String[] containing the lines.
This would be very handy for further parsing them with a second parser or manually, for example if there are version-information in the comments which need to be validated or something like this.

**Comment by jbax** [comment]
Great suggestion! I've implemented support for this and submitted another SNAPSHOT build to include these changes. You can get all comments, or the last parsed comment from either the parser itself of, when using a `RowProcessor`, from the `ParsingContext` object.

See methods `getComments` and `getLastComment`.

Thank you for using our parsers!

**Comment by blackfoxoh** [comment]
Thank you very much for this ultrafast implementation! 
I've tryed it and it works like a charm.
There is just a little thing I came over: I tryed the following
      settings.setCommentCollectionEnabled(true);
      settings.setNumberOfRecordsToRead(0);
and expected with this settings I could just collect all comments allover the file as the javadoc for "setNumberOfRecords()" says " A negative value indicates there's no limit ".
To me it seems as zero results in "no limit" as well?

**Comment by jbax** [comment]
Thank you for raising this little bug. I've fixed it in [this commit](https://github.com/uniVocity/univocity-parsers/commit/089d33fe7a04b309562012bca0e8ec0e3d244d26). Also refer to the [test case built for this issue] (https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_62.java)
