### ISSUE TITLE
FixedWidth - datatype dependend padding

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#64]
I am wondering if there is a possibillity to write FixedWidth-files with having different padding-chars, for example blanks for textual fields and "0" for numeric fields and writing numeric values right-justified? 
When parsing this works automatically as leading "0" are dropped during the conversion.
Or did I just missed a setting which achieves this while writing e.g. Integervalues?

**Comment by blackfoxoh** [comment]
ok, found `FixedWidthFieldLengths.setAlignment()`-methods

**Comment by jbax** [comment]
Currently you can't use different padding characters per field, but it's not difficult to include such a feature. I'll have a look. Thank you!

**Comment by jbax** [comment]
Implemented support for field-based padding in [this commit](https://github.com/uniVocity/univocity-parsers/commit/0f9b45f70a7dccbe850c51bbd75d0477ad9189c3).

Now you can use `fieldLengths.setPadding('0', 1, 4, 10);` to use `0` as the padding for columns at positons 1, 4 and 10.

Or fieldLengths.setPadding('0', 'plzV', 'ziel2'); to use `0` as the padding for fields named "plzV" and "ziel2".

Use the settings object of either the FixedWidthWriter/Parser to call `setUseDefaultPaddingForHeaders(boolean);`

This determines whether or not to use the default padding (set in the FixedWidthFormat object) to parse/write headers. You might not want to have a header named "0000plzV".

**Comment by jbax** [comment]
Another SNAPSHOT build released to include these changes. Please test and provide feedback as we are targeting to release the final 2.0.0 build at this weekend.

**Comment by blackfoxoh** [comment]
I've given it a first try - thank you, works really great.
And best that you thought of the default-padding for headers. In my opinion this could even default to `true` as in most cases this might be what is desired.

A setting `setUseDefaultAlignmentForHeaders(boolean)` (ok, what is default? `FieldAlignment.LEFT` as it is used when nothing else is specified or make it possible to explicitly set it as well?) accordingly would make it perfect.

**Comment by jbax** [comment]
support for default header alignment implemented. Use `settings.setDefaultAlignmentForHeaders(FieldAlignment);`

The default option is `null` in which case the column alignment will be used when writing the headers.
