### ISSUE TITLE
Wrong Output with FixedWidthWriter and BeanWriterProcessor

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#65]
Having the following Bean
```java
   public static class Le {
      @Parsed
      private Integer plzV;
      @Parsed
      private Integer plzB;
      @Parsed
      private String ziel;
   }
```
and the following code to write a fixedwidth-file:
````java
      List<Le> tofLes = new ArrayList<Le>();
      for (int i =0; i<3;i++) {
         Le le = new Le();
         le.plzV=i;
         le.plzB=i+10;
         le.ziel="ziel"+i;
         tofLes.add(le);
      }
      
      FixedWidthFieldLengths fieldLengths = new FixedWidthFieldLengths(20,8);
      FixedWidthWriterSettings fwws = new FixedWidthWriterSettings(fieldLengths);
      fwws.selectFields("ziel","plzV");
      fwws.setHeaderWritingEnabled(true);
      BeanWriterProcessor<Le> rowWriterProcessor = new BeanWriterProcessor<Le>(Le.class);
      fwws.setRowWriterProcessor(rowWriterProcessor);
      FixedWidthFormat format = new FixedWidthFormat();
      format.setPadding('_');
      fwws.setFormat(format);
      
      FixedWidthWriter fww = new FixedWidthWriter(new File("c:/tmp/test.txt"),fwws);
      fww.processRecords(tofLes);
      fww.close();
````
results in 
````
plzV________________plzB____
0___________________________
1___________________________
2___________________________
````
but expected
````
ziel________________plzV____
````
with appropriate values...
(using the latest snapshot: "univocity-parsers-2.0.0-20160115.071607-26")

**Comment by blackfoxoh** [comment]
Ok, seems I was on the wrong track. Works when defined as
````java
FixedWidthFieldLengths fieldLengths = new FixedWidthFieldLengths();
fieldLengths.addField("ziel", 20, FieldAlignment.LEFT).addField("plzV", 8, FieldAlignment.RIGHT);
````
Because of the classname FixedWidthField**Lengths** I didn't expect much more as the lengths there. Sorry, my fault. Therefore this is at most a opportunity for improving the javadoc (of method `selectFields()`) to guide stupid users like me :-)

**Comment by jbax** [comment]
I'll have a look an try to improve the API so this gets less tricky. Reopening.

**Comment by jbax** [comment]
Using the original code you can get the result you intended by doing the following.

```
//fwws.selectFields("ziel","plzV");
fwws.setHeaders("ziel","plzV");
```

I agree that the confusion could be prevented with better documentation in the `selectFields()` method, so I've updated the javadoc in [this commit](https://github.com/uniVocity/univocity-parsers/commit/b7d9f956f7013e24409908e83a7ec5592780d7e3).

Hopefully it makes things clearer.
Thank you for your input!
