### ISSUE TITLE
close() of AbstractWriter is not idempotent as it should be

### ISSUE THREAD

**Issue by jpcooper** [uniVocity/univocity-parsers#67]
writer.flush() should not be called in the definition of close() of AbstractWriter. As per the definition of java.io.Writer.close(), closing a previously closed stream should have no effect.

However, flushing an already closed stream throws an IOException. Therefore closing an already closed AbstractWriter throws an exception where it shouldn't.

**Comment by jbax** [comment]
Thank you for pointing that out! It's been fixed.

**Comment by jpcooper** [comment]
Thanks.
