### ISSUE TITLE
How to parse rows on demand?

### ISSUE THREAD

**Issue by xiaom** [uniVocity/univocity-parsers#68]
Hello,

I am using the parser to parse a large CSV file and I want to do a random sampling on the rows in the file. For example, I only want to parse rows with an even row number. Is there any good approach to do it?

Thanks!

**Comment by jbax** [comment]
You can achieve this easily by reading the file iteratively:

```
	parser.beginParsing(newReader(csvFile));
	Object[] row;
        boolean skip = false;
	while ((row = parser.parseNext()) != null) {
		if(!skip){
			process(row); //do what you need here.
		}
		skip = !skip;
	}
```

A slightly faster approach would be using your own dedicated `RowProcessor` for doing what you need.
