### ISSUE TITLE
writer.processRecord(Map) throws unexpected exception if missing writer processor...

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#69]
I have tryed the following, forgetting to add a writer processor:
````java
CsvWriterSettings settings = new CsvWriterSettings();
settings.setHeaders("col2", "col5", "col3", "col4", "col1", "col6");
CsvWriter writer = new CsvWriter(new File("path/to/file"), settings);

Map<String, Object> rowData = new HashMap<String, Object>();
for (int i = 1; i <= 4; i++) {
   rowData.put("col" + i, "inh" + i);
}

writer.processRecord(rowData);
````
This throws a `TextWritingException: Not all values associated with the last record have been written to the output. Hint: use 'writeValuesToRow()' or 'writeValuesToString()' to flush the partially written values to a row.`
As of the javadoc of `processRecord(Map)` I would expect `An IllegalStateException will be thrown if no RowWriterProcessor is provided [...]` 

Seems to be a specific case with `processRecord(Map)` as `writer.processRecord("Test");` throws the expected IllegalStateException.

**Comment by jbax** [comment]
Thank you for reporting this issue! It's been fixed and a new SNAPSHOT build has been released to include this bugfix.

**Comment by blackfoxoh** [comment]
retested: now always throws a `TextWritingException` with correct message. You might want to adjust the javadoc of `writer.processRecord();` as there it still says `An IllegalStateException will be thrown if no RowWriterProcessor is provided...`
Hope I've got your intention right because of the referenced commit just shows adding a new unittest checking for TextWritingException. The actual commit for the fix I couldn't find here on github but the code in the new snapshot indeed is changed :-) ...

**Comment by jbax** [comment]
Ha, thanks for the tip. My last commit has the updated javadoc.
