### ISSUE TITLE
How get delimiter founded from  setDelimiterDetectionEnabled?

### ISSUE THREAD

**Issue by p4535992** [uniVocity/univocity-parsers#70]
Hi, in the new version 2.0.0,  you have add a new method  "setDelimiterDetectionEnabled", how can i get the char value of the delimiter found from your marvelous parser? I try with the "getDelimiter" from the CSVFromat but i must miss something.
I show with a example what i need to do:
```java
            CsvParserSettings parserSettings = new CsvParserSettings();
            parserSettings.setLineSeparatorDetectionEnabled(true);
            RowListProcessor rowProcessor = new RowListProcessor();
            parserSettings.setRowProcessor(rowProcessor);
            parserSettings.setHeaderExtractionEnabled(true);
            parserSettings.setDelimiterDetectionEnabled(true);
            CsvParser parser = new CsvParser(parserSettings);
            parser.parse(fileInputCsv);
            //GEt content
            List<String[]> content =  new ArrayList<>();
            content.addAll(rowProcessor.getRows());
            //Get delimiter 
           char delimiter = ??????????      
```

**Comment by jbax** [comment]
You are not the first user asking this, so I've added the `CsvParser.getDetectedFormat()` method in the latest 2.0.0-SNAPSHOT. This will give you an instance of `CsvFormat` with the detected elements.

Thank you for using our parsers!
