### ISSUE TITLE
Conversion interface

### ISSUE THREAD

**Issue by helt** [uniVocity/univocity-parsers#72]
it is not clear which order is relevant for reading / writing...

**Comment by jbax** [comment]
Examples?

**Comment by helt** [comment]
well.

```
public class InstantToStringConverter implements Conversion<String, Instant> {}
```
will work, while
```
public class InstantToStringConverter implements Conversion<Instant, String> {}
```
throws class cast exceptions, so the source of the error is not obvious...

**Comment by jbax** [comment]
That's because the conversion class performs the conversion from AND to a type.

From the signature, your example converts from String to Instant (
```
public class InstantToStringConverter implements Conversion<String, Instant> {}
```

This will convert from Instant to String
```
public class InstantToStringConverter implements Conversion<Instant, String> {}
```
But your class name is misleading. The name tells one thing and type signature another.

If you want to use this when parsing, it can only be used after some other conversion has been applied to the input, and transformed the value into an Instant, for your implementation to convert the instant to a String.

Hope this helps.

**Comment by jbax** [comment]
Also, check the javadoc:

```
 ...
 * @param <I> The input type to be converted to the output type <b>O</b>
 * @param <O> The type of outputs produced by a conversion applied to the an input <b>I</b>
 * ...
 */

public interface Conversion<I, O> {
...
```

**Comment by jbax** [comment]
Lastly, you could use [ObjectConversion] (https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/conversions/ObjectConversion.java) to implement conversions from String to something else. This is the base class of most conversions implemented by the library.

If you look at the other conversions, you'll find that they don't have a "FromAtoB" pattern to their names, as Strings are the only input type available when parsing. When writing we want Strings to be generated at the end. I suggest you to create an `InstantConverter` that extends from  [ObjectConversion] (https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/conversions/ObjectConversion.java).

**Comment by helt** [comment]
yes, the class name is a bad one. But thats not the point im tryig to raise here. My problem is more a "how to use" problem. The javadoc of `Conversion` is correct although not sufficient. I cannot infer whether the field `Foo` is input or output. Because i dont know whether `execute` or `revert` is used during conversion from Bean to csv-row.

Addedum: An example.

I do annotate a pojo-field with a 
```
@Convert(conversionClass = FooConversion.class)
public Foo foo;
```
and then there are two candidates for implemetation:
```
public class FooConversion implements Conversion<Foo, Bar>
public class FooConversion implements Conversion<Bar, Foo>
```
Based on the javadoc of `Conversion<I, O>` interface, it is not obvious (to me) which candidate is the correct one (the one that will work with `CsvWriter`). I initially thought its `Conversion<Foo,Bar>` but its not (and i had to go through some strange exceptions).

**Comment by jbax** [comment]
`execute` is for parsing. Conversions can be chained but they will invariably start from a `String` (the original content parsed from a field) and the result of the conversion (or sequence of conversions) will be assigned to the annotated field.

`revert` is for writing. In this case your non-string value will be sent to the `revert` operation of a conversion to the output.

You will get errors if the input of your conversion methods (`execute` or `revert`) is not of the expected type.

Your `Conversion<Foo, Bar>` implies that the `execute` method will receive a `Foo` object, and convert it to a `Bar` object. You will need to have some other conversion applied to generate the input `Foo` object, probably a `Conversion<String,Foo>`. If you chain both conversions you will end up with the following sequence: `FirstConversion<String, Foo>` and `SecondConversion<Foo, Bar>`, and the `execute` method will perform the *String -> Foo -> Bar*

If `Foo` is a complex type, this will only work if the String value of single field of your input represents multiple elements, something like:

```
value1, "value2.1,value2.2, value2.3", value3
```

Where you can break down the parsed value in the second column (i.e. "value2.1,value2.2, value2.3") into 3 (or more) distinct values that you can use to initialize an instance of your `Foo` class.

I can be of more help if you could provide a sample of the input you are trying to parse and the classes you are creating.

**Comment by helt** [comment]
Hi jbax.

I dont have a problem with the usage after i have tried to create a converter and failed and retried. I have understood it. I thought, that it would be beneficial for others if the javadoc would be more elaborate in this matter, so they dont run through the same trial-and-error phase until they got the converters right...
