### ISSUE TITLE
Parsing complex csv

### ISSUE THREAD

**Issue by mdanetzky** [uniVocity/univocity-parsers#77]
I need to parse following csv line:

field1,"inner quote" field2,"12,34",",5",

Only third field ("12,34") is surrounded by quotes. Is there any way to do it with univocity?

**Comment by jbax** [comment]
I'm assuming you want to parse this row to produce the following values:

- field1
- "inner quote" field2
- 12,34
- ,5
- <null>

As your quote character is `"`, and the delimiter is `,` this is currently unparseable but it seems easy to make it work. I'll have a snapshot build ready with support for this later.

**Comment by jbax** [comment]
Done. Update to univocity-parsers-2.1.0-SNAPSHOT and use 

```
settings.setParseUnescapedQuotesUntilDelimiter(true);
```

to parse this as you expect.

**Comment by mdanetzky** [comment]
This is great! Thank you so much.

My concern is, that ",5" could be interpreted as one field containing ,5 or two fields separated by a comma and containing " and 5" respectively. 
Since the lack of precaution in csv production has reached unprecedented levels in recent years I am thinking of a csv parser, that could be taught all the edge cases. The simplest form would consist of the lists of delimiters. Given the same csv line as above:
`field1,"inner quote" field2,"12,34",",5",`
Example list of delimiters separated with pipes:
`,|,"|",|,|,|,`
would produce:
- field1
- "inner quote" field2
- 12,34
- "
- 5"
- &nbsp;

Whereas this list:
`,|,"|","|",|,`
would produce:
- field1
- "inner quote" field2
- 12,34
- ,5
- &nbsp;

**Comment by jbax** [comment]
This is not going to be implemented. However, we can build a custom version for your particular use case through our commercial support. Feel free to send us an e-mail to support@univocity.com for more information.

Best regards

**Comment by jbax** [comment]
Released version 2.0.2 with the `parseUnescapedQuotesUntilDelimiter` option as it was being requested by other users as well.
