### ISSUE TITLE
A way to disable default type conversion

### ISSUE THREAD

**Issue by mdanetzky** [uniVocity/univocity-parsers#80]
I have a complex parser, that converts String to BigDecimal and is aware of comma/dot and currency name issues. I wrapped it in a Convert based class and used it in a Bean parser. Unfortunately the type conversion kicks in before my converter and I get a java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String.
Is there any way to disable the default conversion for the field or converter?

**Comment by jbax** [comment]
Disable the default conversion by setting `applyDefaultConversion=false` on the `@Parsed` annotation:

```
	@Convert(conversionClass = MyBigDecimalConversion.class)
	@Parsed(field = "SomeAmount", applyDefaultConversion = false)
	private BigDecimal myNumericField;

```

Thanks for using our parsers!
