### ISSUE TITLE
Null characters in my CSV

### ISSUE THREAD

**Issue by xkrt** [uniVocity/univocity-parsers#82]
Hi,

My CSV files sometimes corrupted (many null characters inside some rows) and I have exception:
```
Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 4096
Identified 1 null characters (' ') on parsed content. This may indicate the data is corrupt or its encoding is invalid. Parsed content:
	<content here>\0
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=true
	Autodetect quotes=false
	Column reordering enabled=true
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=true
	Ignore trailing whitespaces=true
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Parse unescaped quotes=true
	Row processor=none
	RowProcessor error handler=null
	Selected fields=none
	Skip empty lines=trueFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\r\n
		Quote character=`
		Quote escape character="
		Quote escape escape character=null
```

Can I configure parser skip this bad lines and keep going to next line?
In fact, it will be helpful to skip any "error" rows and keep parsing next.

**Comment by jbax** [comment]
The first problem is your `java.lang.ArrayIndexOutOfBoundsException - 4096`. This means you are parsing a value with more than 4096 characters, and the parser is configured throw an error at you if anything goes beyond that.

You can define a more appropriate number of characters to be read on each value by setting `settings.setMaxCharsPerColumn(int)` to a large number. In general, it's no problem to have `\0` as part of your input, but it might mean you are reading corrupt data so please verify the data is good at the point where the exception occurred (the `TextParsingException` gives you character and line number from where things blew up).

The second problem is that your input might actually be corrupt and can't be parsed reliably from that point onward. Therefore the line is not skipped and the process is aborted. If you simply skip the line you might end in the middle of another value that contains line separators (i.e. the next line might just be part of a multi-line value), or an incomplete line, and get further errors.

If you want to insist in skipping lines when the parser throws errors at you, you can read the lines using java's `java.io.BufferedReader.readLine()` to get a `String` and then call `parser.parseLine(String)`, ignoring when a line fails to be parsed.
