### ISSUE TITLE
Column type detection?

### ISSUE THREAD

**Issue by rhl-** [uniVocity/univocity-parsers#83]
Hi,

Is it possible for univocity parser to detect the type of a column? for example, have it store a boolean[] which specifies if a column contains strings which can all be converted to numbers, (perhaps after ignoring null, missing, values?) similarly an array just to determine if columns contain null, or missing values?

**Comment by jbax** [comment]
Thanks for the suggestion, but you can create your own `RowProcessor` implementation and use it to collect any information about your data, then make it report back to you. 

There's no need to add this to the API.
