### ISSUE TITLE
EnumSelector.CUSTOM_METHOD dont work

### ISSUE THREAD

**Issue by humsp** [uniVocity/univocity-parsers#88]
If have tried to use the EnumSelector.CUSTOM_METHOD as follows but it don't work.

```
...

public enum VendorID implements TypedEnum<Integer> {
    CREATIVE_MOBILE_TECHNOLOGIES_LLC(1),
    VERI_FONE_INC(2);

    final int value;

    VendorID(final int value) {
        this.value = value;
    }

    public static VendorID valueof(final int value) {
        for (final VendorID typе : VendorID.values()) {
            if (typе.getValue() == value) {
                return typе;
            }
        }
        return null;
    }

    @Override
    public Integer getValue() {
        return value;
    }
}

@EnumOptions(selectors = EnumSelector.CUSTOM_METHOD, customElement = "valueOf")
@Parsed(field = "VendorID")
private VendorID vendorID;

...
```

I got this exception:

> com.univocity.parsers.common.DataProcessingException: Error processing annotation 'EnumOptions' of field 'vendorID' in Taxi.TaxiCsvBean. Unexpected error identifying conversions to apply over field vendorID of class Taxi.TaxiCsvBean
> Internal state when error was thrown: charIndex=0
> Internal state when error was thrown: charIndex=0
> 	at com.univocity.parsers.common.processor.BeanConversionProcessor.setupConversions(BeanConversionProcessor.java:177)
> 	at com.univocity.parsers.common.processor.BeanConversionProcessor.processField(BeanConversionProcessor.java:95)
> 	at com.univocity.parsers.common.processor.BeanConversionProcessor.initialize(BeanConversionProcessor.java:69)
> 	at com.univocity.parsers.common.processor.BeanProcessor.processStarted(BeanProcessor.java:67)
> 	at univocityExtension.BeanIteratorProcessor.processStarted(BeanIteratorProcessor.java:82)
> 	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:216)
> 	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:592)
> 	at Test.main(Test.java:50)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: com.univocity.parsers.common.DataProcessingException: Unexpected error identifying conversions to apply over field vendorID of class Taxi.TaxiCsvBean
> Internal state when error was thrown: charIndex=0
> 	at com.univocity.parsers.annotations.helpers.AnnotationHelper.getConversion(AnnotationHelper.java:236)
> 	at com.univocity.parsers.annotations.helpers.AnnotationHelper.getConversion(AnnotationHelper.java:83)
> 	at com.univocity.parsers.common.processor.BeanConversionProcessor.setupConversions(BeanConversionProcessor.java:169)
> 	... 12 more
> Caused by: java.lang.IllegalStateException: Unable to access custom method 'valueOf' in enumeration type Taxi.TaxiCsvBean$VendorID
> 	at com.univocity.parsers.conversions.EnumConversion.<init>(EnumConversion.java:134)
> 	at com.univocity.parsers.annotations.helpers.AnnotationHelper.getConversion(AnnotationHelper.java:126)
> 	... 14 more
> Caused by: java.lang.NoSuchMethodException: Taxi.TaxiCsvBean$VendorID.valueOf()
> 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
> 	at com.univocity.parsers.conversions.EnumConversion.<init>(EnumConversion.java:129)
> 	... 15 more

Did i use your project wrong?

I had looked at your  [EnumConversion](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/conversions/EnumConversion.java) class. If i understand the code right, i think the problem comes from the method enumType.getDeclaredMethod() from java.lang.Class. It throws an Exception when it don't find a field, and never return null.

See Method:

 ```
@CallerSensitive
    public Field getDeclaredField(String name)
        throws NoSuchFieldException, SecurityException {
        checkMemberAccess(Member.DECLARED, Reflection.getCallerClass(), true);
        Field field = searchFields(privateGetDeclaredFields(false), name);
        if (field == null) {
            throw new NoSuchFieldException(name);
        }
        return field;
    }
```

If you look at the EnumConversion code, then the **if (field == null)** never reached.

```
try {
    field = enumType.getDeclaredField(customEnumElement);
    if (!field.isAccessible()) {
        field.setAccessible(true);
    }
} catch (Throwable e) {
    fieldError = new IllegalStateException("Unable to access custom field '" + customEnumElement + "' in enumeration type " + enumType.getName(), e);
}

if (field == null) {
    try {
        method = enumType.getDeclaredMethod(customEnumElement);
        if (!method.isAccessible()) {
            method.setAccessible(true);
        }
    } catch (Throwable e) {
        methodError = new IllegalStateException("Unable to access custom method '" + customEnumElement + "' in enumeration type " + enumType.getName(), e);
    }
    if (method != null) {
        if (method.getReturnType() == Void.class) {
            throw new IllegalArgumentException("Custom method '" + customEnumElement + "' in enumeration type " + enumType.getName() + " must return a value");
        }
        if (!selectorSet.contains(EnumSelector.CUSTOM_METHOD)) {
            selectorSet.add(EnumSelector.CUSTOM_METHOD);
        }
    }
} else if (!selectorSet.contains(EnumSelector.CUSTOM_FIELD)) {
    selectorSet.add(EnumSelector.CUSTOM_FIELD);
}
```

Thank you for helping

**Comment by jbax** [comment]
Shouldn't you be using `getValue` instead of `valueOf`? The `valueOf` method in your enumeration requires a parameter. 

Changing the annotation to this works fine for me:

```
		@EnumOptions(selectors = EnumSelector.CUSTOM_METHOD, customElement = "getValue")
		@Parsed(field = "VendorID")
		private VendorID vendorID;
```

Test input I used:

```
	    VendorID,Name
	    1,Foo
	    2,Bar
```

**Comment by humsp** [comment]
Yes you are right, i misunderstood the EnumOptions. Thank you for your support.
