### ISSUE TITLE
ArrayIndexOutOfBoundsException during fixedwidth parsing

### ISSUE THREAD

**Issue by Lonzak** [uniVocity/univocity-parsers#89]
I try to parse a fixed width string however always get an AIOOBE. The weird thing is that the length of the array is 603 - but of course in a 0-based index array there is no index at 603. But even if I set maxColumns() to 602 I still get the error. (Unfortunatly I can't post the string I read.) I played around with some of the settings however didn't succed. If I add an any String e.g. "\r\n" or a blank I get an quite extensive error stating that "the Number of columns processed may have exceeded limit of 603 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can ...." Any idea what the error is?
Here is the exception:

```
java.lang.ArrayIndexOutOfBoundsException: 603
	at com.univocity.parsers.common.ParserOutput.emptyParsed(ParserOutput.java:256)
	at com.univocity.parsers.common.AbstractParser.handleEOF(AbstractParser.java:169)
	at com.univocity.parsers.common.AbstractParser.parseLine(AbstractParser.java:496)
	at com.univocity.parsers.common.AbstractParser.parseRecord(AbstractParser.java:455)
	at com.somepackage.parse(SomeClass.java:93)
        at  ...... 

```

I init the parser like that (replaced some values for clarity):
```
FixedWidthFields lengths = new FixedWidthFields(String[], int[]);
FixedWidthParserSettings settings = new FixedWidthParserSettings(lengths);

//sets the character used for padding unwritten spaces in the file
settings.getFormat().setPadding(' ');
settings.getFormat().setLineSeparator("\n");
settings.setMaxColumns(602);
settings.setLineSeparatorDetectionEnabled(true);
//settings.setColumnReorderingEnabled(false);

// create a fixed-width parser with the given settings
FixedWidthParser parser = new FixedWidthParser(settings);
Record requestRecord = parser.parseRecord(dumpLine);
```

**Comment by jbax** [comment]
I'm sorry but this is not enough information. Can you provide a fictional example of an input and field lengths to parse that input, so I can create a unit test that reproduces the error?

**Comment by Lonzak** [comment]
Attached a test case.
The int[] has a size of 603.
All length values added make 1804 which is the length of the string.

[Test.txt](https://github.com/uniVocity/univocity-parsers/files/289855/Test.txt)

**Comment by jbax** [comment]
Thank you for that! The issue with the `maxColumns` setting. If you set it to the maximum number of columns +1 your code works. Just call 

```
settings.setMaxColumns(604);
```

I'll fix the bug right now.

**Comment by jbax** [comment]
Fixed on commit: https://github.com/uniVocity/univocity-parsers/commit/0e3ee0c5c947d720fa662265491978b68649a892

Thank you!

**Comment by Lonzak** [comment]
You are welcome and thank you for your immediate reply and the fix...
