### ISSUE TITLE
Fixedwidth parsing ignores trailing and leading whitespaces

### ISSUE THREAD

**Issue by Lonzak** [uniVocity/univocity-parsers#91]
I have the following input:
"START&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;J&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;END"
and if I parse the blanks will be removed:
"START, J, END"

I set the following settings, however no effect:
```
settings.setIgnoreLeadingWhitespaces(false);
settings.setIgnoreTrailingWhitespaces(false);
settings.setColumnReorderingEnabled(false);
```
Is that a bug or do I miss an option here?
[Test.txt](https://github.com/uniVocity/univocity-parsers/files/290647/Test.txt)

**Comment by jbax** [comment]
That's because the default padding is the whitespace. Padding just means unwritten content so it doesn't become part of the value.

Try setting the padding to underscore using `	settings.getFormat().setPadding('_');` to see the difference leading/trailingWhitespaces make.

**Comment by Lonzak** [comment]
thanks - that works.
Theoretically - what happens if string contains a '_'`?

And a second question: Is it possible to supress the '\n' at the line end?

**Comment by jbax** [comment]
If the '_' is not at the beginning or end then it's considered part of the value (also depends on the alignment). If you want all characters, including padding, white space, etc then set the padding to `'\0'`.

You can suppress the '\n' now. I just fixed this in [this issue] (https://github.com/uniVocity/univocity-parsers/issues/90). I've released version 2.1.2-SNAPSHOT to include this bugfix.

Hope this helps!

**Comment by Lonzak** [comment]
What I meant is for writing:
I use a FixedWidthWriter.java to create a fixedwidth String. However I don't want, that at the end a '\n' is added. If I set 
`settings.getFormat().setLineSeparator("");`
I get an error stating that the line separator can't be empty...

**Comment by jbax** [comment]
The fixedwidth writer doesn't provide an option to NOT write the line ending but it certainly should. I'll make add this option now and release another snapshot build.

**Comment by Lonzak** [comment]
Thanks - highly appreciated!

**Comment by jbax** [comment]
Fixed. A new 2.1.2-SNAPSHOT build is already available. You should see an additional setting:

```
fixedWidthWriterSettings.setWriteLineSeparatorAfterRecord(false);
```

This should do the trick.
Thanks for using our parsers!
