### ISSUE TITLE
Last EmptyValue get recognized as NullValue in the last line without newline character

### ISSUE THREAD

**Issue by nabito** [uniVocity/univocity-parsers#92]
Say you have this CSV:

ID, Name, Surname, Age, Salary, Supervisor
1, Robert, Kurosaki, 44, xxx, ""
2, John, Konor, "",               yyy, Tony Stark
3, Tony, "", 66, ,""

With the last line ended without new line character.
With the following settings you'll discover the bug:

		CsvParserSettings settings = new CsvParserSettings();
		settings.setEmptyValue("hmm?");
		settings.setNullValue("n/a");

The empty value inside quotes in the last column of the last line is mistaken for NullValue, resulting in the following:

ID Name Surname Age Salary Supervisor 
1 Robert Kurosaki 44 xxx hmm? 
2 John Konor hmm? yyy Tony Stark 
3 Tony hmm? 66 n/a n/a

A newline character at the last line solve the problem, but just in case you want to make the parser more robust with sloppy csv file.

**Comment by jbax** [comment]
Great catch, thank you!
It's now fixed and another 2.1.2-SNAPSHOT build is available with the fix for this one.

Thanks for using our parsers!
