### ISSUE TITLE
Parsing csv files without header crashes with ArrayIndexOutOfBoundException

### ISSUE THREAD

**Issue by Lonzak** [uniVocity/univocity-parsers#93]
I try to parse csv files and if the file has a header everything is fine.
If however a file doesn't have a header and I try to access it via its index (`record.getString(0)`) it crashes with a AIOOBE.
I set the `settings.setHeaderExtractionEnabled();` to false however no change.
The only workaround I found is to set `settings.setHeaders("","","","");`.

Is there a way to read a headerless csv without specifying any headers? (Also tried setting it to <null>)

**Comment by jbax** [comment]
Thank you so much for reporting this error! It's been fixed in the latest commit and I released another 2.1.2-SNAPSHOT build already to include this fix.
