### ISSUE TITLE
remove quotes around all cells

### ISSUE THREAD

**Issue by rhl-** [uniVocity/univocity-parsers#95]
Does the parser support parsing 

"foo", "bar" as [foo,bar] 
while maintaining 

"\"foo\"", "\"bar,\"" as ["foo", "bar"] ?

**Comment by jbax** [comment]
Currently it doesn't. Will be implemented in a future 2.2.0 version.

**Comment by jbax** [comment]
Implemented support for this in version 2.2.0-SNAPSHOT.
Call `setKeepQuotes(true);` to keep the quote characters as originally found in the input.

Additionally, if you enable the already existing flag `setKeepEscapeSequences(true);` you'll retain the original content of the entire field.
