### ISSUE TITLE
Cell with only whitespace chars (NullValue) mistakenly treated as EmptyValue in last column

### ISSUE THREAD

**Issue by nabito** [uniVocity/univocity-parsers#97]
Hi again, thanks for great parser!

I just found a subtle non-consistent behavior of the program (bug?)

Says, we have this settings:
		settings.setEmptyValue("");
		settings.setNullValue(null);
And we have a CSV with this contents:

![screen shot 2016-06-13 at 3 16 40 am](https://cloud.githubusercontent.com/assets/1082880/15993019/5a59cd0a-3115-11e6-912e-ae825ecebde2.png)

Please notice the value of cell in the last column of second row, it contains space characters.
The parser will recognized the cell as EmptyValue and leave empty string intact, even though the space chars are not inside double quotes.

ID,Name,Surname,Age,Salary,Supervisor
1,Robert,Kurosaki,null,null,null
2,Clark,Kent,null,null,
3,John,Konor,,  ,null

This is tested on 2.1.1 as well as 2.1.2-SNAPSHOT.

**Comment by jbax** [comment]
That's a great catch! I just fixed this in the latest commit and version 2.2.0-SNAPSHOT has been released to include the bugfix.

Thank you for using our parsers!
