### ISSUE TITLE
Operate directly on UTF-8 encoded bytes

### ISSUE THREAD

**Issue by rxin** [uniVocity/univocity-parsers#99]
Apache Spark started using the univocity parser for CSV parsing in 2.0. Internally in Spark we don't use Java string but rather directly UTF-8 encoded bytes (we use a combination of on-heap byte arrays as well as offheap memory). Spark currently reads CSV files in as bytes, convert those into Java String, run through univocity, and then convert those back into UTF-8 bytes. This is pretty expensive.

Is there a way to extend univocity to support operating directly on UTF-8 encoded bytes?

**Comment by jbax** [comment]
The parser works with an instance of `java.io.Reader` and also `java.io.InputStream`. Did you try to parse using something like this?

```
		byte[] bytes = getUTF8EncodedBytesFromSomewhere();
		InputStream inputStream = new ByteArrayInputStream(bytes);

		CsvParser parser = new CsvParser(new CsvParserSettings());

		parser.beginParsing(inputStream, "UTF-8");
		// or
		parser.parse(inputStream, "UTF-8");
		// or
		parser.parseAll(inputStream, "UTF-8");

```

Internally this just creates a `java.io.Reader` using:

```
	Reader reader = new InputStreamReader(inputStream, "UTF-8");
```

**Comment by jbax** [comment]
Closing as I assume this worked for you.

**Comment by rxin** [comment]
Thanks @jbax. Is there a way for the reader to return bytes rather than java.lang.String?

**Comment by jbax** [comment]
Not sure what you mean. Can you please provide an example of what you'd like to have? Pseudo-code works :)
